### ISSUE TITLE
swupd: journald: output not optimized for tty-less display

### ISSUE THREAD

**Issue by thac0** [clearlinux/swupd-client#1006]
**Describe the bug**
When swupd does its update business, and outputs progress to journald, it results in nonsense. Output needs to know when it is running in a tty-less environment and tune output accordingly.

**To Reproduce**
1. Allow swupd to do an auto-update
1. Run sudo journalctl -b | grep -i swupd
1. See the following

```
Jul 17 10:00:24 localhost swupd[2265]: Update started.
Jul 17 10:00:25 localhost swupd[2265]: Preparing to update from 30390 to 30400
Jul 17 10:00:26 localhost swupd[2265]: Downloading packs (10.71 Mb) for:
... yada yada ...
Jul 17 10:00:26 localhost swupd[2265]: [14B blob data]
Jul 17 10:00:26 localhost swupd[2265]: [14B blob data]
Jul 17 10:00:26 localhost swupd[2265]: [14B blob data]
... repeated many, many times ...
```

**Expected behavior**
When swupd is outputting to journald, it should not attempt to display progress data-- that's the "14B blob data" stuff. Instead, it should simply report when it prepares, starts, and ends the update.

**Environment (please complete the following information):**
 - Clear Linux OS Version: 30400
 - Platform: native; KBL NUC

**Comment by otaviobp** [comment]
Thanks for the report.
This bug was fixed on last swupd release available at 30400. You aren't going to see this output on next update. 
Please reopen the bug if you see that after 30400.
