### ISSUE TITLE
update with uid/gid change

### ISSUE THREAD

**Issue by pohly** [clearlinux/swupd-client#101]
Is swupd supposed to handle OS updates where the IDs defined in /etc/passwd and/or /etc/group change, or is that a situation which needs to be avoided?

Right now, when that happens, "swupd updated" fails with "File content hash mismatch for /var/lib/swupd/staged/05....2bd (bad server data?)" where the file is one of those whose user or group ID changed its numeric value.

The reason is that tar uses the symbolic names during unpacking on the client: it assigns the current numeric ID as defined in /etc, whereas the server used the new numeric ID. Because the numeric ID is the input for hashing, a hash mismatch occurs, which prevents updating.

For bsdtar, adding "--numeric-owner" to the TAR_COMMAND fixes that aspect of the problem. A similar fix should be possible for GNU tar.

But that only addresses a subset of the problem. Processes running with the old ID also need to be restarted, which is harder.

**Comment by matthewrsj** [comment]
> For bsdtar, adding "--numeric-owner" to the TAR_COMMAND fixes that aspect of the problem. A similar fix should be possible for GNU tar.

Now using libarchive, but I was unable to find a solution quickly to replicate --numeric-owner. I can keep looking or... we could expand our manifest format as oft suggested by @icarus-sparry to include UID/GID along with other file metadata and the hash would only be a hash of content.

> But that only addresses a subset of the problem. Processes running with the old ID also need to be restarted, which is harder.

Right, if the process is a service at least the change should be detected by clr-service-restart implemented by @ahkok.

@icarus-sparry can you open an issue with a brief overview of your ideas to expand manifest format? I can close bugs that the proposal fixes once you do that. I think this is one of those resolved issues.

**Comment by icarus-sparry** [comment]
Created #403 for this.

**Comment by matthewrsj** [comment]
thanks @icarus-sparry

**Comment by pohly** [comment]
On Tue, 2018-02-27 at 12:06 -0800, Matthew Johnson wrote:
> Now using libarchive, but I was unable to find a solution quickly to
> replicate --numeric-owner.

One can see in bsdtar how it is implemented:

	if ((bsdtar->flags & OPTFLAG_NUMERIC_OWNER) == 0)
        		archive_write_disk_set_standard_lookup(writer);

https://github.com/libarchive/libarchive/blob/6a9dcf9fc429e2dc9fb08e669bf7b0bed4d5edf9/tar/read.c#L108

swupd-client calls archive_write_disk_set_standard_lookup() in
extract_to() and thus has the problem described in this issue (name for
file from new OS revision looked up in name table from old OS
revision).

Perhaps remove that call?

**Comment by cmarcelo** [comment]
In swupd-client the line mentioned is

https://github.com/clearlinux/swupd-client/blob/master/src/archives.c#L116

From a quick glance it seems that @pohly suggestion is the right thing to do here. If we don't care about the "names" only the numbers, there is no point trying to fix the numbers based on the names (which is what that call set archive to do).

**Comment by cmarcelo** [comment]
I'd reopen this, as this seems to be solvable independently of #403.
I'd rename this issue to something like: "Ignore uname/gname from the tar files".
