### ISSUE TITLE
os-install: Add downloadonly flag

### ISSUE THREAD

**Issue by jwakre** [clearlinux/swupd-client#1017]
**Problem**
It would be useful for the os-install command to populate the statedir without installing content. This would enable offline installs from the cached content.

**Describe the solution you'd like**
* Add `--downloadonly` flag to `os-install` command
* When the `--downloadonly` flag is set, the statedir should be updated, but no content should be installed.

**Comment by otaviobp** [comment]
I just suggest to call this flag --download to be compatible with the update command

**Comment by jwakre** [comment]
> I just suggest to call this flag --download to be compatible with the update command

Earlier I wasn't aware that `swupd update` had this capability. I will add the `--download` flag to the `os-install` and `verify` commands.

**Comment by castulo** [comment]
I think we can close this issue now
