### ISSUE TITLE
Help message of `swupd search-file` is not accurate

### ISSUE THREAD

**Issue by lebensterben** [clearlinux/swupd-client#1019]
This is similar to #961 but not exactly the same.

The man page for `swupd search-file` says

```
          • -l, --library
                Restrict search to designated dynamic shared library paths.

          • -B, --binary
                Restrict search to designated program binary paths.
```

But `swupd search-file -h` gives you

```
   -l, --library           Search paths where libraries are located for a match
   -B, --binary            Search paths where binaries are located for a match
```

This causes some confusion because either -l and -B option only accept a file, not a directory, as its argument. But the wording in the help message is not very clear so users may instead gives a directory path instead.

**Comment by otaviobp** [comment]
Thanks for the report. It looks like the --help message is confusing. The idea is to look for the file that you use as argument in those paths. Let's fix that.
