### ISSUE TITLE
`swupd search-file` without argument outputs contents of all bundles

### ISSUE THREAD

**Issue by lebensterben** [clearlinux/swupd-client#1033]
To reproduce, run `swupd search-file`, you will see that it outputs the files installed by each bundle and even calculated the size it occupies.

If you add `-B` or `-l` flag but still doesn't supply any argument, it will limit the scope to binaries and libraries.

I think it might be better to throw a warning message for the missing argument.

---

But on the other hand, this output is pretty much what people have long been ask for, namely to list files installed by a bundle ( see #971 ).

I suggest to add this functionality to `info` sub-command`, so that `swupd info` without an argument shows OS version, version/content URLs, and maybe some other information. And `swupd info BUNDLE [BUNDLE2...]` gives you the files installed by such bundle.

**Comment by otaviobp** [comment]
I personally like the idea on printing all files when no search string is added to the search-file. For me is like running 'find' without any argument.
And it would be really nice to have a info command like you described. We have several tickets requesting similar things

**Comment by otaviobp** [comment]
Closing this for now. Please reopen if you think that your concern wasn't addressed.
