### ISSUE TITLE
Add swupd <subcommand> to view upstream format

### ISSUE THREAD

**Issue by mvincerx** [clearlinux/swupd-client#1066]
Currently, I can run `swupd -v`, which shows the format that the current/local `swupd`. 

Can we create a `swupd <subcommand>` that allows user to view the latest format on upstream/server?

Maybe we could use `swupd info` of `swupd check-update`--or maybe this should be a `mixer` subcommand. I think it's valuable to users who manage downstream derivatives that track upstream.

**Comment by phmccarty** [comment]
Note that there was a recently merged PR (#1055) related to this request.

Not sure if it will work out-of-the-box for downstream derivatives though.

**Comment by otaviobp** [comment]
The PR is printing only the last version. We still don't have a way to print current (and next) format.

**Comment by bktan8** [comment]
I think `swupd info` should include the content of `/usr/share/defaults/swupd/format`.

**Comment by castulo** [comment]
> I think:
> 
> * `swupd info` should include the content of `/usr/share/defaults/swupd/format`.  Should look something like this:
> 
> ```
> Distribution:      Clear Linux OS
> Installed version: 30940 (format 29)
> Version URL:       https://cdn.download.clearlinux.org/update
> Content URL:       https://cdn.download.clearlinux.org/update
> ```
> 
> * `swupd check-update` should include the content of `/usr/share/defaults/swupd/format` and the latest upstream format.  Should look something like this:
> 
> ```
> Current OS version: 30000 (format 28)
> Latest server version: 30940 (format 29)
> ```

I like the idea but I think that should not be the default behavior. That info could be available through a flag, something like `--detailed` or `--verbose`. A format is something many users don't care about or even know about.

**Comment by bktan8** [comment]
@castulo - sounds good to me!
