### ISSUE TITLE
Integrate clr-user-bundles on swupd

### ISSUE THREAD

**Issue by otaviobp** [clearlinux/swupd-client#1082]
Swupd should support for adding, listing, removing, updating 3rd party bundles using clr-user-bundles support.

**Comment by karthikprabhuvinod** [comment]
@castulo : Should we close #1176  as well?

**Comment by castulo** [comment]
> @castulo : Should we close #1176 as well?

yes I think is been completed

**Comment by castulo** [comment]
All 3rd-party functionality has been implemented. I'm closing this issue.
