### ISSUE TITLE
When json format is used we should print the output of post update scripts in a json format

### ISSUE THREAD

**Issue by otaviobp** [clearlinux/swupd-client#1127]
Swupd calls several commands using exec() and we redirect the output of the command to stdout and stderr. Instead we could read it and print using log functions so we would have them printed in a json format.
Another possible approach is redirect every output of exec() to stderr, so it wouldn't clash with json printed in stdout.

**Comment by karthikprabhuvinod** [comment]
Ya looks like  helper processes run as child processes as part using execve. I think its best to check first we can redirect the output from standard output for this child process to a buffer, jsonify it and write buffer to file.

sending output of exec() to stderr can be little confusing for users.

**Comment by karthikprabhuvinod** [comment]
One of the ways I can envision is:

create a pipe like the below sudo code

int pipe_fd[2];
pipe(pipe_fd);

//child
if (fork() == 0){
close(pipe_fd[0]) . //child does need standard input
dup2(pipe_fd[1], STDOUT) // redirect stdout to pipe
dup2(pipe_fd[1], STDERR) // redirect stderr to pipe
}

// in parent
char buffer[1024]
char *line = NULL;
size_t len = 0;
close(pipe_fd[1]) //parent does need standard output
while ((read = getline(&line, &len, pipe_fd[0])) != -1) {
 info("%s", line)
}

**Comment by karthikprabhuvinod** [comment]
@otaviobp @castulo : Let me know what you guys think about my proposed solution?

**Comment by otaviobp** [comment]
I think that this is the way to go. The only problem is that we are going to be using stdout for errors too, but I think this is ok. We can add a prefix saying it's from an external command too, like:

    info("command: %s", line);
