### ISSUE TITLE
Bad format in swupd json output when using --debug

### ISSUE THREAD

**Issue by castulo** [clearlinux/swupd-client#1128]
**Describe the bug**
When using the `--json-output` flag along with the `--debug`flag the json output is incorrect since one message is being printed outside of the "[" "]".

Example:
```
{ "type" : "debug", "msg" : "No configuration file was found" },
[
{ "type" : "start", "section" : "bundle-remove" },
{ "type" : "info", "msg" : " Removing bundle: ansible" },
```

**To Reproduce**
Run any swupd command with `--json-output` and `--debug`, like `swupd bundle-remove BUNDLE --json-output --debug`

**Expected behavior**
the output should be json parsable

**Environment (please complete the following information):**
 - swupd 3.22.3

**Comment by otaviobp** [comment]
Nice, I think I can solve this with my changes on json lib on top of pr #1105
