### ISSUE TITLE
Test fails to run if there are any test leftovers

### ISSUE THREAD

**Issue by otaviobp** [clearlinux/swupd-client#1135]
If a test is interrupted it can leave some leftovers behind. In this case tests are going to fail to run.
The same occurs when a test is run with KEEP_ENV=true.
In this case we could remove the test leftovers on startup or use a new name for the test environment

**Comment by castulo** [comment]
what do you mean? the tests are supposed to run even if there are leftovers or if the last test was run with KEEP_ENV=true -> https://github.com/clearlinux/swupd-client/blob/master/test/functional/testlib.bash#L3292 are you sure this is happening? I couldn't reproduce it locally

**Comment by otaviobp** [comment]
I didn't remember that patch. So it looks like a bug. The problem is not happening on KEEP_ENV as I said. Just if I ctrl-C the test of if there's any critical error.

How I reproduced it:

    $ ./autogen.sh
    $ make
    $ ./test/functional/update/update-ignore-also-add.bats
     ✗ UPD057: Update a system where also-add dependencies are added in the newer version
       (from function `sign_version' in file test/functional/update/../testlib.bash, line 1305,
        from function `create_version' in file test/functional/update/../testlib.bash, line 1439,
        from function `create_test_environment' in file test/functional/update/../testlib.bash, line 1597,
        from function `test_setup' in file test/functional/update/update-ignore-also-add.bats, line 11,
        from function `setup' in file test/functional/update/../testlib.bash, line 3301,
        from function `bats_test_begin' in file /usr/libexec/bats-core/bats-exec-test, line 88,
        in test file test/functional/update/update-ignore-also-add.bats, line 25)
         `@test "UPD057: Update a system where also-add dependencies are added in the newer version" {' failed with status 3
       Can't open /swupd-client/Swupd_Root.pem for reading, No such file or directory
       140641318724352:error:02001002:system library:fopen:No such file or directory:crypto/bio/bss_file.c:69:fopen('/swupd-client/Swupd_Root.pem','r')
       140641318724352:error:2006D080:BIO routines:BIO_new_file:no such file:crypto/bio/bss_file.c:76:unable to load certificate
       The name provided "update-ignore-also-add_UPD057" doesn't seem to be a valid test environment
    $ ./test/functional/generate-cert.prereq
    $ ./test/functional/update/update-ignore-also-add.bats
     ✗ UPD057: Update a system where also-add dependencies are added in the newer version
       (from function `destroy_test_environment' in file test/functional/update/../testlib.bash, line 1708,
        from function `setup' in file test/functional/update/../testlib.bash, line 3292,
        from function `bats_test_begin' in file /usr/libexec/bats-core/bats-exec-test, line 88,
        in test file test/functional/update/update-ignore-also-add.bats, line 25)
         `@test "UPD057: Update a system where also-add dependencies are added in the newer version" {' failed
       The name provided "update-ignore-also-add_UPD057" doesn't seem to be a valid test environment
       The name provided "update-ignore-also-add_UPD057" doesn't seem to be a valid test environment

And if I remove the test directory update-ignore-also-add_UPD057/, the test runs fine.

**Comment by castulo** [comment]
Oh yeah, we don't have anything in the library to remove the test environment if we do a ctrl-c, maybe we can add a trap to remove the environment in case of ctrl-c.
The other problem you are having is that the function that deletes a test environment has a check to make sure the provided directory actually resembles a test environment, that is it looks for certain directories that are supposed to exist within the test environment to make sure we don't end up deleting something that we were not supposed to, since your test environment failed when it was being created the directories that should exist within it do not exist, so the testlib doesn't want to remove a directory that doesn't look like a test environment. To avoid this kind of problems maybe we could create a control file within the directory, something like ".testlib", and look for that control file to make sure it is a test environment. We could just create that control file as one of the very first steps of the environment creation.

**Comment by karthikprabhuvinod** [comment]
> I didn't remember that patch. So it looks like a bug. The problem is not happening on KEEP_ENV as I said. Just if I ctrl-C the test of if there's any critical error.
> 
> How I reproduced it:
> 
> ```
> $ ./autogen.sh
> $ make
> $ ./test/functional/update/update-ignore-also-add.bats
>  ✗ UPD057: Update a system where also-add dependencies are added in the newer version
>    (from function `sign_version' in file test/functional/update/../testlib.bash, line 1305,
>     from function `create_version' in file test/functional/update/../testlib.bash, line 1439,
>     from function `create_test_environment' in file test/functional/update/../testlib.bash, line 1597,
>     from function `test_setup' in file test/functional/update/update-ignore-also-add.bats, line 11,
>     from function `setup' in file test/functional/update/../testlib.bash, line 3301,
>     from function `bats_test_begin' in file /usr/libexec/bats-core/bats-exec-test, line 88,
>     in test file test/functional/update/update-ignore-also-add.bats, line 25)
>      `@test "UPD057: Update a system where also-add dependencies are added in the newer version" {' failed with status 3
>    Can't open /swupd-client/Swupd_Root.pem for reading, No such file or directory
>    140641318724352:error:02001002:system library:fopen:No such file or directory:crypto/bio/bss_file.c:69:fopen('/swupd-client/Swupd_Root.pem','r')
>    140641318724352:error:2006D080:BIO routines:BIO_new_file:no such file:crypto/bio/bss_file.c:76:unable to load certificate
>    The name provided "update-ignore-also-add_UPD057" doesn't seem to be a valid test environment
> $ ./test/functional/generate-cert.prereq
> $ ./test/functional/update/update-ignore-also-add.bats
>  ✗ UPD057: Update a system where also-add dependencies are added in the newer version
>    (from function `destroy_test_environment' in file test/functional/update/../testlib.bash, line 1708,
>     from function `setup' in file test/functional/update/../testlib.bash, line 3292,
>     from function `bats_test_begin' in file /usr/libexec/bats-core/bats-exec-test, line 88,
>     in test file test/functional/update/update-ignore-also-add.bats, line 25)
>      `@test "UPD057: Update a system where also-add dependencies are added in the newer version" {' failed
>    The name provided "update-ignore-also-add_UPD057" doesn't seem to be a valid test environment
>    The name provided "update-ignore-also-add_UPD057" doesn't seem to be a valid test environment
> ```
> 
> And if I remove the test directory update-ignore-also-add_UPD057/, the test runs fine.

@otaviobp : I was unable to reproduce this as well. I tried your way mentioned above and also terminating with CTRL+C while running through 

`bats test/functional/signature
`

**Comment by otaviobp** [comment]
How to reproduce it:
 - Clone swupd repository
 - Run test/functional/repair/repair-json.bats
