### ISSUE TITLE
Cannot build in clearlinux due to unexpected token

### ISSUE THREAD

**Issue by ericho** [clearlinux/swupd-client#1141]
**Describe the bug**
I'm trying to build swupd-client in clearlinux but configure fails with a syntax error related with bsdiff.

**To Reproduce**
1. Clone this repo
2. Download, build and install libcheck (the same install instructions as .travis.yml)
3. I installed bsdiff with `swupd bundle-add mixer` so I didn't download a build bsdiff as the .travis.yml does.
4. Run `autoreconf --verbose` and then `./configure`

With this I get : 

```
checking whether we are using the GNU C compiler... (cached) yes
checking whether gcc accepts -g... (cached) yes
checking for gcc option to accept ISO C89... (cached) none needed
checking whether gcc understands -c and -o together... (cached) yes
./configure: line 9456: syntax error near unexpected token `bsdiff,'
./configure: line 9456: `PKG_CHECK_MODULES(bsdiff, bsdiff)'
```

**Expected behavior**
swupd-client should be able to build in clearlinux.

**Environment (please complete the following information):**
 - Clear Linux OS Version: 31270
 - Platform: NUC

**Comment by ericho** [comment]
As the error is related with `bsdiff` then I tried to build it, however I get this error after run `./configure`.

```
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for zlib... yes
checking for BZ2_bzBuffToBuffCompress in -lbz2... no
configure: error: the libbz2 library is missing
```

**Comment by otaviobp** [comment]
The problem is that you may have missing dependencies to build swupd. You can try to install one by one, but there's an easier way to do that is to install the dev bundle for suwpd, the os-core-update-dev bundle

**Comment by ericho** [comment]
Thanks @otaviobp for the quick response. Adding the bundle solved the issue.

**Comment by otaviobp** [comment]
Nice. Thanks for reporting the issue
