### ISSUE TITLE
If you bundle-add a bundle that is already installed we should track it

### ISSUE THREAD

**Issue by otaviobp** [clearlinux/swupd-client#1169]
Imagine that you run the following:

```
swupd os-install
swupd bundle-add os-core-update #os-core-plus will be installed as a dependency
swupd bundle-add os-core-plus
```
swupd will track only os-core-update, but if you do:

```
swupd os-install
swupd bundle-add os-core-plus
swupd bundle-add os-core-update
```
swupd will track both os-core-plus and os-core-update

So if you try to bundle-add a bundle that is already installed we should track it.

**Comment by castulo** [comment]
This was supposed to be handled here https://github.com/clearlinux/swupd-client/blob/master/src/bundle_add.c#L249, maybe some corner cases are causing that behavior.

**Comment by otaviobp** [comment]
My bad. I don't know what I did wrong, but I tested that again and this is working fine as expected.
