### ISSUE TITLE
Create a command to manage 3rd-party repositories

### ISSUE THREAD

**Issue by otaviobp** [clearlinux/swupd-client#1176]
Add a new swupd command to manage 3rd-party repositories. Information about repositories should be added in a ini file under /var/lib/swupd/3rd-party/repo.

Add a new repository:
`$ swupd 3rd-party add my_repo https://url`

Remove a repository:
`$ swupd 3rd-party remove my_repo https://url`

List all repositories:
`$ swupd 3rd-partylist list`

Related to #1082

**Comment by castulo** [comment]
> Remove a repository:
> `$ swupd 3rd-party remove my_repo https://url`

why do you need to specify the URL to remove the repo?

**Comment by karthikprabhuvinod** [comment]
> > `$ swupd 3rd-party remove my_repo https://url`

I think  name should be enough : swupd 3rd-party remove my_repo

**Comment by karthikprabhuvinod** [comment]
https://github.com/clearlinux/swupd-client/pull/1185

**Comment by karthikprabhuvinod** [comment]
Closing as its been completed
