### ISSUE TITLE
Create a command to list all bundles from 3rd-party repositories

### ISSUE THREAD

**Issue by otaviobp** [clearlinux/swupd-client#1179]
Create a command `swupd 3rd-party bundle-list` that can list bundles from a 3rd party repository

The goal is to support all features from bundle-list that are supported in `swupd bundle-list`, but focus should be on:

`swupd 3rd-party bundle-list`: List all installed bundles grouped by repository
`swupd 3rd-party bundle-list --repo my_repo`: List all installed bundles from my_repo
`swupd 3rd-party bundle-list -all`: List all installed bundles grouped by repository
`swupd 3rd-party bundle-list --all --repo my_repo`: List all bundles from my_repo

Note that we should support installation of multiple bundles with the same name. If there's any name clash the repository name should be required.

Related #1082

Tasks:
- [x] Add support for `3rd-party bundle-list` to the `testlib`
- [x] Add functional tests for listing bundles from a 3rd-party repos
- [x] Add the `3rd-party bundle-list` command to swupd (without functionality)
- [x] Add the `--repo` flag to specify a 3rd-party repo
- [ ] Add documentation to man pages.
- [x] Add command to autocompletion script swupd.bash
- [x] Add command to autocompletion script swupd.zsh
- [x] Add command to the config file
- [x] Implementation of the `3rd-party bundle-list` functionality
- [x] Implementation of the `--repo` flag functionality
- [x] Check output correctness and consistency with other commands (including output using `--quiet`, `--verbose`, `--debug`)
- [ ] Update release notes draft

**Comment by castulo** [comment]
Tasks:
- [ ] Add support for `3rd-party bundle-list` to the `testlib`
- [ ] Add functional tests for listing bundles from a 3rd-party repos
- [ ] Add the `3rd-party bundle-list` command to swupd (without functionality)
- [ ] Add the `--repo` flag to specify a 3rd-party repo
- [ ] Add documentation to man pages.
- [ ] Add command to autocompletion scripts swupd.bash and swupd.zsh
- [ ] Add command to the config file
- [ ] Implementation of the `3rd-party bundle-list` functionality
- [ ] Implementation of the `--repo` flag functionality
- [ ] Check output correctness and consistency with other commands (including output using `--quiet`, `--verbose`, `--debug`)
- [ ] Update release notes draft
