### ISSUE TITLE
explicitly list /opt in default list of swupd repair --help

### ISSUE THREAD

**Issue by mrkz** [clearlinux/swupd-client#1205]
Thanks for correcting me and moving this to [clear-linux-documentation](https://github.com/clearlinux/clear-linux-documentation). 

@lebensterben @mrkz perhaps we should also specify that */opt* is also a user managed area in the stateless guide? 

Also, wouldn't it be important to update the output for "swupd repair --help"? See:
`Options:`
` -Y, --picky             Also remove files which should not exist`
`-w, --picky-whitelist=[RE] Directories that match the regex get skipped. Example: /var|/etc/machine-id Default: /usr/lib/modules|/usr/lib/kernel|/usr/local|/usr/src`

The default list shouldn't also list /etc/, /home, /var and /opt?

_Originally posted by @insilications in https://github.com/clearlinux/clear-linux-documentation/issues/913#issuecomment-553400107_

**Comment by ahkok** [comment]
stuff outside of `/usr` is user-managed, so, `/opt`/ by default falls under that. The exceptions are for paths under `/usr` ... So the docs should explain that. `swupd` doesn't do anything with `/run` for instance.

**Comment by otaviobp** [comment]
We need to improve the doc. Thanks for the report.
