### ISSUE TITLE
Can't update / bundle-add on a fresh install.

### ISSUE THREAD

**Issue by arnaudaprahamian** [clearlinux/swupd-client#1207]
**Describe the bug**
Just install Clear Linux and can't install anything in "Software" or with swupd.
Here is command line error :

> sudo swupd update --allow-insecure-http
Update started
Checking mirror status
Error: Failed to connect to update server: https://clearnas.ostc.intel.com/update/version/format29/latest
Possible solutions for this problem are:
	Check if your network connection is working
	Fix the system clock
	Run 'swupd info' to check if the urls are correct
	Check if the server SSL certificate is trusted by your system ('clrtrust generate' may help)
Warning: Upstream server https://cdn.download.clearlinux.org/update/ not responding, cannot determine upstream version
Warning: Unable to determine if the mirror is up to date
Error: Unable to determine the server version
Update failed
Software just give me this error : "Failled to connect to update server"

**To Reproduce**
Install Clear Linux, try to swupd update
No proxy, time synced with Internet, I can open the link with firefox.
Use Wifi and try with Ethernet too.

**Expected behavior**
Working installation

**Environment (please complete the following information):**
Distribution:      Clear Linux OS
Installed version: 31600
Version URL:       https://clearnas.ostc.intel.com/update
Content URL:       https://clearnas.ostc.intel.com/update

 - Platform: Fresh Dual Boot install (with fresh Windows 10 install) on Asus Vivobook S400C with Intel® Core™ i3-3217U

**Comment by otaviobp** [comment]
Hi,
There's a bug in 31600 that set the mirror incorrectly on install time. The good is that the fix is easy.
Can you run:

    sudo swupd mirror --unset
    sudo swupd update

**Comment by otaviobp** [comment]
I'm closing this issue because it doesn't look like a bug in swupd and problem was fixed in newer images. Please, reopen that if you have more issues.
