### ISSUE TITLE
3rd_party: Remove links to binaries exported by a 3rd party repository on bundle-remove

### ISSUE THREAD

**Issue by otaviobp** [clearlinux/swupd-client#1278]
Swupd should create links to binaries as stated on #1277
On bundle-remove these links should be removed.

**Comment by bryteise** [comment]
Content identified in the whitelist for a bundle should be removed. Bundle-remove should regenerate the shared 3rd-party directories (things in PATH and eventually others) as the last part of its operation (this means that even bundles that are not removed will need to have their shared wrapper scripts etc regenerated).
