### ISSUE TITLE
3rd-party: dangerous flags handling step1 - Don't install files with dangerous flags

### ISSUE THREAD

**Issue by otaviobp** [clearlinux/swupd-client#1281]
Some file flags are too permissive for a 3rd party repo, so they need shouldn't be installed unless whitelisted.

For this issue we should block installation of files the following dangerous flags:
 - setuid
 - set group id
 - sticky

**Comment by otaviobp** [comment]
@bryteise is there any other flag that we should block?

**Comment by bryteise** [comment]
Does swupd currently process extended attributes?

**Comment by castulo** [comment]
@otaviobp , @bryteise, So when swupd encounters binary files with `setuid` and/or `setgid` should it just skip installing that particular file and carry on with the installation of the other files in the bundle or should it block the installation of the whole bundle?

**Comment by castulo** [comment]
I'm thinking that as things are currently implemented with mixer and swupd there may not be a way of knowing the file permissions before downloading and extracting the file, so we would need to check for this flags either during staging or after the file has been installed, and then removing/uninstalling it if it has dangerous flags set.

**Comment by bryteise** [comment]
So the file must be extracted since the only way to know what attributes the file has is to inspect it. I would imagine staging would be the correct time to do so just like hash validation and aborting the add/update at that time for the bundle/repo.

**Comment by castulo** [comment]
> So the file must be extracted since the only way to know what attributes the file has is to inspect it. I would imagine staging would be the correct time to do so just like hash validation and aborting the add/update at that time for the bundle/repo.

yeah, I think that is the way to go
