### ISSUE TITLE
3rd-party: dangerous flags handling step2 - Only install files with dangerous flag when whitelisted

### ISSUE THREAD

**Issue by otaviobp** [clearlinux/swupd-client#1282]
Depends on #1281 
Only install files with dangerous flags when whitelisted. Description on how the whitelist should behave is still pending.

**Comment by castulo** [comment]
I'm wondering, wouldn't it be better to just require the use of a flag, for example `--force` to install a bundle that has files with dangerous flags instead of requiring a specific list of files to be used as whitelist? What do you guys think? @otaviobp @bryteise

**Comment by bryteise** [comment]
I'd prefer not to use force at all for this kind of thing, 3rd-party content is a different level of risk.

**Comment by castulo** [comment]
> I'd prefer not to use force at all for this kind of thing, 3rd-party content is a different level of risk.

ok, fair enough. But then how is the whitelist supposed to work? how is the user supposed to provide it? can you elaborate a little bit more about the high level functionality of this please?

**Comment by bryteise** [comment]
I'd like to support interactive usage to be able to have swupd print out a list of content that needs to be approved and why. Auto-update can skip repos that need approval (with a message logged as part of the motd update so users will know they need to do something). You could implement this to print out a message and have a flag for I agree that could be passed on the next run but that seems not as nice from a usage perspective. Regardless I think force has to many potential other interactions that I don't want to mix it in here.

**Comment by castulo** [comment]
> I'd like to support interactive usage to be able to have swupd print out a list of content that needs to be approved and why. Auto-update can skip repos that need approval (with a message logged as part of the motd update so users will know they need to do something). You could implement this to print out a message and have a flag for I agree that could be passed on the next run but that seems not as nice from a usage perspective. Regardless I think force has to many potential other interactions that I don't want to mix it in here.

Ok, so based on your feedback:
- I will print all the files with dangerous flags
- I will ask the user if they want to continue with the install, continue if they do, abort if they don't.

Thanks for the feedback.
