### ISSUE TITLE
Swupd clear doesn't remove swupd 3rd-party cache files

### ISSUE THREAD

**Issue by otaviobp** [clearlinux/swupd-client#1330]
**Describe the bug**
In a system that was used to install 3rd-part content cache files are left over forever at /var/lib/swupd/3rd-party/

**To Reproduce**
```
# swudp clear --all
0 files removed
0.00 Bytes freed
```

**Expected behavior**
Swupd clean should remove all state files. Swupd clean --all should also remove manifests.

**Comment by castulo** [comment]
I assume you meant `clean` not `clear` 😆, besides that, 3rd-party content has its own function to clean: `swupd 3rd-party clean`. If you just run `swupd clean --all` it is going to clean the cached content non related to 3rd-party.

**Comment by otaviobp** [comment]
Oh, I totally forgot about 3rd-party clean. If ```swupd 3rd-party update``` is running that, we can close this one.

**Comment by castulo** [comment]
> Oh, I totally forgot about 3rd-party clean. If `swupd 3rd-party update` is running that, we can close this one.

Let me double check that

**Comment by castulo** [comment]
`swupd 3rd-party update` in cleaning up the 3rd-part cache correctly. I'm closing this issue.
