### ISSUE TITLE
Save bundle tracking files in a path relative to path_prefix instead of statedir

### ISSUE THREAD

**Issue by otaviobp** [clearlinux/swupd-client#1332]
Right now we save the bundle tracking files in $statedir/bundles (/var/lib/swupd/bundles/). This is problematic if you are trying to reuse the same statedir for multiple clear linux chroots. The ideal is to install everything that can't be reused between multiple chroots in a path relative to path_prefix(--path parameter).
The suggestion is to move that from /var/lib/swupd/bundles to ${path_prefix}/var/lib/swupd_info/bundles. I'm open for suggestions on the swupd_info folder name

**Comment by castulo** [comment]
> The suggestion is to move that from /var/lib/swupd/bundles to ${path_prefix}/var/lib/swupd_info/bundles. I'm open for suggestions on the swupd_info folder name

Why not something within `${path_prefix}/var/lib/swupd` so we keep all swupd related data in the same directory?

**Comment by otaviobp** [comment]
We have changed the approach for this item, so I'm closing it.
