### ISSUE TITLE
3rd-party bundle-add should be allowed install state files

### ISSUE THREAD

**Issue by castulo** [clearlinux/swupd-client#1342]
When swupd is installing a bundle, it skips installing files considered to be state files, these include files in:
```
/data
/dev
/home
/lost+found
/proc
/root
/run
/sys
/tmp
/usr/src
/var
```

For swupd 3rd-party, a user should be able to install files in those directories.

**Comment by bryteise** [comment]
I'd expect there is very few cases it is actually important for 3rd party software to have data in most of those directories. I would be inclined to have blacklists be handled by mixer instead honestly and have distro checks for this kind of thing sneaking through. That said this is another layer of survival mechanism code but we should consider if it is still serving its purpose today as opposed to when it was originally added.

**Comment by bryteise** [comment]
That said, it probably is easier to make 3rd-party operations ignore blacklists than rework finer details of the release process.
