### ISSUE TITLE
staging: don't convert symlinks to hardlinks

### ISSUE THREAD

**Issue by otaviobp** [clearlinux/swupd-client#1353]
Reference: PR #1318

@castulo found a critical bug on  was found on commit be1deab9652f7729fd890c26ce9f797c8b9ddbd5 so it was reverted.

In some specific partitions the the AT_SYMLINK_FOLLOW flag is ignored, even when using kernet > 2.6.18 and the symlink was being referenced instead of copied. This caused swupd to assume several files in the disk were corrupted.

I couldn't find the root cause of the problem, but in my laptop I have 2 ext4 partitions and the problem occurs only in one of those. I opened another pull request with another proposed fix for the problem (#1352), but we still required further testing and test automation.

@andred Can you check if the new PR makes sense to you and if it works for your use case?

**Comment by otaviobp** [comment]
Closed by https://github.com/clearlinux/swupd-client/pull/1352

**Comment by andred** [comment]
Sorry for the late reply, but #1352 works for me, too.
