### ISSUE TITLE
[question] how to exclude bundle for update with swupd

### ISSUE THREAD

**Issue by ionutnechita** [clearlinux/swupd-client#1368]
Hi Clear Linux Team,

Is there any possibility to exclude a bundle for the update?
In other Linux distributions, there is this possibility.
Packages can be frozen.
It would be something like:
With YUM package manager > yum.conf

 exclude="kernel-lts2019"

that would be the kind of frost for that package.

this thing is possible?

**Comment by ahkok** [comment]
And not planned, either. This was a deliberate design choice made when we started ClearLinux.

**Comment by bryteise** [comment]
Well this kind of thing could be enabled as a possibility, similar to --force operations or repairing to an earlier version. Again it wouldn't be supported as ahkok noted but it could let users experiment (the os would be broken in subtle and not so subtle ways). I don't think we would likely spend much time ourselves on such a feature though.
