### ISSUE TITLE
swupd os-install: Error: Missing --bundle argument

### ISSUE THREAD

**Issue by mythi** [clearlinux/swupd-client#1369]
Our container builds have:

```
RUN mkdir /install_root \
    && swupd os-install \
    ${CLEAR_LINUX_VERSION} \
    --path /install_root \
    --statedir /swupd-state \
    --bundles=os-core \
    --no-boot-update \
    && rm -rf /install_root/var/lib/swupd/*
```

but is has started failing with an error: `Error: Missing --bundle argument`

There's no documentation about `--bundle`. 

However, if I change  to `--bundles=os-core,vi` (as shown by the help text), this starts working*. It looks `os-core` is somehow ignored/skipped and if the list becomes empty the error is given.

(* However, `vi` gives `Warning: Bundle "vi" is invalid or no longer available`)

**Comment by otaviobp** [comment]
This is a bug introduced on last release. I'm reproduced it here and I'll move it to swupd repository.
The problem is that os-core is always added on os-install, so it's filtered and we print a warning as if we didn't have any bundles in the parameter.
And `--bundle` should be `--bundles`. It's a typo

**Comment by otaviobp** [comment]
As a workaround for now, don't use the --bundles if you are only installing os-core. And if you are adding more than one bundle, this should work.
Also vi was rename to vim. We need to update that in the documentation.

**Comment by mythi** [comment]
> As a workaround for now, don't use the --bundles if you are only installing os-core

I'll wait for the fix because I don't want to rework the Dockerfiles after the fixes unless it's guaranteed that `swupd os-install` without `--bundles` defaults to `os-core` always.

**Comment by otaviobp** [comment]
It's guaranteed that os-install will always install os-core when no arguments are provided to --bundles and there are no plans on changing that.
But we are working in a fix that should be ready and released soon too, so it's up to you.

**Comment by mythi** [comment]
> It's guaranteed that os-install will always install os-core when no arguments are provided to --bundles

OK. I think that should be documented too and be visible to users who run `swupd os-install --help`.
