### ISSUE TITLE
os-install with bundle os-core failed.

### ISSUE THREAD

**Issue by qzheng527** [clearlinux/swupd-client#1377]
**Describe the bug**
Clear version: 32600
Do os-install by setting bundle "os-core" failed.
There is no error by setting bundle "os-core-update".
There is no such issue on version 32550.

This issue caused the clearlinux docker build failed.
Logs as below.
[https://github.com/clearlinux/dockerfiles/pull/387/checks?check_run_id=510207494](url)

**To Reproduce**
Steps to reproduce the behavior

Commands used :
1. source /usr/lib/os-release
2. mkdir /install_root
3. swupd os-install -V ${VERSION_ID} --path /install_root --statedir /swupd-state --bundles=os-core --no-boot-update

Error: Missing --bundle argument

Performs a system software installation in the specified location

Usage:
   swupd os-install [OPTION...] PATH

Global Options:
   -h, --help              Show help options
   -p, --path=[PATH]       Use [PATH] to set the top-level directory for the swupd-managed system
   -u, --url=[URL]         RFC-3986 encoded url for version string and content file downloads
   -P, --port=[port #]     Port number to connect to at the url for version string and content file downloads
   -c, --contenturl=[URL]  RFC-3986 encoded url for content file downloads
   -v, --versionurl=[URL]  RFC-3986 encoded url for version file downloads
   -F, --format=[staging,1,2,etc.]  the format suffix for version file downloads
   -S, --statedir=[PATH]   Specify alternate swupd state directory
   -C, --certpath=[PATH]   Specify alternate path to swupd certificates
   -W, --max-parallel-downloads=[n] Set the maximum number of parallel downloads
   -r, --max-retries=[n]   Maximum number of retries for download failures
   -d, --retry-delay=[n]   Initial delay in seconds between download retries, this will be doubled for each retry
   -n, --nosigcheck        Do not attempt to enforce certificate or signature checking
   -I, --ignore-time       Ignore system/certificate time when validating signature
   -t, --time              Show verbose time output for swupd operations
   -N, --no-scripts        Do not run the post-update scripts and boot update tool
   -b, --no-boot-update    Do not install boot files to the boot partition (containers)
   -j, --json-output       Print all output as a JSON stream
   -y, --yes               Assume yes as answer to all prompts and run non-interactively
   --allow-insecure-http   Allow updates over insecure connections
   --quiet                 Quiet output. Print only important information and errors
   --verbose               Enable verbosity for commands
   --debug                 Print extra information to help debugging problems
   --no-progress           Don't print progress report
   --wait-for-scripts      Wait for the post-update scripts to complete
   --assume=[yes|no]       Sets an automatic response to all prompts and run non-interactively

Options:
   -V, --version=[VER]         If the version to install is not the latest, it can be specified with this option
   -x, --force                 Attempt to proceed even if non-critical errors found
   -B, --bundles=[BUNDLES]     Include the specified BUNDLES in the OS installation. Example: --bundles=os-core,vi
   -s, --statedir-cache=[PATH] After checking for content in the statedir, check the statedir-cache before downloading it over the network
   --download                  Download all content, but do not actually install it
   --skip-optional             Do not install optional bundles (also-add flag in Manifests)

**Expected behavior**
No issue by using os-install with bundle os-core.

**Environment (please complete the following information):**
 - Clear Linux OS Version: [swupd info]
Before swupd update, version is 32550, no issue
After swupd update, version is 32600, os-install failed.

 - Platform: [hardware, docker, vm information ]
docker image : clearlinux:latest

**Comment by castulo** [comment]
This seems to be related to bug #1369 , it was fixed on swupd release 3.24.2 that will be available shortly. Thanks for reporting this issue.
I'm closing this issue since it seems to be the same we already fix, if you still see a problem once 3.24.2 is released please feel free to reopen.
