### ISSUE TITLE
3rd-party repo should not be added unless it has successfully gotten the certificate and user accepted, etc.

### ISSUE THREAD

**Issue by bktan8** [clearlinux/swupd-client#1384]
I tried to add a 3rd-party repo, but entered the wrong URL.  It hanged trying to reach the repo, so I killed the process.  But the repo was added nonetheless.  I think it should only be added once the repo has been verified.  

See below example:

clear@clr-mx~ $ sudo swupd 3rd-party add my-repo http://10.54.73.113 --allow-insecure-http
Warning: This is an insecure connection
The --allow-insecure-http flag was used, be aware that this poses a threat to the system

Adding 3rd-party repository my-repo...

^C|]
clear@clr-mx~ $ sudo swupd 3rd-party add my-repo http://10.54.74.113 --allow-insecure-http
Warning: This is an insecure connection
The --allow-insecure-http flag was used, be aware that this poses a threat to the system

Adding 3rd-party repository my-repo...

Error: The repository my-repo already exists

Failed to add repository
clear@clr-mx~ $ sudo swupd 3rd-party list
Swupd 3rd-party repositories:
 - my-repo: http://10.54.73.113

Total: 1

**Comment by castulo** [comment]
when a 3rd-party repo fails to be added for some reason, whatever steps swupd had completed adding the repo are rolled back, since the process was killed the rollback never happened.

**Comment by bktan8** [comment]
I get your point.  But can't we just not add the repo until they have accepted the certificate?

To add the 3rd-party repository you need to accept this certificate
Do you want to continue? (y/N):
