### ISSUE TITLE
Would like "bundle-info" to show required and optional bundle dependencies 

### ISSUE THREAD

**Issue by bktan8** [clearlinux/swupd-client#1399]
Before I install a bundle, I'd like to know what are the include()s and what are the also-add()s.
It would be great for "bundle-info" to display this information.

**Comment by otaviobp** [comment]
@castulo Do you know if this is supported by any other command?

**Comment by castulo** [comment]
we do show which bundles are included and which ones are also-add using bundle-info, but only if the bundle is already installed, for example:
```
$ sudo swupd bundle-info editors --dependencies
__________________________
 Info for bundle: editors
__________________________

Status: Explicitly installed

There is an update for bundle editors:
 - Installed bundle last updated in version: 32510
 - Latest available version: 32690

Bundle size:
 - Size of bundle: 931.26 KB
 - Size bundle takes on disk (includes dependencies): 445.80 MB

Direct dependencies (4):
 - os-core
 - emacs (optional, installed)
 - joe (optional, installed)
 - vim (optional, installed)

Indirect dependencies (6):
 - findutils (optional, installed)
 - lib-openssl (optional, installed)
 - libstdcpp (optional, installed)
 - p11-kit (optional, installed)
 - perl-basic (optional, installed)
 - python3-basic (optional, installed)
```

**Comment by bktan8** [comment]
Can we do it for uninstalled bundles so I can decide if I want to skip the optional bundles or not?

**Comment by castulo** [comment]
> Can we do it for uninstalled bundles so I can decide if I want to skip the optional bundles or not?

sounds good

**Comment by bktan8** [comment]
thx!

**Comment by bktan8** [comment]
@castulo - I doublechecked and it looks like "bundle-info" does show optional dependencies for not installed bundles.

Here's an example:

```
clear@controller~ $ sudo swupd bundle-info editors --dependencies

__________________________
 Info for bundle: editors
__________________________

Status: Not installed
Latest available version: 32690

Bundle size:
 - Size of bundle: 931.26 KB
 - Maximum amount of disk size the bundle will take if installed (includes dependencies): 355.63 MB

Direct dependencies (4):
 - os-core
 - emacs (optional)
 - joe (optional)
 - vim (optional)

Indirect dependencies (6):
 - findutils (optional)
 - lib-openssl (optional)
 - libstdcpp (optional)
 - p11-kit (optional)
 - perl-basic (optional)
 - python3-basic (optional)
```

**Comment by castulo** [comment]
Ahh, I did check that yesterday and tried showing info of a few bundles (`ansible`, `blender` and `mariadb`), but the bundles that I used  didn't show any information about also-adds, it never occurred to me that it was because they didn't have also-adds 🤣
I
'm glad we are already providing that information. Can we close this issue then?

**Comment by bktan8** [comment]
Yep.  Thanks!
