### ISSUE TITLE
3rd-party: add 3rd-party usr/share to XDG_DATA_DIRS

### ISSUE THREAD

**Issue by otaviobp** [clearlinux/swupd-client#1411]
On the 3rd-party exported wrapper we need to add the 3rd-party share directory (/opt/3rd-party/bundles/<reponame>/usr/share) to the XDG_DATA_DIRS env variable, like how we do with LD_LIBRARY_PATH.

**Comment by bryteise** [comment]
Also want XDG_CONF_DIRS (/opt/3rd-party/bundles/$name/etc) set similarly.
