### ISSUE TITLE
3rd-party: Regenerate binary wrapper on updates and swupd repair

### ISSUE THREAD

**Issue by otaviobp** [clearlinux/swupd-client#1413]
We need to have a way to regenerate the wrappers on swupd 3rd-party. First we need to regenerate all wrappers on any update where the binary is updated.
Regenerating on update won't apply any changes we made on swupd SCRIPT_TEMPLATE though. We need to have a way to force swupd to regenerate all wrappers.

 - [x] swupd update should regenerate the wrapper if binary has changed
 - [x] swupd repair should regenerate all wrappers of binaries that it is handling, even if binary is fine.
 - [ ] Wrappers are generated using the variable SCRIPT_TEMPLATE on src/3rd_party_repos.c. This variable can change every time swupd is updated and when this happens, we need to regenerate the wrappers.

**Comment by bryteise** [comment]
It is important that template changes don't require a user to manually repair in order to get updated scripts I think.

**Comment by otaviobp** [comment]
> It is important that template changes don't require a user to manually repair in order to get updated scripts I think.

I was unsure about that, but now that you say this it make total sense. I added that to the list.

**Comment by castulo** [comment]
> * On swupd update make sure to regenerate all wrappers if the template has changed. One idea on how to do it is to add a version number on wrappers scripts and check for changes on every update.

what about just looking at the updated files and if one of them is **`/usr/bin/swupd`** then we regenerate all wrapper scripts?

**Comment by castulo** [comment]
> what about just looking at the updated files and if one of them is **`/usr/bin/swupd`** then we regenerate all wrapper scripts?

Hmm but as a second thought if we just did that the template that we would use would still be the old one...

**Comment by castulo** [comment]
...unless during the update, if we see that `/use/bin/swupd` is being updated we can just issue a `swupd repair` once update finishes, similar to the way we run re_update when there is a format bump. That way repair will be run using the new swupd binary which has the new wrapper template. 

The only thing is that the user would see an update followed by a repair, but that should be ok IMO, we could even issue a message announcing that so the user doesn't get surprised, something like: "a swupd repair will be executed to update the exported binaries".

Thoughts @otaviobp ☝️

**Comment by bryteise** [comment]
Could make the template come from the filesystem that gets loaded when the templates are generated (so after the system would have been updated).

**Comment by otaviobp** [comment]
Right now there's no 3rd-party operation that is executed by any swupd command (other than the 3rd-party command). I don't think it's a problem to change that, but I would prefer to find a way to update the wrappers on swupd 3rd-party update instead of updating that on swupd update. For me it makes more sense, but I see that is a bit more complicated.
