### ISSUE TITLE
3rd-party: export .desktop files

### ISSUE THREAD

**Issue by gregor160300** [clearlinux/swupd-client#1420]
Currently, swupd 3rd-party only creates a wrapper for binary files such that they can be used (putting them in PATH). As most of the software people will install through 3rd-party will be (proprietary) desktop software it would be a better experience for the end-user if all .desktop files from /opt/3rd-pary/bundles/3rd-party-repo-name/usr/share/applications would end up in either the global /usr/share/applications folder (I think this violates the stateless design and thus would not be a good option) or in $HOME/.local/share/applications however, this would mean that the applications will only be available for one user (through the desktop interface).

Both options rely on the person creating the 3rd-party bundle to update the .desktop files with the correct path.

**Comment by gregor160300** [comment]
> Just copying to `~/.local/share/applications` doesn't works.

This is true when using unmodified .desktop files as they reference non-existing binaries, the .desktop file needs to be modified to adjust for the /opt/3rd-party/bin folder

**Comment by paulcarroty** [comment]
And `/opt/3rd-party/bundles/repoid/usr/share/icons/`. Or modify [graphical environment](https://wiki.archlinux.org/index.php/Environment_variables#Graphical_environment), but I can't do it properly on GNOME.

**Comment by paulcarroty** [comment]
After upgrade to swupd 3.24.5 3rd-party .desktop works in Gnome on X, but still hidden in Wayland session.
