### ISSUE TITLE
3rd-party: allow exporting the lib folder of a bundle

### ISSUE THREAD

**Issue by gregor160300** [clearlinux/swupd-client#1421]
I have been experimenting with building my own 3rd-party bundles and while most of the bundles work fine without having their lib folder in the LD_LIBRARY_PATH it can be useful to export the libraries to the LD_LIBRARY_PATH. A good example for this need is having a build of ffmpeg installed as a 3rd-party bundle when the lib folder of this ffmpeg build is not available in the LD_LIBRARY_PATH applications like vlc (and likely others as well) can't make proper use of the added codecs.

**Comment by otaviobp** [comment]
Thank you for the feedback. So far, as you noticed, we only support exporting binaries, but exporting libraries and .desktop files is going to be supported in the future.

**Comment by bryteise** [comment]
@gregor160300 A work around for this is to have whatever applications are requiring the 3rd-party libraries in the same mix repo.

**Comment by gregor160300** [comment]
Great to hear that you are planning on supporting more export options. I did consider building vlc within the same mix however I found that it was easier to just run LD_LIBRARY_PATH=/opt/3rd-party/bundles/<repo-name>/usr/lib vlc from the terminal, as for firefox it has it's own quirks. I do think there might be some issues with ldconfig due to the stateless design, for some reason programs like firefox and vlc seem unable to pick up on the libraries loaded by ldconfig see also [here](https://community.clearlinux.org/t/how-to-h264-etc-support-for-firefox-including-ffmpeg-install/195)

**Comment by bryteise** [comment]
@gregor160300 Do you mean that:

```
sudo sh -c 'echo /usr/local/lib >>/etc/ld.so.conf'
sudo ldconfig
```

isn't enough for firefox (and apparently vlc) to use the library path correctly? I think this was a firefox bug looking at [this](https://bugzilla.mozilla.org/show_bug.cgi?id=1565996).

**Comment by gregor160300** [comment]
> @gregor160300 Do you mean that:
> 
> ```
> sudo sh -c 'echo /usr/local/lib >>/etc/ld.so.conf'
> sudo ldconfig
> ```
> 
> isn't enough for firefox (and apparently vlc) to use the library path correctly? I think this was a firefox bug looking at [this](https://bugzilla.mozilla.org/show_bug.cgi?id=1565996).

Indeed this isn't enough for both vlc and firefox I will read through the bugreport on bugzilla to find a proper workaround as it seems firefox didn't fix it yet. Meanwhile, I am setting up a VM to check whether or not adding the export of LD_LIBRARY_PATH in /etc/environment fixes the codec loading in at least vlc
