### ISSUE TITLE
Testlib: generate_test is not finding the next available ID anymore 

### ISSUE THREAD

**Issue by castulo** [clearlinux/swupd-client#1485]
The test generator `generate_test` that can be used to create a new test based on the template uses the `get_next_available_id` function to autogenerate the test Id for the test. This function is currently broken because testlib expects to have all tests from one group in the same directory. For example all "ADD" tests are expected to be in the `test/functional/bundleadd/` directory, and  we decided to move some of these tests into `test/functional\only_in_ci_system\`.

There may be another functions that may malfunction because of this, like: `list_tests`, 'get_next_available_id' and 'generate_test'. If we are planning on being able to shuffle tests from one ID group into multiple directories we need to make changes to support that.

**Comment by otaviobp** [comment]
I don't like the idea on assuming ID by the path. Instead of trying to get the next ID for a path I would try to get the next ID for a prefix.
