### ISSUE TITLE
Save all extracted files (staged files) in a path dependent on the URL

### ISSUE THREAD

**Issue by otaviobp** [clearlinux/swupd-client#1540]
Everything you download should be saved in a path like ${STATEDIR}/staged/${url}/
For example, we could have the following file in the system:
 - /var/lib/swupd/staged/http_cdn.download.clearlinux.org_update/aa726606daecf7b9f0af03903cd4c6180b50323f305fb30b0f9425f053c62aa1

**Comment by castulo** [comment]
With the changes proposed in #1577, all fulllfiles will be extracted to `<STATE_DIR>/cache/<https_cdn.download.clearlinux.org_update>/staged, so I think that covers it.
