### ISSUE TITLE
global options: `versionurl` and `contenturl` doesn't need `root` privillege to set

### ISSUE THREAD

**Issue by lebensterben** [clearlinux/swupd-client#1545]
To reproduce:
```
❯ swupd autoupdate --contenturl=http://github.com/
Enabled
❯ swupd autoupdate --versionurl=http://github.com/
Enabled
```

**Comment by otaviobp** [comment]
--contenturl and --versionurl flags are just affecting one execution of swupd. So you are not setting that for the autoupdate in this command.
`Swupd autoupdate` will just check the status of the autoupdate. To enable or disable it you need to run `swupd autoupdate --enable/--disable`, that requires root. Adding --versionurl/--contenturl in this command won't affect how swupd does the update. To change the mirror you are using you need to use `swupd mirror` command.

**Comment by lebensterben** [comment]
>--contenturl and --versionurl flags are just affecting one execution of swupd. So you are not setting that for the autoupdate in this command. ...

@otaviobp Thanks for the explanation, I will close this now.
