### ISSUE TITLE
Clear container update failure at /opt/3rd-party/script.template

### ISSUE THREAD

**Issue by raggi** [clearlinux/swupd-client#1566]
I provisioned a container filesystem for nspawn using:

`swupd os-install -p /var/lib/machines/somemachine -N -b -B os-core`

I ended up either from that, or from a subsequent bundle addition with an apparent dependency on `/opt/3rd-party/script.template`, and then swupd would not complete, with:

```
May 12 01:16:09 somemachine swupd[1038]: The scripts that export binaries from 3rd-party repositories need to be regenerated
May 12 01:16:09 somemachine swupd[1038]: Error: The wrapper scripts template file /opt/3rd-party/script.template failed to be updated
```

I created /opt/3rd-party and it now succeeds.

I believe this process shouldn't depend on /opt/3rd-party being present, but I don't know if there was another error in my steps along the way.

**Comment by otaviobp** [comment]
I could reproduce this problem when running any 3rd-party command or `swupd update --3rd-party`, so this is a bug.
This line is printed by the function that updates the 3rd-party repositories. I couldn't find any case where this function is called by any command that is not a 3rd-party command. If you can reproduce this problem again, can you send us the exact command you run that caused this problem?

**Comment by castulo** [comment]
> I could reproduce this problem when running any 3rd-party command or `swupd update --3rd-party`, so this is a bug.

Can you show the steps you followed to reproduce @otaviobp

**Comment by otaviobp** [comment]
Run `swupd update --3rd-party` or `swupd 3rd-party update` on a system without the directory `/opt/3rd-party`

**Comment by castulo** [comment]
ahhh I see, I could reproduce it like that, thanks
