### ISSUE TITLE
increase curl timeout when installing large bundles

### ISSUE THREAD

**Issue by nobodyatandnothing** [clearlinux/swupd-client#1597]

**Comment by nobodyatandnothing** [comment]
> Transferring to the swupd-client repo... I assume that `apa` is a wrapper around swupd, not a fork of swupd?

its just in alias

**Comment by phmccarty** [comment]
> > Transferring to the swupd-client repo... I assume that `apa` is a wrapper around swupd, not a fork of swupd?
> 
> its just in alias

Great, thanks for confirming :-)

**Comment by nobodyatandnothing** [comment]
maybe large bundles could be heavily compressed (xz) ? it would take less time to extract than to download and far less expensive.

**Comment by Nutr1t07** [comment]
and how was that get solved?
