### ISSUE TITLE
why no ipv6 support?

### ISSUE THREAD

**Issue by ctc** [clearlinux/swupd-client#200]
Why is curl "hardcoded" to resolve all urls to ipv4?

curl.c
#warning "setup a means to validate IPv6 works end to end"
        curl_ret = curl_easy_setopt(curl, CURLOPT_IPRESOLVE, CURL_IPRESOLVE_V4);

**Comment by tmarcu** [comment]
This is an artifact of the original code base, and should be updated to support both.

**Comment by sofar** [comment]
The whole line should just be removed to enable both by default.

https://github.com/clearlinux/swupd-client/blob/master/src/curl.c#L509

I can actually likely do this, as I have a host on native ipv6.

It appears that ipv6 already is fully functional as well already:

```
$ curl -I -6 https://download.clearlinux.org/
HTTP/1.1 200 OK
Date: Sat, 06 May 2017 06:50:45 GMT
Server: Apache
...
$ curl -I -6 https://cdn.download.clearlinux.org/
HTTP/1.1 200 OK
Server: Apache
...

**Comment by ctc** [comment]
works very well with IPv6 - if it's allowed to use IPv6
