### ISSUE TITLE
review --url x --versionurl

### ISSUE THREAD

**Issue by barbieri** [clearlinux/swupd-client#21]
Please ensure `--versionurl` is available for all commands that needs `version_server_urls`. Currently we have few inconsistencies:

 * `check-update` uses `--url` while it should be called `--versionurl`.
 * `bundle-add`, `bundle-rm` and `search` all miss `--versionurl`, only calculating it from `--url`.

The idea is that we can use different version URL to fix versions, like "qa-approved" and "milestones". They would be different numbers (tags) to the same update stream.

**Comment by phmccarty** [comment]
I added the missing options in my pull request, clearlinux/swupd-client#22
