### ISSUE TITLE
Add alias to bundle-add and bundle-remove

### ISSUE THREAD

**Issue by gorozco1** [clearlinux/swupd-client#217]
As a linux user the "common mindset is to use install" when it comes to install a new component in a system:

Example:

```
# dnf install <foo>
# apt-get install <foo>
# apt install <foo>
# rpm --install <foo>
# dpkg --install <foo>
```

So as a way to lower the adotpion curve for any new user would be very handy to have aliases for **bundle-add** and **bundle-remove** so the following can work:

- Add a new bundle
`swupd install sysadmin-hostmgmt `

- Remove a bundle
`swupd remove sysadmin-hostmgmt `

**Comment by tmarcu** [comment]
I can agree with this for adoption. I would rather not have aliases though, and instead just change the actual core names to "install" and "remove" <bundle>, and get rid of bundle-OPTION.

**Comment by bryteise** [comment]
@tmarcu You'd be breaking any number of users with scripting around bundle-OPTION subcommands. Probably best to make them deprecated and print warnings about them go away and then after some time (a few months at least) bump swupd-client major version and remove the commands.

**Comment by phmccarty** [comment]
One other thing to note is that `verify --install` still exists. Maybe we could deprecate this `--install` option and making sure `install` (currently `bundle-add`) supports the existing usage model for `verify --install`?

**Comment by bryteise** [comment]
@phmccarty That'd be quite nice though involve a bit of a refactor I imagine.

**Comment by matthewrsj** [comment]
#250 will track `install` as a top-level command. I think an easier solution would be to call the aliases `add` and `remove` instead of `install` and `remove` so we don't have to handle an OS install and a bundle install with the same command. Or just name the os install option `os-install`.

**Comment by matthewrsj** [comment]
Closing in favor of #250, other suggestions need to be coordinated as part of a larger CLI rework.
