### ISSUE TITLE
provide a comand to show files into the bundle, installed and available

### ISSUE THREAD

**Issue by rlins10** [clearlinux/swupd-client#221]
It would be nice to nice to have  "--listfile" options to show files inside a bundle that is installed and ones that are available but not installed.

(Jonh)

**Comment by matthewrsj** [comment]
This idea for installed bundles would basically be a cat of a manifest that should already exist in the statedir.

This idea for available bundles is basically what swupd search is for. I don't see the use case for someone wanting to see the entire file list for a bundle without having an idea of what they are looking for.

These file lists are almost always verrrry long. It doesn't make sense to me for swupd to be outputting this in the console. Open the manifest file in your state directory in an editor or visit https://download.clearlinux.org (or whatever upstream) and view it there.

**Comment by xinyunliu** [comment]
Why this feature removed? Does clearlinux provide a method to list files in a bundle?
