### ISSUE TITLE
versionstamp never created

### ISSUE THREAD

**Issue by aaronovz1** [clearlinux/swupd-client#234]
This file might be created outside the scope of swud-client but in a Yocto/meta-swupd environment I don't see any where that creates the /usr/share/clear/versionstamp file if it doesn't exist. Shouldn't verifytime create this if the file is missing or invalid (it seems to update it if the file exists and has a timestamp).

**Comment by mkhansen-intel** [comment]
I am getting this error when running a swupd update: 
```
root@clr-201cff6f98494b319cf2c48bfbc38c66 ~ # swupd update
swupd-client software update 3.10.0
   Copyright (C) 2012-2016 Intel Corporation

/usr/share/clear/versionstamp does not exist!
Updater failed to initialize, exiting now.
root@clr-201cff6f98494b319cf2c48bfbc38c66 ~ #
```
I think this may be the same problem you're seeing... what is supposed to create that file?

**Comment by aaronovz1** [comment]
Yep that is the same problem I am seeing. You can workaround it by creating the file like so:
```
echo `date +%s` > /usr/share/clear/versionstamp
```

I am not sure what is meant to create it. I couldn't find any reference in the code that does it. I ended up adding an extra step during our system imaging scripts which creates it for now.

**Comment by matthewrsj** [comment]
Yes this is interesting. `/usr/share/clear/versionstamp` is included in the os-core bundle, which is part of the base install on any clear OS. Since this file exists in the installer image swupd will successfully `verify --install` the file on the new target image.

There should probably be a check to create the file if it does not exist, instead of failing out. @tmarcu @phmccarty was there a particular reason this file is not created? It seems like it should be created similarly to the way /var/lib/swupd is with the recent commit from @icarus-sparry.

**Comment by phmccarty** [comment]
It's created by bundle-chroot-builder when creating Clear mixes.

**Comment by mkhansen-intel** [comment]
In the mixer how-to page (https://clearlinux.org/documentation/clear-linux/how-to/mixer.html) it says to install bundle-chroot-builder using swupd, which is how I hit this error in the first place. I think you may have a circular dependency?

**Comment by mkhansen-intel** [comment]
Sorry not a circular dependency. However the swupd command fails.

**Comment by phmccarty** [comment]
@mkhansen-intel Are you running swupd on Clear Linux? I ask because the Clear Linux team validates to check that this file (among others) exist in every Clear Linux build, and I've never seen this validation fail.

**Comment by mkhansen-intel** [comment]
Yes, but I build the image myself...not sure what I've done wrong?

**Comment by tmarcu** [comment]
Are you building your update/images with the current release of swupd-server? Or a meta-forked swupd-server? The versionstamp file is generated automatically for os-core, which is always required to be built & installed. The only way for this file to not exist is either chroots weren't created, or the build you updated to was empty or wrongly created and deleted the file, IMHO. 
Verifytime is a last-resort backup if the system is terribly misconfigured and doesn't match the cert validity range, it's not responsible for this file.

**Comment by aaronovz1** [comment]
I am using the meta-swupd layer for Yocto with the latest version of swupd-server and swupd-client. I don't see where in any of the code that file gets created.

________________________________

**Comment by mdhorn** [comment]
I was just trying to use the docker image of clearlinux and ran into this exact same issue.

```
# swupd verify
swupd-client software verify 3.10.0
   Copyright (C) 2012-2016 Intel Corporation

/usr/share/clear/versionstamp does not exist!
Failed verify initialization, exiting now.
```

```
# swupd check-update
swupd-client software update checker 3.10.0
   Copyright (C) 2012-2016 Intel Corporation

Attempting to download version string to memory
Current OS version: 1
There is a new OS version available: 17560
```

**Comment by phmccarty** [comment]
@mdhorn Which Clear Linux Docker image did you use?

The output you have posted from both of those commands is unexpected, at least with the image on Dockerhub (https://hub.docker.com/_/clearlinux/); the`swupd verify --install` command is used to create that image, which installs the os-core and os-core-update bundles. In particular, the os-core bundle ships with both `/usr/share/clear/versionstamp` and a refreshed `/usr/lib/os-release` containing the correct current version.

**Comment by phmccarty** [comment]
So, for those seeing a missing `/usr/share/clear/versionstamp` file, it's not clear to me how to reproduce the issue. Can someone post steps to reproduce (also environment information, etc)?

From the swupd-client side, I think `verifytime` should ignore the condition where `/usr/share/clear/versionstamp` is missing. I'll open a separate issue for that.

**Comment by aaronovz1** [comment]
I can't comment on the issue seen under Clear as I am in a meta-swupd/Yocto environment. @matthewrsj. you say the versionstamp file is part os-core, I assume there is a build step in Clear which adds that. I think the same kind of build step needs to be added to meta-swupd to resolve the issue that I see. @pohly what do you think?

**Comment by matthewrsj** [comment]
@aaronovz1 #289 has also been opened as an issue here.

**Comment by phmccarty** [comment]
@aaronovz1 For Clear Linux builds, the code that creates the file lives in bundle-chroot-builder ([direct link](https://github.com/clearlinux/bundle-chroot-builder/blob/798b4e8906355ac3c61ce57dd16707f743d985a4/bundle-chroot-builder.py#L281)).

**Comment by pohly** [comment]
@aaronovz1 I've started updating meta-swupd in https://github.com/pohly/meta-swupd/commits/master. Creating /usr/share/clear/versionstamp" was part of the my update to swupd-client 3.12.0 (https://github.com/pohly/meta-swupd/commit/958c6f68d1ea1ee1beda5e20dcb76a5b09b6744e).

I don't know yet how we'll proceed with meta-swupd itself. Eventually these local changes should get pushed back to it.

**Comment by aaronovz1** [comment]
@pohly Thanks! I wasn't aware of your more updated repo. The A/B partitioning enhancement is really interesting.

**Comment by phmccarty** [comment]
Is this issue resolved now that @pohly pushed the meta-swupd change?

**Comment by aaronovz1** [comment]
Sorry, yes this looks like it's resolved for me.

**Comment by phmccarty** [comment]
Okay, thanks.
