### ISSUE TITLE
Add -m flag for swupd update

### ISSUE THREAD

**Issue by matthewrsj** [clearlinux/swupd-client#257]
Add flag to allow user to update to a particular version as long as that version is > the current version. Context surrounding this feature can be found in #249

**Comment by pohly** [comment]
When -m is given, the version URL parameter is not necessary and if given, must not be used.

**Comment by matthewrsj** [comment]
Good point, I agree that it should not be supported to switch between content streams like that, since update doesn't check all the files on the filesystem. swupd-client should print a warning that the versionurl parameter is being ignored.

**Comment by bryteise** [comment]
@pohly The version URL is needed because -m could give "latest" which needs to be validated against the version URL.

**Comment by bryteise** [comment]
Oh nevermind I see what you are saying =P.

**Comment by bryteise** [comment]
I'm still a little unsure about saying it should not be used though. In the case where somebody sets up a mirror, an alternate version and version url would be acceptable as they should be stopped from going to a different content stream due to the content being signed.

**Comment by pohly** [comment]
Let's take an example:

```
swupd update -m 200 -c http://example.org/swupd-content -v http://example.org/swupd-versions
```

Why would it need to access example.org/swupd-versions? What additional checks depend on data found there?

My expectation is that "swupd update" will only need information from example.org/swupd-content/200/ and example.org/swupd-content/<current version>.

**Comment by bryteise** [comment]
In this case if you give
`swupd update -m latest` you'd want to give the version url as it needs to look up what the latest version is on the mirror.

**Comment by matthewrsj** [comment]
Maybe `-m latest` can be treated differently? Or not allowed at all? It is default behavior to update to latest, so that flag would essentially be ignored anyways would it not?

**Comment by pohly** [comment]
My expectation was that -m would always take an integer version number.

If someone wants "-m latest", they should simply not use "-m".

**Comment by bryteise** [comment]
Yes, you can remove latest handling in update and that would resolve my worry.

**Comment by pohly** [comment]
Exactly :-) "-m 100" is meant to override the "update to latest" behavior.

**Comment by bryteise** [comment]
I always like being able to specify the default behavior with options as well but it isn't a requirement and makes this case harder so the latest handling can be dropped here for sure.

**Comment by cmarcelo** [comment]
> When -m is given, the version URL parameter is not necessary and if given, must not be used.

It is still needed if the update to a version in another format. Could be avoided if update is between same format.
