### ISSUE TITLE
Implement better functional test creation workflow

### ISSUE THREAD

**Issue by phmccarty** [clearlinux/swupd-client#258]
Currently, in order to write a new functional test, the BKM is to copy an existing functional test *similar* to the new one you want to write, and modify it accordingly. Pain points include several manual steps: (a) calculating swupd hashes of files, (b) updating the manifests according to the test's needs, and (c) calculating the swupd hash of each bundle manifest to include in the Manifest.MoM as a final step.

A workflow should be implemented to facilitate automating test creation, in particular the three items listed above.

**Comment by matthewrsj** [comment]
Closed by @castulo in several PRs. The only remaining work is porting the actual tests, which is not part of this issue (and as I understand it is pretty much done anyways).
