### ISSUE TITLE
"swupd verify --install -m" should not need version URL

### ISSUE THREAD

**Issue by pohly** [clearlinux/swupd-client#277]
Command (custom distro and update stream, swupd client 3.12.0):
```
swupd verify --install -F 4 -c http://localhost:8000 -v http://localhost:8000 -m 20 -S /tmp/statedir -p /tmp/rootfs
```

First, -v is required, swupd refuses to proceed without it.
Second, it downloads /version/format4/latest.

Not sure what it does with the information. Is it needed?

IMHO a clean install with an explicit version should work without a version URL and without information about the latest version.

**Comment by phmccarty** [comment]
> First, -v is required, swupd refuses to proceed without it.

swupd-client has a configure option `--with-versionurl` to set a hardcoded versionurl in the binary. It also reads a configuration file at `/usr/share/defaults/swupd/versionurl` for a default versionurl. And it also supports the `-v` command line option. The command line value has highest priority, followed by the config file, followed by the builtin value.

As a result, it's possible for swupd-client emit an error if (a) no hardcoded versionurl is set in the binary and (b) no config file exists. I suspect this is why you see an error.

> Second, it downloads /version/format4/latest.

The network detection code checks for a valid network connection by downloading the formatN/latest file. This could be improved in the future, but swupd-client has been doing this for a long time.

**Comment by phmccarty** [comment]
Also, a side note about the special treatment of `-m latest`. The `latest` value means to use the value from formatN/latest. This is just for reference, since you are not using `-m latest`.

**Comment by pohly** [comment]
On Mon, 2017-10-16 at 22:48 +0000, Patrick McCarty wrote:
> The network detection code checks for a valid network connection by
> downloading the formatN/latest file. This could be improved in the
> future, but swupd-client has been doing this for a long time.

When used in "push mode" without a version URL, the network detection
code should fall back to checking the content URL based on the given
version.

Shall I file another issue for that or should we have a general
"support push mode without version URL" feature request?
