### ISSUE TITLE
Question: staging size and growth each update

### ISSUE THREAD

**Issue by aaronovz1** [clearlinux/swupd-client#278]
Does the client store much data after an update is finished? I am worried about the potential for a system to eventually run out of disk space if it stores staged/meta data each update. Can someone give a general overview of the process that occurs on a client and measures that can be done to avoid this?

**Comment by matthewrsj** [comment]
All downloaded data is stored in the state directory (`/var/lib/swupd` on Clear). On Clear Linux this is stored for 4 days as defined in `/usr/lib/tempfiles.d/swupd-client.conf`. This could easily be done in another environment and the time period could be made much shorter.

**Comment by matthewrsj** [comment]
@aaronovz1 does that answer your question? Can this be closed?

**Comment by aaronovz1** [comment]
What does swupd-client.conf file look like?

**Comment by icarus-sparry** [comment]
$ cat /usr/lib/tmpfiles.d/swupd-client.conf
d /var/lib/swupd 0700 root root 4d -

[tmpfiles.d](https://www.freedesktop.org/software/systemd/man/tmpfiles.d.html) is the manual page for this, which is part of systemd. Other distributions may have other ways of cleaning up files periodically.

**Comment by aaronovz1** [comment]
Thanks. I don't use Clear or have it available so was just curious what its contents were. I'll check the manpages for more information.

Last question - is there any information under /var/lib/swupd that could be retained as to reduce re-downloading the files? On systems with GSM connections we would want to avoid extra bandwidth costs.

**Comment by matthewrsj** [comment]
For the most part if the file exists in /var/lib/swupd the client will not attempt to re-download, it will just assume it is the right file and verify the hash in the staging phase. If the hash verification fails the operation will fail, which is a bug reported in #325, and should be fixed soon.

**Comment by aaronovz1** [comment]
What I meant is what files are temporary and not required in future updates and can be safely deleted, and what files would be re-downloaded because they are required for all or future updates. Just trying to minimize disk use but also GSM bandwidth.

**Comment by icarus-sparry** [comment]
The files in "staged" can be used to reduce downloads, as we use bsdiff and bspatch to potentially ship just the changes in the binaries, rather than the full binaries when we upgrade. This is a tradeoff, increased disk space vs reduced bandwidth. 

Normally the delta, download and telemetry directories will be empty unless swupd is currently running.

**Comment by matthewrsj** [comment]
that is kind-of hit or miss. You're largest hit by far will be the full-files that get put in the staged/ directory. On my local system staged/ accounts for 7.3G (yikes!) of the 7.7G in my state directory.

On a new update swupd will not download any file that already exists in the staged/ directory, so having those hang around can reduce your bandwidth/

Without knowing what an update will look like before it happens I'm not sure how you could trim this down.

Anyone else have thoughts on this?

**Comment by matthewrsj** [comment]
With the current implementation you would probably need to play with how long you want to keep /var/lib/swupd files around by messing with swupd-client.conf.

**Comment by matthewrsj** [comment]
Also, don't be too alarmed by my statedir size. I have very many bundles installed.

**Comment by aaronovz1** [comment]
Ok. I think I have enough information to close this. I will have to experiment and see what a good clean up interval would be.
