### ISSUE TITLE
use libarchive directly

### ISSUE THREAD

**Issue by pohly** [clearlinux/swupd-client#285]
This is related to https://github.com/clearlinux/swupd-server/pull/48. Once the server uses libarchive, the client should also use bsdtar, which is already possible.

But calling libarchive directly would have several advantages:
- when unpacking Manifest files, restoring file attributes can be skipped, thus avoiding a problem with "ioctl(4, FS_IOC_GETFLAGS, 0x7ffe5c46d874) = -1 ENOTTY (Inappropriate ioctl for device)" when the statedir is on a tmpfs
- tar archives can be unpacked directly, without storing the entire file on disk first (GNUtar needs to seek in the file to detect compression methods, libarchive doesn't)
- file name or link name encoding errors in a locale which does not support UTF-8 can be ignored because the fallback is to skip re-encoding, which is exactly what swupd needs (would solve https://github.com/clearlinux/swupd-client/issues/280)

Right now, https://github.com/clearlinux/swupd-client/issues/249 is implemented with statedir on the target partition (because of https://github.com/clearlinux/swupd-client/issues/273), but then the target partition must have at least enough space for "unpacked rootfs + pack-os-core-from-0.tar".

**Comment by pohly** [comment]
The goal is to do "swupd verify --install -p /mnt/some-partition" and directly stream the OS content onto the target partition.

Right now we put the state directory onto the target partition (partly because of issue #273, partly because unpacking Manifests into /tmp fails due to the ioctl() problem), but that means that additional space is needed on the OS partition.

**Comment by matthewrsj** [comment]
Fixed by #327
