### ISSUE TITLE
add --no-scripts option to update and verify

### ISSUE THREAD

**Issue by pohly** [clearlinux/swupd-client#286]
Part of https://github.com/clearlinux/swupd-client/issues/249, originally discussed there.

Depending on whether swupd-client is invoked for the currently active filesystem or some inactive one, post-update actions vary. What's currently hard-coded into swupd-client (/usr/bin/systemctl daemon-reexec/reload, /usr/bin/systemctl restart update-triggers.target) is not applicable when updating the inactive partition. Same for run_preupdate_scripts (runs /usr/bin/clr_pre_update.sh).

Given that the current proposal is to use a combination of various swupd operations to achieve the final filesystem update, the helper script needs its own post-update hook mechanism instead of relying on systemd.

What about adding a "--no-scripts" option to "swupd update" and "swupd verify" which suppresses running these additional external helpers?

**Comment by pohly** [comment]
Example of what happens at the moment:
```
swupd verify --install -F 4 -c http://localhost:8000 -v http://localhost:8000 -m 10 -S /tmp/tmp.tASazq/swupd-state -p /tmp/tmp.tASazq
swupd-client software verify 3.12.0
   Copyright (C) 2012-2017 Intel Corporation

Verifying version 10
Attempting to download version string to memory
Range command not supported by server, download resume disabled.
Downloading packs...

Extracting os-core pack for version 10
	...100%
Adding any missing files
	...100%
Inspected 10909 files
  10909 files were missing
    10909 of 10909 missing files were replaced
    0 of 10909 missing files were not replaced
Calling post-update helper scripts.
sh: /tmp/tmp.tASazq//usr/bin/clr-boot-manager: not found
Fix successful
```

The failure during post-update seems to be ignored, so at least the command does not fail overall.

**Comment by matthewrsj** [comment]
The `--no-boot-update` argument already exists in v3.12.2. Does this do what you are wanting?

**Comment by pohly** [comment]
When --no-boot-update is used, does swupd still run update_triggers() in scripts.c and thus "systemctl daemon-reload/reexec" followed by "/usr/bin/systemctl restart update-triggers.target"? That part also needs to be disabled.

**Comment by matthewrsj** [comment]
It does still run the update_triggers.

I'm thinking when doing an update to another partition there should be a flag that indicates that, maybe `--partition <part/path>` which will skip `update_triggers()` and set the staging dir to some default on the target partition (with override allowed). Other than that `--partition` would behave the same way `--path` does.

This way it won't be necessary to run the update with a bunch of magic flags to make the update work.

**Comment by pohly** [comment]
To me this "--partition" parameter sounds too complex. But that's just my 2 cents. If you want to go that way, it would also work.

**Comment by matthewrsj** [comment]
I'm in favor of adding a --no-scripts flag to skip the post-update scripts entirely. This will help the container use case as well (as it exists they always see warnings about not being able to run the scripts).
