### ISSUE TITLE
return code: distinguish between permanent and temporary failures

### ISSUE THREAD

**Issue by pohly** [clearlinux/swupd-client#292]
The script implementing issue #249 currently uses the following logic:
- "swupd update + swupd verify --fix"
- if that fails, fall back to "mkfs + swupd verify --install", i.e. reinstall from scratch

The rationale is that "swupd verify --install" into a freshly formatted partition is something that can be tested and thus guaranteed to work, whereas incremental updates may fail due to various, unforeseeable factors (filesystem corruption, out-of-disk-space errors).

However, with this approach and swupd as it is now, transient errors like loss of network connectivity cause the script to wipe out current content. instead it should give up early.

Please consider adding two kinds of return codes to swupd-client:
- 1 for permanent errors that require intervention by a local admin
- 2 for transient errors that might go away when trying again later (usually network errors)

**Comment by matthewrsj** [comment]
swupd has several different error codes depending on what error was encountered, detailed here: https://github.com/clearlinux/swupd-client/blob/master/include/swupd-error.h

For example, `ENOSWUPDSERVER` is return code 16, which indicates there was no network connection to the swupd server.

**Comment by matthewrsj** [comment]
Yes, swupd can return `ENOSWUPDSERVER`.

I'll open another issue to improve return code documentation.

**Comment by matthewrsj** [comment]
Closed in favor of #296
