### ISSUE TITLE
swupd verify --fix --extra-picky

### ISSUE THREAD

**Issue by pohly** [clearlinux/swupd-client#293]
The script implementing issue #249 uses "swupd verify --fix --picky -p some_partition_mount" to remove extra content from the partition. However, the description of "--picky" only talks about it having an effect for files under /usr.

What about files elsewhere, like /lib, /etc or even something else entirely under /? Will they get removed if not part of the OS build?

FWIW, we configure swupd-client with --disable-stateless, which means that it manages /etc.

Perhaps a --extra-picky option is needed? If so, then we also need an exception list, because currently /swupd-state on the target partition is used as statedir, which needs to be ignored by swupd (either because it gets specified explicitly or implicitly).

One other, potentially related issue is recording the content URL that was used to populate the current partition content. Comparing version numbers only makes sense if the content URL is the same. Therefore the script stores the content URL in /usr/share/defaults/swupd/contenturl, which is not part of the OS. This currently leads to "swupd verify --fix" removing the file, followed by the script re-creating it.

The script could use some other location (/.contenturl ?), but if "swupd verify --fix" manages the entire file tree, then that file also would get removed unless we have a way to whitelist it.

**Comment by matthewrsj** [comment]
This functionality was added in #337
