### ISSUE TITLE
Improve return code documentation

### ISSUE THREAD

**Issue by matthewrsj** [clearlinux/swupd-client#296]
Right now https://github.com/clearlinux/swupd-client/blob/master/include/swupd-error.h is the only place swupd return codes are "documented". These return codes should be added to the man pages.

**Comment by matthewrsj** [comment]
See #292 for context

**Comment by pohly** [comment]
Are all of these codes really also potential exit codes of the executable?

For example, how does the executable return ENET404=404 to the caller? Exit codes have to fit into 8 bits (see WEXITSTATUS in "man waitpid"). Trying to call exit(ret) with ret=404 won't work as expected.

**Comment by phmccarty** [comment]
@pohly No, some of those error codes are only used for internal errors and not propogated back to main() or wherever exit() is called. We should probably segregate the internal error codes from the ones users should care about.

**Comment by icarus-sparry** [comment]
We should aim to fix exit codes into 7 bits as shells such as bash use 128+signal_number as the exit code for processes killed by signals.

**Comment by asifhg** [comment]
Cmd SUCCESS returns inconsistent return codes.
`swupd check-update ;# Returns 0.`
`swupd update --migrate ;# Returns 1.`

**Comment by matthewrsj** [comment]
`swupd update --migrate` should not be returning 1 on success. What indicated to you this was a successful operation? I need more information.
