### ISSUE TITLE
New autoreconf warning

### ISSUE THREAD

**Issue by phmccarty** [clearlinux/swupd-client#300]
Introduced in d918dd72320fb787bec14988b822f5c900cbb8fd, there is a new autoreconf warning:

```
Makefile.am:290: warning: dir $@: non-POSIX variable name
Makefile.am:290: (probably a GNU make extension)
```

**Comment by icarus-sparry** [comment]
Ah, my fault for suggesting doing it at make run time, rather than waiting for the shell to do it.
Assign it to me.
