### ISSUE TITLE
test: unpack_target_from_manifest() should support symlinks

### ISSUE THREAD

**Issue by phmccarty** [clearlinux/swupd-client#302]
In swupdlib.bash, unpack_target_from_manifest() supports files and directories, but not symlinks.

**Comment by icarus-sparry** [comment]
Something that can be done as part of #258 where potentially this function could go away, or be extended, e.g. to do deletes, handle type changes etc.

**Comment by phmccarty** [comment]
Yes, good point. This is potentially a subtask of #258, depending on how we want to implement that.

**Comment by matthewrsj** [comment]
@castulo can you take a look at this? I think your testlib functions support links already.

**Comment by matthewrsj** [comment]
I'm going to close it for now. If it is still valid, reopen.

**Comment by castulo** [comment]
@matthewrsj yes, you can create test bundles that include symlinks with the testlib.
