### ISSUE TITLE
Where is libreoffice?? Evince? Vlc?

### ISSUE THREAD

**Issue by unixbhaskar** [clearlinux/swupd-client#303]
Or did I missed those???

`
bhaskar@ClearLinux_04:56:51_Wed Oct 04:~ $ sudo swupd bundle-list
swupd-client bundle list 3.12.2
   Copyright (C) 2012-2017 Intel Corporation

bootloader
c-basic
desktop
desktop-apps
desktop-assets
desktop-autostart
desktop-gnomelibs
desktop-locales
dev-utils
dev-utils-dev
editors
editors-dev
go-basic
go-basic-dev
kernel-native
koji
kvm-host
libX11client
mail-utils
mail-utils-dev
mixer
network-basic
network-basic-dev
openssh-server
os-clr-on-clr
os-clr-on-clr-dev
os-core
os-core-dev
os-core-update
os-core-update-dev
os-installer
performance-tools
perl-basic
perl-basic-dev
pnp-tools-basic
python-basic
python-basic-dev
shells
storage-utils
storage-utils-dev
sysadmin-basic
sysadmin-basic-dev
tcl-basic
telemetrics
user-basic
Current OS version: 18080

`

**Comment by matthewrsj** [comment]
@unixbhaskar this is a clr-bundles issue, as swupd is agnostic as to which packages are in the bundles. I'll open an issue for you there.

**Comment by matthewrsj** [comment]
https://github.com/clearlinux/clr-bundles/issues/15
