### ISSUE TITLE
Error for <file> tarfile extraction, curl timeout?

### ISSUE THREAD

**Issue by aaronovz1** [clearlinux/swupd-client#305]
We have been experiencing this issue for a number of files. I was thinking it was a timeout issue with curl but I am not sure. I checked the <hash>.tar files that the errors were referring to under the "download" directory and they were showing as zero bytes. Is there something else I can look at to figure out what causes this?

This is using swupd-client 3.10.0

**Comment by icarus-sparry** [comment]
The swupd-client truncates the tar files to zero size after it has processed them to avoid downloading them again.  See [download_pack](https://github.com/clearlinux/swupd-client/blob/master/src/packs.c#L75) for the current code. This is not saying there are no errors, just that zero length tar files are expected. Perhaps we should waste a few bytes and write an explicit message into these files?

**Comment by aaronovz1** [comment]
Writing "OK" into the file would maybe help debugging. I'm still unsure of what is causing the errors though. I assumed the errors were because it tried to untar a zero byte file as looking at the code it already checks response code from curl?

________________________________

**Comment by aaronovz1** [comment]
I did a quick test to try narrow it down. I changed the update server to be a server on our local network which has worked fine in the past. We recently switched to using AWS S3 and I think this is causing the problem somehow. Has anyone tried using S3 as a storage for the update files?

**Comment by aaronovz1** [comment]
This was a problem with the S3 URL's I was using. For some reason using this form:
_http://bucket-name.s3.amazonaws.com_ caused issues, where as _https://s3-us-west-2.amazonaws.com/bucket-name_ works fine.
