### ISSUE TITLE
Remove generated man pages from repo

### ISSUE THREAD

**Issue by matthewrsj** [clearlinux/swupd-client#316]
As brought up in #311 by @icarus-sparry, we should not be checking man pages into the git repository:

> We ought to delete the man pages from the repo or else scrap the idea of using rst2man.  The current middle ground of guess what timestamps git is going to give you is just wrong.

We should remove them and add them to the .gitignore. This approach will require users to either have rst2man.py installed or they will have to pass something like the `--disable-manpages` flag introduced in #309.

**Comment by icarus-sparry** [comment]
How about the following idea.

1. Have the manual pages present in both the rst and man format in the repo.
1. Have rules for generating the man pages from the rst in the makefile.
1. Do not invoke them,even as part of the "make dist" step.
1. Have *tests* which skip if rst2man.py is not available, and pass if the output of rst2man agrees with the checked in pages.
1. Have rst2man.py as part of travis installation.

This would mean that there was no requirement for rst2man.py in the environment for yocto, as long as people there were not altering the manual pages. We have manual pages in man format available. We have tests to ensure that if people change the rst pages, they have checked in the updated man pages.

**Comment by matthewrsj** [comment]
That sounds like a good solution to me, since out of date man pages will be caught by our CI. The extra rule to update the man pages can be part of the release workflow (or any commit that updates the man pages).

**Comment by matthewrsj** [comment]
I closed #397 which was somewhat related to this discussion (or caused this discussion anyways). @ahkok mind weighing in here?
