### ISSUE TITLE
configurable download retries

### ISSUE THREAD

**Issue by pohly** [clearlinux/swupd-client#322]
I am writing tests for issue #249 that simulate network errors. Right now, the tests run very slowly due to the hard-coded retry interval of 10 seconds and MAX_TRIES = 3.

Can interval and max retries be made configurable?

How do you handle this in your own tests?

On a related note, I am seeing "swupd update" trying to download Manifest.MoM.tar four times, for an overall duration of 1:10min. It all depends on the definition of MAX_TRIES of course, but to me this looks like an off-by-one error.

If we had a command line option --max-tries=3, I would expect three GET requests at most. For --max-retries=3, one initial GET followed by three retries would also make sense.

It's trying the second manifest only once.

HTTP log:
```
2017-10-20 14:32:04,915 - oe-selftest - INFO - "GET /10/Manifest.MoM.tar HTTP/1.1" 500 -
2017-10-20 14:32:14,776 - oe-selftest - INFO - "GET /10/Manifest.MoM.tar HTTP/1.1" 500 -
2017-10-20 14:32:34,717 - oe-selftest - INFO - "GET /10/Manifest.MoM.tar HTTP/1.1" 500 -
2017-10-20 14:33:14,724 - oe-selftest - INFO - "GET /10/Manifest.MoM.tar HTTP/1.1" 500 -
2017-10-20 14:33:14,752 - oe-selftest - INFO - "GET /20/Manifest.MoM.tar HTTP/1.1" 500 -
````

Output:
```
Attempting to download version string to memory
Update started.
Preparing to update from 10 to 20
Failed to retrieve 10 MoM manifest
Retry #1 downloading from/to MoM Manifests
Failed to retrieve 10 MoM manifest
Retry #2 downloading from/to MoM Manifests
Failed to retrieve 10 MoM manifest
Retry #3 downloading from/to MoM Manifests
Failed to retrieve 10 MoM manifest
Failure retrieving manifest from server
Update took 69.8 seconds
```

This is with file:// version URL and http:// content URL. Conceptually this tests mirrors a functioning version server while the content server has some internal issue.

**Comment by pohly** [comment]
Could be implemented separately or together with issue #211.

**Comment by phmccarty** [comment]
I would love to see an option to disable the retry timeouts entirely. Right now, there is one functional test that intentionally hits download retries, so such an option would be useful for that purpose.

Making them configurable also sounds desirable.

**Comment by matthewrsj** [comment]
I see more of a use case for disabling retries entirely via a command line flag than I do for setting the max number of retries via the command line.

Setting the max tries as a configure option makes sense to me though.

**Comment by pohly** [comment]
On Fri, 2017-10-20 at 16:42 +0000, Matthew Johnson wrote:
> I see more of a use case for disabling retries entirely via a command
> line flag than I do for setting the max number of retries via the
> command line.

Depending on what aspect a test is covering, doing multiple retries may
just end up cluttering the event log. For my purpose ("is the overall
return code of the executable correct") I don't need retries. But I can
live with the current number of retries if at least the time delay can
be removed dynamically via command line option.

> Setting the max tries as a configure option makes sense to me though.

A configure option doesn't make sense to me, because then would have to
compile differently for testing and production use, or worse, compile
multiple times (for tests with and without retries).

**Comment by matthewrsj** [comment]
I meant to say I see a use case for disabling retry **timeouts** via command line not retries entirely. Yes this would be entirely for testing purposes.

I can see where one might want to set MAX_TRIES to a higher value in an environment with intermittent network connectivity. I don't really see where a user would want to specify the number of retries on the command line. Is a user really going to pass --max-tries 4 if it didn't work with 3? or --max-tries=1. If the above suggestion is done (timeouts set to zero) then --max-tries isn't really needed for testing.
