### ISSUE TITLE
Ctrl-C a swupd bundle-add <foo>, swupd doesn't recover

### ISSUE THREAD

**Issue by bavery22** [clearlinux/swupd-client#325]
Error: 
# swupd bundle-add os-core-dev                                                                         
swupd-client bundle adder 3.12.5                                                                         
   Copyright (C) 2012-2017                                                                                       
Downloading 
Installing bundle(s) 
Error: hash check failed for //usr/bin/bunzip2   

Steps to reproduce:
swupd bundle-add os-core-dev      
Hit Ctrl-C before it completes, I believe it was after download and during install.  I did this because I meant to Ctrl-C a different window.
+++

After this, I can add or remove other bundles, but add or remove operations on os-core-dev fail. the rm failure is:
swupd bundle-remove os-core-dev
swupd-client bundle remover 3.12.5
   Copyright (C) 2012-2017 Intel Corporation

Removing bundle: os-core-dev
Warning: Bundle "os-core-dev" does not seem to be installed
Error: Bundle remove failed
1 bundle(s) of 1 failed to remove
++++
swupd verify returns:
# swupd verify
swupd-client software verify 3.12.5
   Copyright (C) 2012-2017 Intel Corporation

Verifying version 18520
Verifying files
        ...100%
Inspected 32387 files
Verify successful

**Comment by matthewrsj** [comment]
The issue is that you CTRL-C'd the process before it put the bundle-identifying files under /usr. swupd verify by itself does not manage /usr, so you need to pass --picky. To fix this issue combine it with --fix like so:

```
swupd verify --fix --picky
```

**Comment by matthewrsj** [comment]
This actually `is` an issue, since a file can exist in the state directory with a bad hash. Therefore when swupd comes through to run verify --fix it sees the file exists there, does not download it, but fails with a hash mismatch error.

Swupd should remove that file and attempt a download instead of failing on a hash mismatch.

**Comment by phmccarty** [comment]
@matthewrsj I think we discussed this bug offline, but this should be a pretty trivial bug fix (adding an `unlink(targetfile)` right before [this line](https://github.com/clearlinux/swupd-client/blob/916555189312800ebc008497757d01145ef86c97/src/download.c#L103)).

**Comment by matthewrsj** [comment]
@phmccarty it actually needs to be added as an `else` to the hash verification. `verify_file` returns `true` when the hash matches, so for failure we need to `unlink` and continue to download.

PR coming shortly.

**Comment by matthewrsj** [comment]
regardless, the return needs to be `0` from that function, not `1`.

**Comment by phmccarty** [comment]
Ah, yes, you are right :-)
