### ISSUE TITLE
Hanging when no disk space is available

### ISSUE THREAD

**Issue by gtkramer** [clearlinux/swupd-client#328]
When using ister to create a virtual disk image, as swupd is performing an install of content, if the partition where content is being installed runs out of disk space, then swupd hangs indefinitely.  In this case, swupd should error out to allow ister to exit normally and log an error.  Below is a trace of the commands:

+ sudo -E ister.py -t /home/clear/clear-92be12be9967438d810c5eaa6b6778ca/image/ister.json -V https://cdn.download.clearlinux.org/update -C https://cdn.download.clearlinux.org/update -l /home/clear/clear-92be12be9967438d810c5eaa6b6778ca/log/ister.log -s /home/clear/clear-92be12be9967438d810c5eaa6b6778ca/image/Swupd_Root.pem -f 20
Reading configuration
Validating configuration
Creating virtual disk
Creating partitions
Mapping loop device
Creating file systems
Setting up mount points
Starting swupd. May take several minutes
Installing 5 bundles (and dependencies)
+ swupd verify --install --path=/tmp/ister-18720-b_v5m_u4 --manifest=18720 --contenturl=https://cdn.download.clearlinux.org/update --versionurl=https://cdn.download.clearlinux.org/update --format=20 --statedir=/var/lib/swupd -C /home/clear/clear-92be12be9967438d810c5eaa6b6778ca/image/Swupd_Root.pem

To reproduce this issue, the following ister.json file can be used (uploaded as ister.txt):
[ister.txt](https://github.com/clearlinux/swupd-client/files/1433024/ister.txt)

**Comment by matthewrsj** [comment]
Related to #266
