### ISSUE TITLE
Error downloading to local file

### ISSUE THREAD

**Issue by rayascott** [clearlinux/swupd-client#338]
I'm new to Clear Linux, and have installed the live version on VirtualBox on my Mac. I followed the getting started guide and that went smoothly. Everything installed as it should including the prompted install for os-utils-gui. I then moved on to creating and enabling a new user space. 

When I perform `swupd bundle-add os-clr-on-clr` I get a lot of errors with a similar message... 

`Curl: Error downloading to local file` also towards the end... `Path /usr/bin/7z is missing on the file system`. 

After that it attempts to close a file after a write and it returns a `No space left on device` message.

After converting the downloaded img file, I converted it to a vdi and then used VBoxManage to increase the virtual disks capacity to 30GB, so is there something I need to perform within the ClearLinux OS to fix the out of space error?

**Comment by rayascott** [comment]
It may be worth mentioning in the documentation for installing into VirtualBox that the default image will quickly run out of disk space if following the user guide. It's set to a maximum of 5GB, but I couldn't install Gnome after installing the os-utils-gui, as there wasn't enough disk space left.

**Comment by matthewrsj** [comment]
> After that it attempts to close a file after a write and it returns a No space left on device message.

As far as swupd goes, we have several issues open to improve our out-of-space messaging (#37, #266, #328). 

I'm not sure about your attempts at resizing the images you get from download.clearlinux.org. Have you tried creating an image using an installer image such as `https://download.clearlinux.org/current/<version>-installer.img`? What are the exact "getting started" docs you are referring to?

I would recommend sending an email to the Clear Linux mailing list (dev@lists.clearlinux.org), as there will probably be people there who have tried exactly what you are doing.

**Comment by rayascott** [comment]
The "getting started" docs I was referring to can be found by navigating through the documentation like thus... 

`Documentation > Get Started > Install Clear Linux in a virtual machine > Use VirtualBox*` which says to use `clear-XXXX-live.img.xz` for a VirtualBox install. If I try to use the installer disk image, even after a successful installation the OS hangs on startup with the message `FATAL: No Bootable medium found! System halted.`

The issue is resolved now however, since I've increased the VirtualBox drive size.
