### ISSUE TITLE
ajax.google.com tiemd out caused swupd failed to retrieve packages

### ISSUE THREAD

**Issue by AkatsukiRyuunosuke** [clearlinux/swupd-client#339]
I'm living in China and I intend to use Clear linux for compute use, but I could netither install the system or update the system using swpud.
Becuase the Google was banned in China, the ajax.google.com is also banned too.
Casuing the curl timed out while retrieving packages from http://cdn.download.clearlinux.org/update

Please use a more pure or simple Repository like Debian OR CentOS, or disable google ajax for chinese users.

Thank you!

**Comment by matthewrsj** [comment]
Very interesting. I'll pass this along to people responsible for the CDN.

**Comment by ahkok** [comment]
For record, `swupd` does not use `http`, but only `https`. The correct URL to the CDN is therefore:

https://download.clearlinux.org/update/

Second, `swupd` never uses `javascript`. The javascript that is visible when you visit this URL through a web browser is only used for cosmetic features and does not change the content or listings.

If there is a network issue with using ClearLinux inside China, we'd like to know about it, though.

**Comment by matthewrsj** [comment]
Closing based on @ahkok's comments
