### ISSUE TITLE
Error for 'X' download: No response received

### ISSUE THREAD

**Issue by tuxutku** [clearlinux/swupd-client#345]
<pre>
utku@clr-449e9b2a44f8458bb4885604dc172a1c ~/Programlar/libva-1.8-branch $ sudo swupd verify -f
sudo: /usr/share/defaults/sudo/sudoers.d is world writable
Password: 
swupd-client software verify 3.13.1
   Copyright (C) 2012-2017 Intel Corporation

Verifying version 19270
Starting download of remaining update content. This may take a while...
	...1%
File /usr/include/asm-generic/.install was not in a pack
	...15%Error for 28cb7c6cad23920f344157f48ae353caca34e9a2f5cff934a4fdaaf7509f2062 download: No response received
Error for a0ddc962507650d0f4f28c68dbef626acf43631a5c0a50bd61dd90f35e03c3b5 download: No response received
	...22%Error for d9d34a1e44f3684286dd07c6a9e1747a1307e4421cd5d70f71a548c446a9ca54 download: No response received
Error for d5fb6d952db507b8c391da314c02be8dbbf627f4287c5eb0e39f146674403489 download: No response received
Error for 77d351753f892194379c14317a86ac1aa0105f382d564e674a798f2111a94165 download: No response received
Error for 0bf57217729603f83a6dbf4f6341d4e15f48afccde4031b0c05445b1c4928c45 download: No response received
Error for 7b5683644cc8d7e1e6c6a46b5f59ee7fab91df569d93af842150f3c9c397c550 download: No response received
Error for 48edef9437d4d3a09cb628240b90b0af5deb37c75d1012b78cb8a93ef57efee8 download: No response received
Error for aa4f0e17e8f586b4a8be01cb3b94e1a8bc5f93a4cbba00ddcd656e7ddf69842c download: No response received
Error for f9e9ddd3abfe7140e078a4da829169c7f1cdeba38f339449c9cfffc77e2b2ee6 download: No response received
Error for 036c4e2bda8cd46f33031f4cde51af63b4b9a05c6d3d004af1bb1b5a4543b188 download: No response received
Error for 0c9723b50ef262b18813b707994c95c819d01275c2c64cdbb476a1b7cd9fbd05 download: No response received
Error for 8b0f198e544f9330ae7c9b93563000448fd073bcf64b314436fd3e2cee87bb3d download: No response received
</pre>

I just installed libva 1.8 and it relinked some files
I have decent internet connection and provider does not block intel

**Comment by tuxutku** [comment]
will try to update and then verify -f

**Comment by tuxutku** [comment]
<pre>
utku@clr-449e9b2a44f8458bb4885604dc172a1c ~/Programlar/libva-1.8-branch $ sudo swupd verify -f
sudo: /usr/share/defaults/sudo/sudoers.d is world writable
Password: 
swupd-client software verify 3.14.1
   Copyright (C) 2012-2017 Intel Corporation

Verifying version 19420
Starting download of remaining update content. This may take a while...
	...12%
File /usr/lib/firmware/GPL-2 was not in a pack
	...13%
</pre>
it seems to me works

**Comment by tuxutku** [comment]
<pre>
utku@clr-449e9b2a44f8458bb4885604dc172a1c ~/Programlar/libva-1.8-branch $ sudo swupd verify -f
sudo: /usr/share/defaults/sudo/sudoers.d is world writable
Password: 
swupd-client software verify 3.14.1
   Copyright (C) 2012-2017 Intel Corporation

Verifying version 19420
Starting download of remaining update content. This may take a while...
	...12%
File /usr/lib/firmware/GPL-2 was not in a pack
	...44%Error for a0ddc962507650d0f4f28c68dbef626acf43631a5c0a50bd61dd90f35e03c3b5 download: No response received
Error for d9d34a1e44f3684286dd07c6a9e1747a1307e4421cd5d70f71a548c446a9ca54 download: No response received
Error for d5fb6d952db507b8c391da314c02be8dbbf627f4287c5eb0e39f146674403489 download: No response received
Error for 77d351753f892194379c14317a86ac1aa0105f382d564e674a798f2111a94165 download: No response received
	...49%
</pre>
still no response received

**Comment by tuxutku** [comment]
verify -f was succesfull but coused another minor problems
![image](https://user-images.githubusercontent.com/24626743/33526013-f4b78210-d84a-11e7-8094-60747f445e08.png)
missing icons
![img_20171203_164206](https://user-images.githubusercontent.com/24626743/33526051-aa1845f4-d84b-11e7-98e4-002416ff8a76.jpg)
systemd[1]: gdm-hw-accel.service: Two services allocated for the same bus name org.gnome.DisplayManager, refusing operation.
also login animation is gone (no blackout, directly to xfce loading screen)

**Comment by matthewrsj** [comment]
In this case `curl_multi` is failing to even get a response from the update server. Since you are on version 19420 I assume you are using standard Clear Linux CDN for your contenturl. I haven't seen any other issues come up with that content from other users. Did this network error go away or is it still happening?

**Comment by tuxutku** [comment]
every time i tried to update as i remember
i will check it when i come back to home

**Comment by tuxutku** [comment]
<pre>
utku@clr-449e9b2a44f8458bb4885604dc172a1c ~ $ sudo swupd update
Password: 
swupd-client software update 3.14.1
   Copyright (C) 2012-2017 Intel Corporation

Update started.
Attempting to download version string to memory
Preparing to update from 19420 to 19440
Downloading packs...

Extracting c-basic pack for version 19440
	...4%
Extracting desktop pack for version 19440
	...11%
Extracting desktop-apps-extras pack for version 19430
	...14%
Extracting dev-utils pack for version 19430
	...24%
Extracting dev-utils-dev pack for version 19430
	...25%
Extracting kernel-native pack for version 19440
	...37%
Extracting koji pack for version 19430
	...38%
Extracting network-basic pack for version 19430
	...50%
Extracting network-basic-dev pack for version 19430
	...51%
Extracting os-core pack for version 19440
	...56%
Extracting os-core-dev pack for version 19440
Error: Hard-link target 'delta/18940-19430-77d10d52d01b23876c791c7373592af527e01738031f50fecbefbb2275797b9f-2816cda5372017babe9742d4837811e5b74d08e86f89ee4a9088d6e18fa28ed9' does not exist.
	...58%
Extracting python-extras pack for version 19430
	...79%
Extracting rust-basic pack for version 19440
	...83%
Extracting sysadmin-basic pack for version 19440
	...100%

Statistics for going from version 19420 to version 19440:

    changed bundles   : 14
    new bundles       : 0
    deleted bundles   : 0

    changed files     : 394
    new files         : 9905
    deleted files     : 1396

Starting download of remaining update content. This may take a while...
	...0%
File /usr/bin/guile was not in a pack
	...100%
Finishing download of update content...
Staging file content
Applying update
	...100%
Update was applied.
Calling post-update helper scripts.
Possible filedescriptor leak : 7 (socket:[26495])
Update took 207.3 seconds
Update successful. System updated from version 19420 to version 19440
209 files were not in a pack
</pre>

**Comment by matthewrsj** [comment]
Looks like that was successful, and this may have been a transient network error?
