### ISSUE TITLE
systemd[1]: gdm-hw-accel.service: Two services allocated... after swupd update and swupd verify -f

### ISSUE THREAD

**Issue by tuxutku** [clearlinux/swupd-client#346]
This is continue of https://github.com/clearlinux/swupd-client/issues/345 and its can be connected to that issue. 

verify -f was succesfull but coused another minor problems
![image](https://user-images.githubusercontent.com/24626743/33526013-f4b78210-d84a-11e7-8094-60747f445e08.png)
missing icons
![img_20171203_164206](https://user-images.githubusercontent.com/24626743/33526051-aa1845f4-d84b-11e7-98e4-002416ff8a76.jpg)
systemd[1]: gdm-hw-accel.service: Two services allocated for the same bus name org.gnome.DisplayManager, refusing operation.
also login animation is gone (no blackout, directly to xfce loading screen)

**Comment by matthewrsj** [comment]
This looks like a systemd issue. @ahkok can you tell what's going on here?

**Comment by matthewrsj** [comment]
This is actually a bug with the gdm-hw-accel.service in Clear Linux. The person responsible for this service (@mrkz) is aware of the issue and investigating.

Closing the issue here because it does not relate to swupd-client
