### ISSUE TITLE
File descriptor leak showing up again.

### ISSUE THREAD

**Issue by matthewrsj** [clearlinux/swupd-client#347]
Context can be found in #121 - basically this is a regression to an old issue that was closed a long time ago.

**Comment by ronindesign** [comment]
Reproduced on fresh install and when using live image, then issuing command `swupd bundle-add os-clr-on-clr`.

Bare metal install (on VMware vmdk config per docs)
Windows 10 v1709 (b17025.1000) (host)
Clear Linux (Fresh live: clear-19430-live.img.xz 2017-12-04 07:18) (guest)
Clear Linux (Fresh installer: clear-19430-installer.iso.xz 2017-12-04 07:18) (guest)
VMware Workstation 12 Pro (12.5.7 build-5813279)

**Comment by bswinnerton** [comment]
I also see this when installing `kernel-kvm` on a fresh install of OS version 19780.

```
brooks@nuc7i3 ~ $ sudo swupd bundle-add kernel-kvm
swupd-client bundle adder 3.14.2
   Copyright (C) 2012-2017 Intel Corporation

Downloading packs...

Extracting kernel-kvm pack for version 19460
        ...100%
Installing bundle(s) files...
        ...100%
Calling post-update helper scripts.
Possible filedescriptor leak : 6 (socket:[19457])
Possible filedescriptor leak : 7 (socket:[19459])
Bundle(s) installation done.
```

**Comment by phmccarty** [comment]
One of those file descriptor leaks appears to be a false positive...

The clr-boot-manager helper program, which is called by swupd for certain operations, also reports file descriptor leaks. It appears that clr-boot-manager is reporting a leak for the TCP socket opened by libcurl via swupd. This socket is later closed by swupd via libcurl, after clr-boot-manager exits. I verified this just now with strace.

My thinking is that clr-boot-manager should *optionally* check for file descriptor leaks, and when swupd calls it, it should not check for leaks. Else swupd will be stuck setting O_CLOEXEC for every file descriptor that clr-boot-manager should not care about. And I'm not sure it's possible to do this for the socket fd managed by libcurl.

**Comment by phmccarty** [comment]
And I see in issue #121 that I had tracked this down to clr-boot-manager previously. History repeating itself :-)

**Comment by phmccarty** [comment]
I opened a PR for clr-boot-manager to remove its file descriptor leak check. See https://github.com/clearlinux/clr-boot-manager/pull/98.

**Comment by matthewrsj** [comment]
That PR has since been merged. Closing this issue as I'm not seeing the error any more. Feel free to re-open if it shows up for anyone else.
