### ISSUE TITLE
/usr/src/kernel is ignored

### ISSUE THREAD

**Issue by miguelinux** [clearlinux/swupd-client#348]
Clear Linux* is shipping Linux headers sources in the /usr/src/kernel directory.

Currently that directory is banned in the Heurisitcs is_state() function.

**Comment by matthewrsj** [comment]
Is this new in Clear Linux, or has this always been an issue?

**Comment by miguelinux** [comment]
@matthewrsj yes

This is a new feature for the kernel in Clear Linux

**Comment by icarus-sparry** [comment]
Out of interest, why are you making this a "state" file. Why do you not want these files to be updated in new versions?

**Comment by miguelinux** [comment]
@icarus-sparry 

This is part of the kernel live patch project leaded by Jaime Garcia.

At /usr/src/kernel will be the headers sources from the current kernel.

**Comment by miguelinux** [comment]
@icarus-sparry @matthewrsj 

@chuyd sent an email regarding this issue.

BTW the files are listed at: https://download.clearlinux.org/update/19440/Manifest.sysadmin-basic
Some lines from that file:
```
D.s.	6c27df6efcd6fc401ff1bc67c970b83eef115f6473db4fb9d57e5de317eba96e	19440	/usr/src/kernel
D.s.	6c27df6efcd6fc401ff1bc67c970b83eef115f6473db4fb9d57e5de317eba96e	19440	/usr/src/kernel/4.14.3-483.native
F.s.	aae4759b256af9a1f14cbf3f66406dd84002c5100e8b2326c0a3884f93aaaaa0	19440	/usr/src/kernel/4.14.3-483.native/.config
D.s.	6c27df6efcd6fc401ff1bc67c970b83eef115f6473db4fb9d57e5de317eba96e	19440	/usr/src/kernel/4.14.3-483.native/Documentation
D.s.	6c27df6efcd6fc401ff1bc67c970b83eef115f6473db4fb9d57e5de317eba96e	19440	/usr/src/kernel/4.14.3-483.native/Documentation/kbuild
F.s.	137bad0663ff94314fd8f0f04d8abcb43dbd5db3e83c3a543843a025bd095170	19440	/usr/src/kernel/4.14.3-483.native/Documentation/kbuild/Kconfig.recursion-issue-01
F.s.	e4532ca948bd4c76f3a9cc3cb962a4e94ee123dd84f997be06ac5355ae1450f4	19440	/usr/src/kernel/4.14.3-483.native/Documentation/kbuild/Kconfig.recursion-issue-02
F.s.	3ad48589bc9f35ea3c0b64445ecf6ce9544187096f463bf997bd0211b644964b	19440	/usr/src/kernel/4.14.3-483.native/Documentation/kbuild/Kconfig.select-break
F.s.	e0f03718b0dcd4bfeed0a76ebee09826e8b253bbe20bedd01dd626bcf8c4ccf7	19440	/usr/src/kernel/4.14.3-483.native/Kconfig
```

**Comment by miguelinux** [comment]
An Isssue  clearlinux/swupd-server#108 and a PR  clearlinux/swupd-server#109 were opened to fix swupd-server fist.
