### ISSUE TITLE
bundle-add: interrupted tar download leaves incomplete tar around

### ISSUE THREAD

**Issue by matthewrsj** [clearlinux/swupd-client#352]
bundle-add does not know how to recover from this and keeps trying to used the partial pack.

For bundle-add, just re-download every time instead of trying to rely on a zero pack being in the state dir.

Related: https://github.com/clearlinux/clr-bundles/issues/28

**Comment by icarus-sparry** [comment]
Something else that would be easy to detect if we signed what we downloaded.
