### ISSUE TITLE
Consider adding a string_free() function

### ISSUE THREAD

**Issue by phmccarty** [clearlinux/swupd-client#357]
So that the code is consistent about resetting a pointer to NULL after freeing dynamic memory allocated at that location, consider adding a `string_free()` wrapper function. For an implementation idea, see the code snippet below (from #356).

```
void free_string(char **s)
{
    if (s) {
       free(*s);
        *s = NULL;
    }
}
```

**Comment by icarus-sparry** [comment]
For some strange reason I like this idea 🥇
