### ISSUE TITLE
Man pages out of date for -b option

### ISSUE THREAD

**Issue by matthewrsj** [clearlinux/swupd-client#358]
The man pages are out of date and are missing the `-b` option for `update` and `bundle-add` subcommands. 

Originally reported to https://github.com/clearlinux/clr-bundles/issues/31

**Comment by icarus-sparry** [comment]
Are we saying we should remove the -b option, and detect if we are in a container automatically, or we should fix the documentation, or both?

**Comment by matthewrsj** [comment]
I'm saying for now, the fact that we don't document "-b" is a bug, but we can discuss if we even need "-b" or if we should do automatic detection, which is why I opened #359.

**Comment by matthewrsj** [comment]
Closed in favor of #404
