### ISSUE TITLE
Detect when running in a container to skip CBM updates

### ISSUE THREAD

**Issue by matthewrsj** [clearlinux/swupd-client#359]
The -b option was originally added to avoid having to detect whether or not the process was running in a container. It is trivial to check (for docker) by checking for the existence of `/.dockerenv` or for lines containing `/docker/` in `/proc/1/cgroup`. Other container types could be checked there as well.

Originally reported to https://github.com/clearlinux/clr-bundles/issues/31

**Comment by tpepper** [comment]
In a good container you might not have those easy hints.  But even without the hints, the CBM run should fail more gracefully.

**Comment by cmarcelo** [comment]
We could use `systemd-detect-virt -c` or see what it does and do similar.

**Comment by matthewrsj** [comment]
Fixed by #374

**Comment by tpepper** [comment]
Systemd's not universally available inside containers.  But I suppose this
is currently "clearlinux/swupd-client" so...ok?

**Comment by bryteise** [comment]
Yea, I think updating kernels is going to always be super platform dependent. We likely eventually have a script that is called rather than cbm directly so that different OSs can make different decisions about bootloader and kernel update mechanics.
