### ISSUE TITLE
current_subs list not freed for update

### ISSUE THREAD

**Issue by phmccarty** [clearlinux/swupd-client#363]
Valgrind detects a memory leak for the update subcommand. See below for details.

```
==1601== 2,350 (24 direct, 2,326 indirect) bytes in 1 blocks are definitely lost in loss record 98 of 98
==1601==    at 0x482BADF: malloc (vg_replace_malloc.c:299)
==1601==    by 0x4A2D7F6: list_alloc_item (list.c:58)
==1601==    by 0x4A2D7F6: list_prepend_data (list.c:153)
==1601==    by 0x4A303C3: create_and_append_subscription (subscriptions.c:181)
==1601==    by 0x4A303C3: read_subscriptions (subscriptions.c:100)
==1601==    by 0x4A3A3D7: main_update (update.c:348)
==1601==    by 0x4092CD: update_main (main.c:253)
==1601==    by 0x485BF69: (below main) (libc-start.c:308)
```

This is likely the result of `swupd_deinit()` only freeing `latest_subs`, not `current_subs` as well.

`swupd_deinit()` could learn how to free an additional subscription list, or `free_subscriptions(&current_subs)` could be called outside that function, since the update subcommand is the only one that manages two subscription lists.

**Comment by matthewrsj** [comment]
Fixed by #460
