### ISSUE TITLE
[question] Is there a way to run a script/systemd-oneshot-service at install time?

### ISSUE THREAD

**Issue by mrkz** [clearlinux/swupd-client#364]
I do have update-triggers systemd service defined already, which executes the script/command when an update event happens, but I'd like to get this functionality/command to run at install time as well, so I have the functionality this command provides as soon as I install the use-case, and not wait for an update to happen.

**Comment by bryteise** [comment]
The systemd service isn't run at install time, swupd instead runs a different script that replicates the systemd functionality.

**Comment by matthewrsj** [comment]
the issue raised here turned out to be an issue in another script, which @bryteise fixed today. Is that correct @mrkz? Can this be closed?

**Comment by mrkz** [comment]
@matthewrsj yes, this turned out to be a regression introduced in https://github.com/clearlinux/swupd-client/commit/6966baf4fa3f13503cbaaf2c752ed0b4389a37ad about how triggers-update.target systemd units are handled by swupd. This can be closed now.

**Comment by matthewrsj** [comment]
Right, this was a bug in the script used by Clear Linux to provide post-update actions, not in swupd-client itself.
