### ISSUE TITLE
Use new os-core-update-index file for swupd search

### ISSUE THREAD

**Issue by matthewrsj** [clearlinux/swupd-client#394]
The new swupd-server (github.com/clearlinux/mixer-tools) creates an `os-core-update-index` bundle that contains a single file (`/usr/share/defaults/swupd/os-core-update-index`) that contains a list of all file->bundle mappings in OS, like so:
```
...
/usr/share/bar        bar-bundle
/usr/share/foo        foo-bundle
...
```
This file is sortd first by filename then by bundle size, allowing swupd search to use this file to quickly display results. In the future this file can include bundle size information as well. The benefit of an approach like this is that swupd will not have to download all the manifests in the OS to do a simple search for a file. Instead this file will exist on the filesystem (if the bundle is installed) and will get delta updates for each release.

**Comment by otaviobp** [comment]
Closing this issue because that index doesn't exist anymore. And the os-core-update-index is going to be removed.
