### ISSUE TITLE
Allow 'swupd' to run without root access for simple operation

### ISSUE THREAD

**Issue by gvancuts** [clearlinux/swupd-client#398]
Some operations such as `search`, `bundle-list` and possibly `check-update` should not need root access to be run. Today running those without root access returns an error:

```
swupd check-update 
swupd-client software update checker 3.14.6
   Copyright (C) 2012-2017 Intel Corporation

This program must be run as root..aborting.
```

**Comment by matthewrsj** [comment]
Unfortunately right now swupd has to download files to or read files from the root-owned statedir, which defaults to `/var/lib/swupd`, in order to determine metadata. For `search` and `bundle-list` it needs to read the `Manifest.MoM` and other manifests.

For `check-update` at least it appears you are right. There might be other commands that could have the root user requirement removed.

**Comment by matthewrsj** [comment]
#404 has the potential to greatly improve this, if implemented.

**Comment by gvancuts** [comment]
> #404 has the potential to greatly improve this, if implemented.

I fail to see how/what it will improve related to this feature request. Can you expand a bit?

**Comment by icarus-sparry** [comment]
I believe he meant #403 not #404

**Comment by cmarcelo** [comment]
> Unfortunately right now swupd has to download files to or read files from the root-owned statedir, which defaults to /var/lib/swupd, in order to determine metadata.

Optional: could the metadata files (which contents is public) be made world readable?

That solves just half of the cake, the other half is to download new files, which swupd could do in the users local cache directory, if not running as root (I guess dnf or some other similar tool does something like that?). And with the second half in place, we don't even need the first.

I don't get the relationship with #403 but I might be missing something. Whatever the contents of the manifest is, we still may have to download a new one anyway.

**Comment by matthewrsj** [comment]
This is not simple to implement without #403. Closing in favor of that.
