### ISSUE TITLE
Allow configuring an alternate system default mirror URL

### ISSUE THREAD

**Issue by bwarden** [clearlinux/swupd-client#410]
While swupd-client supports the -u parameter to specify an alternate URL, it would be useful to be able to configure this as a global default, overriding /usr/share/defaults/swupd/contenturl and perhaps /usr/share/defaults/swupd/versionurl, supporting installations in custom environments with local mirrors or custom-mixed repositories. This would enhance usability of the client from the command line, vs. creating an override for swupd-update.service.

Related to #295.

**Comment by otaviobp** [comment]
This issue was fixed by the addition of "swupd mirror" command
