### ISSUE TITLE
Memory leak & other bugs

### ISSUE THREAD

**Issue by K2** [clearlinux/swupd-client#413]
https://github.com/clearlinux/swupd-client/blob/516acc80fb658ccc2ca1e874720e77263a3db9b6/src/extra_files.c#L77

Even though there is another set of unchecked integer overflows here it's only a problem for 32bit builds.  If this OS is 64 only, it's only the memory leak you might worry about here.

In the event of a failure to realloc you're going to NULL out F and loose you're pointer/memory.  You may want to look at the new(circa. 2014)/adapted; 'reallocarray' function call from OpenBSD that has a revised prototype that eliminates the likelihood of both of the error's in this statement. 

```C
       void *reallocarray(void *ptr, size_t nmemb, size_t size);
```

**Comment by icarus-sparry** [comment]
Thank you for the report.

You are correct that if the realloc fails then memory is leaked.

If realloc fails, then record_filename returns ENOMEM, nftw returns ENOMEM, walk_tree returns without doing anything, verify_main returns after printing a few statistics and the program exits, releasing all the memory.

This is in contrast to the out of memory processing in much of the rest of the program, which calls string_or_die, which just aborts on out of memory.

The reallocarray from OpenBSD is interesting. It is not clear what you mean by `both of the errors`. The issues with the standard realloc is (a) that if it fails and you are just assigning back to the variable then you have a memory leak, and (b) that you specify the size in bytes, but most people are thinking in terms of arrays, and hence have to do the multiply of sizeof(element) by number_of_elements and of course multiplication in C is undefined if it overflows.

Am I missing something? reallocarray only fixes the latter problem not the former, and I can't see another error to fix.

**Comment by K2** [comment]
Oh it's that on 32bit there could be a potential for the integer overflow resulting in a dramatically smaller memory chunk returned due to the nature of an expression being evaluated within the scope of the argument to realloc.  Since reallocarray provides parameters for the calculation required to determine the size of the memory chunk, and internally guards against int overflows, it would prevent an issue on 32.  Since I don't think you have any 32bit builds, it's not really a big deal tbh.

**Comment by icarus-sparry** [comment]
@K2  We have added an explicit call to abort() on the out of memory condition, to make it clearer that if we run out of memory then we are giving up.

Thank you for the pointer to reallocarray, we probably adopt it.
