### ISSUE TITLE
Create a machine readable output for swupd commmands

### ISSUE THREAD

**Issue by dorileo** [clearlinux/swupd-client#433]
Print a status reporting how many steps swupd-client is supposed to report before the iterations calling ```print_progress()``` starts.

Bonus: It would be nice to report a description for the step.

i.e:
```bash
[step] verifying fix path: 10
.
.
.
```

**Comment by dorileo** [comment]
Talking with @matthewrsj we came up with a possibility of getting rid of the "dots system", but "reporting a description for the step" is extremely important/useful.

**Comment by mdhorn** [comment]
Both the installer and software center need machine-parseable output format
- New flag to only output machine parsable
- Need to flush every line of output so the is no buffering

Some like:
MESSAGE: "string"
STEP: 1:5: PREDEFINED_TAG_1
PROGRESS: 0
PROGRESS: 5
...
PROGRESS: 100
STEP: 2:5: PREDEFINED_TAG_2
PROGRESS: 0
PROGRESS: 5
...
ERROR: "<error message>"
STATUS: exit status

The PREDEFINED_TAG would then be locally mapped by the tool to known strings that can be translated for localization.

**Comment by otaviobp** [comment]
sounds good. But I'd like to define a format to use. It looks like YAML is a good format for this kind of output, but not sure how easy it is to print that in C without using any library.

**Comment by mdhorn** [comment]
@otaviobp As long as we can confirm that YAML can be parsed without hitting EOL; unless each line is valid YAML.

**Comment by castulo** [comment]
This is the bundle-add current output:
```
$ swupd bundle-add ansible

Downloading packs...
	...50%
Extracting ansible pack for version 28090
	...100%

Extracting ipmitool pack for version 28140
Starting download of remaining update content. This may take a while...
	...100%
Finishing download of update content...
Installing bundle(s) files...
	...100%
Calling post-update helper scripts.
Successfully installed 1 bundle
```
And this is part of the output generated by the `-t` flag, which actually shows better the stages or steps of the bundle installation:
```
Raw elapsed time stats:
   6096.71 ms: Total execution time
      0.01 ms: |-- Prepend bundles to list
   5332.58 ms: |-- Install bundles
      2.83 ms:     |-- Add bundles and recurse
      9.06 ms:     |-- Consolidate files from bundles
      0.00 ms:     |-- Check disk space availability
      0.26 ms:     |-- Download packs
    231.07 ms:     |-- Download missing files
   4983.22 ms:     |-- Installing bundle(s) files onto filesystem
    705.33 ms:         |-- Add tracked bundles
     96.49 ms:     |-- Run Scripts
```
Based on that we can divide the install in these steps:
1. Add bundles and recurse
2. Consolidate files from bundles
3. Check disk space availability
4. Download packs
5. Download missing files
6. Installing bundle(s) files onto filesystem
7. Run scripts

In large bundles the most time consuming steps are these (in order from slower to faster):
- step 4) Download packs
- step 6) Installing bundle(s) files onto filesystem
- step 5) Download missing files

## Proposal

We could use the  following JSON messages to provide info about the installation process when the --json flag is used (or whatever flag we decide is appropriate):

```
{
	"type" : "msg",
	"msg" : "some message"
}

{
	"type" : "error",
	"error" : "some error"
}

{
	"type" : "progress",
	"currentStep" : 1,
	"totalSteps" : 5,
	"stepCompletion" : 50,
	"stepDescription" : "some_action"
}

{
	"type" : "status",
	"status" : 0
}
```

Using that format in our bundle-add command output, and adding the install progress info, it would look something like this:

```
[
	{
		"type" : "progress",
		"currentStep" : 1,
		"totalSteps" : 7,
		"stepCompletion" : 100,
		"stepDescription" : "load_manifests"
	},
	{
		"type" : "progress",
		"currentStep" : 2,
		"totalSteps" : 7,
		"stepCompletion" : 100,
		"stepDescription" : "consolidate_files"
	},
	{
		"type" : "progress",
		"currentStep" : 3,
		"totalSteps" : 7,
		"stepCompletion" : 100,
		"stepDescription" : "check_disk_space"
	},
	{
		"type" : "progress",
		"currentStep" : 4,
		"totalSteps" : 7,
		"stepCompletion" : 0,
		"stepDescription" : "download_packs"
	},
	{
		"type" : "msg",
		"msg" : "Downloading packs…"
	},
	{
		"type" : "progress",
		"currentStep" : 4,
		"totalSteps" : 7,
		"stepCompletion" : 50,
		"stepDescription" : "download_packs"
	},
	{
		"type" : "progress",
		"currentStep" : 4,
		"totalSteps" : 7,
		"stepCompletion" : 85,
		"stepDescription" : "download_packs"
	},
	{
		"type" : "progress",
		"currentStep" : 4,
		"totalSteps" : 7,
		"stepCompletion" : 100,
		"stepDescription" : "download_packs"
	},	
	{
		"type" : "progress",
		"currentStep" : 5,
		"totalSteps" : 7,
		"stepCompletion" : 0,
		"stepDescription" : "download_fullfiles"
	},
	{
		"type" : "msg",
		"msg" : "Starting download of remaining update content. This may take a while…"
	},
	{ etc… }
]
```

**Comment by mdhorn** [comment]
@castulo This looks like what we need for something which is machine and stream parsable.
The one change I think we would need is that each line (separated by newline) should be a standalone JSON string. This was we can read a single line and parse it for the current status. More like:

```
{"type":"progress","currentStep":1,"totalSteps":7,"stepCompletion":100,"stepDescription":"load_manifests"}
{"type":"progress","currentStep":2,"totalSteps":7,"stepCompletion":100,"stepDescription":"consolidate_files"}
{"type":"progress","currentStep":3,"totalSteps":7,"stepCompletion":100,"stepDescription":"check_disk_space"}
{"type":"progress","currentStep":4,"totalSteps":7,"stepCompletion":0,"stepDescription":"download_packs"}
{"type":"msg","msg":"Downloadingpacks…"}
{"type":"progress","currentStep":4,"totalSteps":7,"stepCompletion":50,"stepDescription":"download_packs"}
{"type":"progress","currentStep":4,"totalSteps":7,"stepCompletion":85,"stepDescription":"download_packs"}
{"type":"progress","currentStep":4,"totalSteps":7,"stepCompletion":100,"stepDescription":"download_packs"},
{"type":"progress","currentStep":5,"totalSteps":7,"stepCompletion":0,"stepDescription":"download_fullfiles"}
{"type":"msg","msg":"Startingdownloadofremainingupdatecontent.Thismaytakeawhile…"}
{etc…}
```

**Comment by castulo** [comment]
@mdhorn  yeah, that was my original idea, but @otaviobp suggested throwing everything in an array so in case we are sending all that to a file, it could be possible to read the whole file and it would be a valid json too. 

because this not a valid json (unless you read it line by line) 
```
{"type":"progress","currentStep":1,"totalSteps":7,"stepCompletion":100,"stepDescription":"load_manifests"}
{"type":"progress","currentStep":2,"totalSteps":7,"stepCompletion":100,"stepDescription":"consolidate_files"}
```

but this is valid json:
```
[{"type":"progress","currentStep":1,"totalSteps":7,"stepCompletion":100,"stepDescription":"load_manifests"},
{"type":"progress","currentStep":2,"totalSteps":7,"stepCompletion":100,"stepDescription":"consolidate_files"}]
```

**Comment by otaviobp** [comment]
JSONs are streamably parsable (I've never parsed that in go, but there are several JSON parsers that uses the visitor design pattern, what's also recommended for large files). We can print everything in the same line, but I see no reason to guarantee that. Removing \n and ',' is pretty easy too, if your parser doesn't support partial parsing.

I prefer to print a valid JSON as the output because I prefer to use a well defined standard than created a new one that is custom (a list of JSONs is a new standard). And them every person that needs to parse the output would need to noticed that she/he can't use a json parser for the full output.

Parsing the output as a stream is one important use case for this feature, but there are other use cases for parsing the final output after swupd is completed (for example to gather the total download bytes and elapsed time to measure performance).

**Comment by mdhorn** [comment]
@otaviobp We can investigate this, but the current need for this new format is the reading a live stream for both the installer and the software center, so those needs should drive this implementation.

**Comment by castulo** [comment]
@josuedhg can you please take a look at this proposal and confirm this would work for your use case with the software center?

**Comment by castulo** [comment]
Something like: 

`{"type":"msg","msg":"Downloading packs…"},`

should be a valid json.... so even if you parse it line by line, it should work for your parser @mdhorn , you would just need to ignore the initial "[" and the last "]", since they are going to be in their own line it should not be a problem for your code to ignore those. Should it?

**Comment by josuedhg** [comment]
I think that is useful :D

**Comment by mdhorn** [comment]
> Something like:
> 
> `{"type":"msg","msg":"Downloading packs…"},`
> 
> should be a valid json.... so even if you parse it line by line, it should work for your parser @mdhorn , you would just need to ignore the initial "[" and the last "]", since they are going to be in their own line it should not be a problem for your code to ignore those. Should it?

That seems very reasonable.

**Comment by otaviobp** [comment]
You can use the GoLang json parser to parse partial JSONs. It's a lot better than trying to remove chars and parse yourself. This is working fine for me, but I haven't added a good error checking. It's important to check tokens for [ and ] and that every element is an object.

	dec := json.NewDecoder(bufio.NewReader(os.Stdin))

	if tok, err := dec.Token(); err == nil {
		fmt.Printf("> %v\n", tok)
	} else {
		log.Fatal(err)
	}
	for dec.More() {
		var data map[string]interface{}
		err := dec.Decode(&data)
		if err != nil {
			log.Fatal(err)
		}

		fmt.Printf("item: %v\n", data)
	}
	if tok, err := dec.Token(); err == nil {
		fmt.Printf("> %v\n", tok)
	} else {
		log.Fatal(err)
	}

**Comment by otaviobp** [comment]
To close this issue we also need to close #864

**Comment by castulo** [comment]
@mdhorn @josuedhg please take a look at the PR submitted to implement this to see if that would provide you with all the info you need for your use cases -> #846
