### ISSUE TITLE
Warning: Linkname can't be converted from UTF-8 to current locale.

### ISSUE THREAD

**Issue by cmarcelo** [clearlinux/swupd-client#445]
When extracting symlinks with non-ASCII (UTF-8) characters in the name, swupd (actually libarchive) complains about converting even if the current locale is UTF-8.

We first investigated whether Mixer was generating something wrong, but it seems to be generating valid tar files. That investigation is in https://github.com/clearlinux/mixer-tools/issues/92. The next stop is looking a libarchive, as the error message seems misleading.

For debugging libarchive, a starting point:

```
<thiago> if anyone wnats to debug this, put a breakpoint in archive_entry.c line 1301 with condition r != 0
<thiago> the debug fuse doesn't work for me (container)
```

**Comment by matthewrsj** [comment]
swupd now uses a more recent version of libarchive. This needs to be tested to see if it is still an issue.

**Comment by otaviobp** [comment]
This problems is still present on Clear 25040, swupd version 3.17.14, when installing os-core.

**Comment by aaronovz1** [comment]
I am noticing this on 3.17.15 with libarchive 3.3.3.

**Comment by jbhanks** [comment]
I am also getting this when I try to install the ISO into a virtual machine. The downloads then proceed without error, but suspiciously fast. The subsequent install is devoid of even the most basic shell programs (such as ping and sudo). 
 Not sure if the two are related.
![clearutferror](https://user-images.githubusercontent.com/12942318/48178088-fde79180-e2e5-11e8-9679-f4239b8f21a3.png)

![clearnotfound](https://user-images.githubusercontent.com/12942318/48178098-05a73600-e2e6-11e8-8d23-30c901ef0d98.png)

**Comment by otaviobp** [comment]
> I am also getting this when I try to install the ISO into a virtual machine. The downloads then proceed without error, but suspiciously fast. The subsequent install is devoid of even the most basic shell programs (such as ping and sudo).

This is all expected. You are installing only 4 small bundles (os-core, bootloader, kernel-kvm, os-core-update), so it should be fast. sudo and ping aren't included in thoses bundles, so they should fail.

If you want to install them you can do that by running:

   $ swupd bundle-add network-basic sudo

> Not sure if the two are related.

The problems aren't related. The "Warning: Linkname..." is a known bug when installing os-core bundle and the only issue we have is the warning being printed. The final installed system is sane and work fine.
