### ISSUE TITLE
mixin/mixer integration: unable to update to latest clear version

### ISSUE THREAD

**Issue by matthewrsj** [clearlinux/swupd-client#446]
If a file in os-core is updated in a new upstream Clear version mix collisions will be detected between the locally-built os-core files and the upstream ones. Because of this the mixin build either needs to occur before the unique files check or the os-core files need to not be checked. The second option could be problematic if the custom RPMs have a dependency on an upstream RPM and the upstream RPM changes in the latest version.

**Comment by iphutch** [comment]
@tmarcu have you been able to scope this issue? Any ETA?

**Comment by matthewrsj** [comment]
@iphutch I'm taking this issue. Pushing my fix shortly.
