### ISSUE TITLE
Delay in server response may lead to truncated data in client

### ISSUE THREAD

**Issue by acornea** [clearlinux/swupd-client#45]
Delays in the server response writes can make the client receive only truncated data, which can cause the client think there is no new updates available.
Tested on swupd v2.87 with a custom server.

Below the HTTPRequestHandler for a python HTTP Server for reproduction:
```
class SlowResponse(BaseHTTPServer.BaseHTTPRequestHandler):
    """Handler that returns data with a set delay between writes"""
    def do_GET(self):
        self.send_response(200)
        self.send_header("Content-type", "text/html")
        self.end_headers()
        response = "99990"
        delay = 0.00001 # seconds
        for c in response:
            self.wfile.write(c)
            sleep(delay)
```
Below are the responses observed for curl command and swupd check-update:

```
$ curl $IP:$PORT/version/format3/latest
99990
$ swupd check-update --url=$IP:$PORT
swupd-client software update checker 2.87
   Copyright (C) 2012-2015 Intel Corporation
   bsdiff portions Copyright Colin Percival, see COPYING file for details

There are no updates available
```

**Comment by barbieri** [comment]
I don't see how checking content-length will help this given that the content-length may be too big.

For some things, like the version, we can have a limit on the expected file size, But for others you can't know beforehand unless told from a secure source (like a previous Manifest). However the entry points can still get content-lenght: 1000000000000 and that will lead to OOM.

**Comment by acornea** [comment]
@barbieri i think your response should be about issue #44, not this one

**Comment by acornea** [comment]
Coming back to the issue at hand. Re-tested with the following parameters: delay= 0.00001 , version = 12345670

Strace on client showed that, sometimes, due to the delay, only the last part of the version gets read. Examples below
```
recvfrom(4, "345670", 16384, 0, NULL, NULL) = 6
recvfrom(4, "2345670", 16384, 0, NULL, NULL) = 7
recvfrom(4, "70", 16384, 0, NULL, NULL) = 2
recvfrom(4, "12345670", 16384, 0, NULL, NULL) = 8
recvfrom(4, "5670", 16384, 0, NULL, NULL) = 4
```
The client then exits based on the information got.

However, there is one case that drew my attention. Sometimes, when the client receives only 3 characters (670), the client reports as the corresponding version  6704. 
```
sendto(4, "GET /version/format3/latest HTTP"..., 105, MSG_NOSIGNAL, NULL, 0) = 105
poll([{fd=4, events=POLLIN|POLLPRI|POLLRDNORM|POLLRDBAND}], 1, 0) = 0 (Timeout)
poll([{fd=4, events=POLLIN}], 1, 197)   = 1 ([{fd=4, revents=POLLIN}])
poll([{fd=4, events=POLLIN|POLLPRI|POLLRDNORM|POLLRDBAND}], 1, 0) = 1 ([{fd=4, revents=POLLIN|POLLRDNORM}])
recvfrom(4, "HTTP/1.0 200 OK\r\nServer: BaseHTT"..., 16384, 0, NULL, NULL) = 122
poll([{fd=4, events=POLLIN}], 1, 196)   = 1 ([{fd=4, revents=POLLIN}])
poll([{fd=4, events=POLLIN|POLLPRI|POLLRDNORM|POLLRDBAND}], 1, 0) = 1 ([{fd=4, revents=POLLIN|POLLRDNORM}])
recvfrom(4, "670", 16384, 0, NULL, NULL) = 3             //receives version 670
poll([{fd=4, events=POLLIN}], 1, 195)   = 1 ([{fd=4, revents=POLLIN}])
poll([{fd=4, events=POLLIN|POLLPRI|POLLRDNORM|POLLRDBAND}], 1, 0) = 1 ([{fd=4, revents=POLLIN|POLLRDNORM}])
recvfrom(4, "", 16384, 0, NULL, NULL)   = 0
close(4)                                = 0
write(1, "There is a new OS version availa"..., 42There is a new OS version available: 6704
) = 42                                                                                           // somehow gets version 6704
```

I have tested with another version (34567890) and when a version of length 3 is received (890) the client reports 8906. I think this might be due to some buffer overwrite, but this is really weird behavior. Again, curl reports the correct version when querying the latest version file.

```
recvfrom(4, "890", 16384, 0, NULL, NULL) = 3
poll([{fd=4, events=POLLIN}], 1, 197)   = 1 ([{fd=4, revents=POLLIN}])
poll([{fd=4, events=POLLIN|POLLPRI|POLLRDNORM|POLLRDBAND}], 1, 0) = 1 ([{fd=4, revents=POLLIN|POLLRDNORM}])
recvfrom(4, "", 16384, 0, NULL, NULL)   = 0
close(4)                                = 0
write(1, "There is a new OS version availa"..., 42There is a new OS version available: 8906
) = 42
```

**Comment by acornea** [comment]
The issue seems to be in swupd_download_version_to_memory()  which can be called multiple times by libcurl to process data received. 

The function always copies the data to tmp_version, assuming it is the final correct one.

When multiple calls occur, the function will overwrite previously written data to tmp_version instead of appending to it, which can lead to the truncated version and the weird version issue (previous data at the end of the version reported).

The fix is to simply keep track of previous data, and append to it at each call.

**Comment by phmccarty** [comment]
William is working on a fix.

**Comment by phmccarty** [comment]
The fix has been merged.
