### ISSUE TITLE
Send telemetry for delta pack misses

### ISSUE THREAD

**Issue by phmccarty** [clearlinux/swupd-client#450]
Because Clear Linux DevOps tries to create as many delta packs as it needs to, it would be helpful to send telemetry for cases when swupd-client tries to download a delta pack and encounters a 404 server error.

**Comment by cmarcelo** [comment]
I've sent a PR for this, since I think would be useful information for our devops (regardless of the answer to my question below).

But I wonder: when there's a format bump, do we make all the packs between versions before the bump and the last version?

**Comment by matthewrsj** [comment]
> when there's a format bump, do we make all the packs between versions before the bump and the last version?

No we do not

**Comment by matthewrsj** [comment]
but that doesn't matter, because the clients have to update to the last in a format before continuing.

**Comment by cmarcelo** [comment]
>> when there's a format bump, do we make all the packs between versions before the bump and the last version?
> No we do not
> but that doesn't matter, because the clients have to update to the last in a format before continuing.

To be clear, I meant the "last version of that format". But I guess the answer is the same. :-)

The scenario I'm thinking: machine is in 20000/20 (version/format). OS is already in 21500/21. Last version in format 20 is 20990/20. We have deltas TO 20990 from a few versions, but we might not from 20000. That will generate telemetry information (I think is fine, but we may decide in the future to filter it a little better).

**Comment by matthewrsj** [comment]
Oh, yes that is absolutely fine.

Say we create deltas 10 versions back: 20890 -> 20990
We also create deltas from first in a format -> current, so update cycles over format bumps will (should) always have packs from first to latest.
