### ISSUE TITLE
autoupdate info needs to be displayed

### ISSUE THREAD

**Issue by bdphipps** [clearlinux/swupd-client#462]
It would be extremely helpful to see the current status of swupd autoupdate being enabled or disable. This could either be a flag added to the swupd autoupdate command or part of the display of swupd info.

**Comment by otaviobp** [comment]
I don't know if I got your proposal. If you run 'swupd autoupdate' it will print the current status of the autoupdate. I agree though that it would be nice to add a message "Autoupdate enabled" after running 'swupd autoupdate --enable', just to be clearer to the user that the autoupdate was turned on. (And obviously we need the same for 'autoupdate --disable')

**Comment by matthewrsj** [comment]
```
# swupd autoupdate
Disabled
```

**Comment by bdphipps** [comment]
Well, darn it. ☺

Maybe I should open a new feature request to add this to the swupd autoupdate –h output. I saw nothing about this any where that I’ve looked so far.

Thanks!

**Comment by icarus-sparry** [comment]
The manual page says the following

      autoupdate [--enable|--disable]
          Enables or disables automatic updates, or reports current status. Enabling updates does not cause an  imme 
          diate update - use swupd update to force one if desired.

and under EXIT STATUS


       If the subcommand was autoupdate without options, then the program returns 0 if automatic updating is enabled.
