### ISSUE TITLE
More detailed error message when applying delta fails

### ISSUE THREAD

**Issue by cmarcelo** [clearlinux/swupd-client#469]
The error message in

https://github.com/clearlinux/swupd-client/blob/master/src/delta.c#L178

is used both in the case that the "from" file is not supposed to exist (not in the manifests, so this delta shouldn't be in the delta pack) and when it should be there but the actual file has a different hash (file was modified in disk).

Based on a report in IRC:

```
<btwarden> Going from 22750 to 22780, I got a lot of these:
<btwarden> Couldn't use delta file /var/lib/swupd/delta/22690-22760-eee8dcc4e4b9a01b0e13140f12f0cbf97be9ebe3d91cc1abbed9274cb00f9722-1af976c327403cc6f300bb1bb64ea3284cbd3279d6071bbfedba430e7ac02a9a: no 'from' file to appl
```

The from hash refers to a `pyc` file (eee8dcc4e4b9a01b0e13140f12f0cbf97be9ebe3d91cc1abbed9274cb00f9722), that possibly could have been modified.

**Comment by matthewrsj** [comment]
@tmarcu some insight on the issue reported by @bwarden

**Comment by bwarden** [comment]
clearlinux/distribution#82
