### ISSUE TITLE
Be consistent in bundle-add/bundle-remove error messages

### ISSUE THREAD

**Issue by cmarcelo** [clearlinux/swupd-client#475]
The operations have different command result output styles. In particular bundle-remove error is a bit redundant. Examples of the current output below:

Removing an existing bundle that was not added:

```
$ sudo swupd bundle-remove unison
Removing bundle: unison
Warning: Bundle "unison" does not seem to be installed
Error: Bundle remove failed
1 bundle(s) of 1 failed to remove
```

Adding a bundle that is already added:

```
$ sudo swupd bundle-add editors
nothing to add, exiting now
```

Adding a bundle that does not exist:

```
$ sudo swupd bundle-add editorsa
editorsa bundle name is invalid, skipping it...
Error: Bad bundle name(s) detected - Aborting
```

**Comment by castulo** [comment]
There is a PR #472 open at the moment to do refactoring to to bundle-remove function, it may be a good time to incorporate some changes based on this.

**Comment by matthewrsj** [comment]
@castulo assigning this to you. Should be a very quick fix.
