### ISSUE TITLE
Double Free corruption 

### ISSUE THREAD

**Issue by tmarcu** [clearlinux/swupd-client#480]
$ sudo -E swupd update --migrate
Attempting to migrate to your mix content...

Update started.
Preparing to update from 22880 to 22880000
Warning: hash check failed for Manifest.os-core for version 22880000. Deleting it.
Warning: Removing corrupt Manifest.os-core artifacts and re-downloading...
Downloading packs...
...100%

Statistics for going from version 22880 to version 22880000:

changed bundles   : 1
new bundles       : 0
deleted bundles   : 0

changed files     : 3998
new files         : 0
deleted files     : 0
Starting download of remaining update content. This may take a while...

Finishing download of update content...
Staging file content
File staging failed: /usr/share/clear/version
Calling post-update helper scripts.
double free or corruption (fasttop)
Aborted

**Comment by matthewrsj** [comment]
```
Warning: hash check failed for Manifest.os-core for version 22880000. Deleting it.
Warning: Removing corrupt Manifest.os-core artifacts and re-downloading...
```
is the first issue. Shouldn't be seen as having a bad hash since these are coming from our mix. Obviously the `double free or corruption` is another issue.

**Comment by tmarcu** [comment]
I agree, but since it succeeded on the retry it is very likely there was just bad content laying around with the same version from a previous run, otherwise it usually won't get past that warning.

**Comment by matthewrsj** [comment]
Nope, I was able to reproduce with a clean state dir.

**Comment by matthewrsj** [comment]
Remember mixin creates a new os-core manifest which has a different hash due to the timestamp.

**Comment by matthewrsj** [comment]
This issue is *not* present in 887716ad56472d2db664144ab264baee6b17add0

**Comment by matthewrsj** [comment]
The issue is introduced in c491c6d058e6f51bdd07ff4672916ed5e456d0c5. Assigning to @otaviobp

**Comment by matthewrsj** [comment]
```
Warning: hash check failed for Manifest.os-core for version 22880000. Deleting it.
Warning: Removing corrupt Manifest.os-core artifacts and re-downloading...
```
is introduced in c491c6d058e6f51bdd07ff4672916ed5e456d0c5, along with 
```
$ sudo ./swupd bundle-add hellowrldbundle
Password: 
Certificate verification error: self signed certificate
WARNING!!! FAILED TO VERIFY SIGNATURE OF Manifest.MoM version 22880000
Cannot load official manifest MoM for version 22880000
```
It appears the double-free issue was introduced later.

**Comment by otaviobp** [comment]
Can you test https://github.com/clearlinux/swupd-client/pull/481?

**Comment by otaviobp** [comment]
I couldn't reproduce the hash problems with a clean swupd cache. 
Update --migrate and bundle-add working fine with a mix here. Can you check if you find a way to reproduce the hash problem?

**Comment by matthewrsj** [comment]
@otaviobp I was unable to reproduce the hash issues. Since everything seems to be working with the fix you did I think we can close this. Thanks for your work on this.
