### ISSUE TITLE
"swupd check-update" should show very latest version based on very latest format available

### ISSUE THREAD

**Issue by bktan8** [clearlinux/swupd-client#482]
Today, "swupd update -s" only shows you the latest available version for the current format the system is on.  It doesn't show the very latest available version based on the very latest format.  I think this is misleading because when an update is performed, it actually brings the system to the very latest version based on the very latest format.  

For example:
If the user's system is on 21010, "swupd update -s" shows the latest version as 21070 - based on format 23.  So when the user performs the update, they think they are getting 21070, but in fact it's going all the way to 24130 (for example) based on format 24.  

Improvement suggestion is to provide more information saying that you're on a version based on a specific format.  The very latest available version is X and its format is Y...

**Comment by bktan8** [comment]
Johnson, Matthew added a comment - 20/Mar/18 5:15 PM

Mccarty, Patrick you mean this: https://download.clearlinux.org/latest ?

**Comment by bktan8** [comment]
Mccarty, Patrick added a comment - 20/Mar/18 5:26 PM

Johnson, Matthew, Hmm, maybe. That location lives outside of /update/ though, and swupd-client only downloads files from /update/. So we would need to introduce more restrictions to how a devops team can publish their content. I think a location under /update/ would be better.

**Comment by bktan8** [comment]
Marcu, Tudor added a comment - 20/Mar/18 5:28 PM

I don't think the default behavior should be listing that file ^, because it is also misleading in that someone may think they can just update/verify --fix to it as well. Swupd is hardcoded to understand its current format only so we avoid breaking changes except through format bumps. 
Saying latest version: 21070 (Format 23) would be a nice improvement, though, and very trivial change to make.

**Comment by bktan8** [comment]
Johnson, Matthew added a comment - 18/May/18 11:23 PM

Not very trivial. You would have to find the latest format from the versions directory, then find the latest file in that directory.

**Comment by gvancuts** [comment]
`swupd check-update` has the same misleading output. It will only tell you what is the latest version available within the same format (without explaining why it's not seeing newer versions). Running `swupd update` will however update the system to the very latest.

It may not be a very trivial change but it does not sound very hard either. It should be easy enough to parse the list of `format*` folders in https://download.clearlinux.org/update/version, take the highest number and read the content `latest` in that folder... or am I missing something?

@bktan8 's suggestion would make it even easier to implement by having a https://download.clearlinux.org/update/version/latestformat that points at the latest one at any point in time.

It's understood that things like `verify --fix` would not work across format bumps. IMHO, a more user-friendly behaviour than the one currently in place would be to:
* List the latest update available (both in the same format and latest format)
* Inform the user that updating beyond a format bump will prevent him from reverting those changes

**Comment by otaviobp** [comment]
> It may not be a very trivial change but it does not sound very hard either. It should be easy enough to parse the list of format* folders in https://download.clearlinux.org/update/version, take the highest number and read the content latest in that folder... or am I missing something?

It's not a good solution to parse the content of that URL because that's a html file that can change. And different servers can output different content. The ideal would be to have a file with that information. But I prefer a latestformat instead of a latest_version, so we can find the lastest format to get the latest version.

I reopened the issue in mixer requesting that file: https://github.com/clearlinux/mixer-tools/issues/467
