### ISSUE TITLE
Unlink manifest cache files at the end of an operation

### ISSUE THREAD

**Issue by phmccarty** [clearlinux/swupd-client#484]
When a manifest cache file (\<VER\>/Manifest.\<BUNDLE\>.\<HASH\>) exists in the state directory for a manifest, a hash check for that manifest ends prematurely without computing its hash because the cache file and manifest file are hardlinked and therefore share the same inode.

To protect against the possibility of swupd-client corrupting either a bundle manifest or an associated cache file, I think the cache files should be unlinked after a swupd operation (e.g. `swupd update`) is complete. This way, the optimization provided by the cache files (i.e. not duplicating manifest hash checks for deeply nested bundle hierarchies) is still present for the duration of the operation, and by unlinking the cache files afterward, we avoid the possibility of future corruption, as the manifest hashes will be recomputed and cache files recreated at the beginning of the next operation.

**Comment by matthewrsj** [comment]
Right now all Manifests are left around after an update, including the hashed version. I agree these should be removed.
