### ISSUE TITLE
Print warnings and errors consistently

### ISSUE THREAD

**Issue by matthewrsj** [clearlinux/swupd-client#489]
We sometimes print warnings like
```
WARNING: ...
```
sometimes like
```
Warning: ...
```
and sometimes just
```
...
```
without the prefix.

We should have `print_warn` and `print_error` functions to make our warnings and errors consistent. They should accept `va_list` type arguments for formatted strings.

**Comment by otaviobp** [comment]
This task is related, in a way, with #294.
It would be nice to define where we want our output to go and do it consistently too.
