### ISSUE TITLE
Make /var/lib/swupd world-readable

### ISSUE THREAD

**Issue by matthewrsj** [clearlinux/swupd-client#490]
We should make the state directory world-readable so we can do all `bundle-list` operations as non-root. I don't believe there's anything in there that users can't already find published on the update server.

**Comment by otaviobp** [comment]
we just need to make sure that we don't give read access to staged/ and telemetry/ dirs. The ideal would be to move all manifests to manifest/ and all packs to packs/ to keep things organized.

**Comment by bryteise** [comment]
Any more thoughts on having a per (hashed) content URL folder with those kinds of things under it?

**Comment by bryteise** [comment]
3rd-party stuff also ends up under the swupd statedir btw.

**Comment by otaviobp** [comment]
> Any more thoughts on having a per (hashed) content URL folder with those kinds of things under it?

I like the idea, but I think that we shouldn't use the hash of the URL, because that would create duplication for mirrors. The ideal would be to have an identifier for that specific mix, but I don't think we have one.

**Comment by bryteise** [comment]
You could use the /usr/lib/os-release URL (assuming mixes change it).

**Comment by otaviobp** [comment]
> You could use the /usr/lib/os-release URL (assuming mixes change it).

Not a bad idea. Not sure if mix changes that, but if not, it should. The only problem is that this isn't exposed in the mix (just as a file to be installed). It would be nice to have that string in a file somewhere in update/ directory.

**Comment by otaviobp** [comment]
Mixer isn't changing that :(
