### ISSUE TITLE
proposal: iterative manifests

### ISSUE THREAD

**Issue by matthewrsj** [clearlinux/swupd-client#498]
# problem

Right now during an update we download and parse complete manifests for all bundles on our system for both the `from` and `to` versions. We need the `from` manifests so we can figure out which files on the system we can apply our deltas against and we need the `to` manifests so we have a list of files we need to actually update.

Out of the `from` manifests we only need the few lines that we have deltas for. We need these lines because at delta application time we only know the `from` hash, not the `from` filename. We need the `from` filename in order to know which file on the filesystem we need to apply our delta to. This means we are downloading and parsing much more than we need for the `from` version.

Out of the `to` manifests we only need the lines that are relevant for our update from version `X` to version `Y`. Assume the common case of a system with autoupdate on consuming an update of a single version jump. This means that the `previous` of `Y` is `X` and the only files we need from the `to` manifest are the ones at the very bottom that changed in version `Y` (manifests are sorted by ascending version, with latest changes at the bottom). This means we download and parse a ton of data we end up throwing away.

Some analysis over the last few updates of Clear Linux show that most bundle manifests are at least as large as their packs. This will of course vary with the size of the actual update.

# proposal

We create (in [mixer](https://github.com/clearlinux/mixer-tools)) and consume iterative manifests. This means different things for the `from` and `to` manifests.

## from manifests

In `mixer` packs are created by performing rename detection and linking files with changed content between two versions. Deltas are created for these files and are added to packs that define an update from version `X` to version `Y` (and more versions, I'll keep using `X` and `Y` here). Mixer could publish an iterative manifest for the `from` version, `X`, by recording which files from `X` are used as the `from` file in the `from`/`to` version pair for an individual delta file. The manifest would be included in the pack because it defines the deltas for that version upgrade (`X`->`Y`). The client could then download the pack to go from `X` to `Y` for that bundle and use that iterative manifest that only has exactly what the client needs. That means it will not need to download the full manifest (if it is missing from their state dir) and will only need to parse what is needed. This manifest does not need to be signed because it will not be used when applying files to the system. It will only be used to map `from` hashes to `from` filenames for delta application.

## to manifests

In addition to regular bundle manifests that contain the complete list of files for that bundle `mixer` could create an iterative manifest. This manifest will only contain the files that changed in the current version (`Y`). The client could use this manifest when updating from `X` to `Y` because the only information it needs from the `Y` manifest is the set of files that changed in `Y`. This means much smaller downloads and much less parsing time. These iterative manifests would be added to the `MoM` with a different flag `I` instead of `M` indicating this is an iterative manifest.

## complete update

The update would then look like this:

* look in current Manifest.MoM for bundles that changed between `X` and `Y`.
* for each, attempt to download pack, if successful
    * use delta manifest in pack as the `from` manifest for that bundle
* download iterative manifest for `Y`, if `Y->previous` == `X`, use this manifest, else download full
* at this point, if everything is successful, the `X` manifest is just the set of from deltas we need and the `Y` manifest is the set of only the files we care about for this update. If unsuccessful we have the full manifests, and either way the update can continue as normal.

## work

We have to be smart about implementing this so we don't break clients.
1) verify that client won't break with `I` flagged manifests and won't allow users to `bundle-add` these as bundles.
2) do the actual work in mixer to create these things. This is not difficult.
3) actually optimize the client to use these manifests if available.

**Thoughts?**

**Comment by tmarcu** [comment]
:rocket: :+1: :100:

**Comment by matthewrsj** [comment]
Sorry, the delta `from` manifest is not signed because it is just used as a mapping of hash to filename of what's on the system for delta application. The delta will be attempted against that file (after the `from` hash is verified) and if successful the result will be placed into `statedir/staged` (to file also verified at this point). The incremental `to` manifest is signed implicitly and before moving files from `statedir/staged` onto the filesystem that file will be verified again.

**Comment by icarus-sparry** [comment]
So the proposal is to have 2 incremental manifests, a "from-12340-12350" and a "to-12340-12350" that will both be put in the "pack-12340-12350"? I was thinking that the suggestion was to just have this information in a single file (which I would want signed to avoid the attack I outlined).

If the "from" manifest is not signed then I believe there is still an attack possible, although it would now need to be a preimage attack. Essentially put a file, e.g. /tmp/wibble on the system, which can have any signature, say H1. Wait for the CDN to get an update say for /bin/sleep which has a hash of H2. create a delta of the attack program and /tmp/wibble that is preimaged to have a hash of H2. Replace the delta inside the pack on the CDN.

Currently the best publically known preimage attacks against SHA2 are not good enough for this to be an actual issue, but since we can avoid the potential future problem we should do so.

**Comment by matthewrsj** [comment]
> So the proposal is to have 2 incremental manifests, a "from-12340-12350" and a "to-12340-12350" that will both be put in the "pack-12340-12350"?

No, the proposal is to have one manifest in the pack that is just the list of files used for creating deltas. Another `Manifest.<bundlename>.i` will be published along with the other manifests and recorded in the MoM. This manifest only contains the files that were changed in that version, and none of the files that were changed before the current version. This manifest is available for download like any other manifest, it is not included in any pack because it only describes the current version.

The attack you describe won't work as I understand it. The unsigned manifest (which is just a list of from delta files) is only used to map the old hash to the old file name so we don't have to load all file records available on the client at the `from` version. The incremental manifest is no different from the full manifest except that it doesn't list old files. All files being put on the filesystem will be verified just like always.

Remember the result of applying a delta to a file on the filesystem is checked against the hash in the manifest (the one listed in the MoM for the version the client is updating to). If that hash doesn't match the file will be deleted and a fullfile will be downloaded instead (and once again verified against the manfest).

**Comment by matthewrsj** [comment]
## visual aids
### current state
![img_3420](https://user-images.githubusercontent.com/12090084/42065605-c2abbb3a-7af0-11e8-945e-86b6b24275e3.jpg)
### proposed delta and iterative manifests
Ignore the "CURRENT" at the top.
![img_3421](https://user-images.githubusercontent.com/12090084/42065606-c2c9645a-7af0-11e8-8db6-e53469b4f5ea.jpg)
### order of work
![img_3422](https://user-images.githubusercontent.com/12090084/42065607-c2dfa0f8-7af0-11e8-9ead-7db8b4f47c96.jpg)

**Comment by cmarcelo** [comment]
> Thoughts?

If I understood correctly the proposed solutions optimize for performing the update without any Manifests (for X and Y) already download. But I think in the regular operation, the current (X, from) manifests should be around. If they are not, swupd could just download them. Is that assumption wrong?

With that assumption in mind, one alternative would be ship the delta of the manifest (not a new kind of manifest) as part of the corresponding packs. The result of the delta can be verified with the TO/Y MoM. This would attack the "TO/Y manifest download problem". (I think this sort of thing even existed in the past but wasn't used).

The other problem seems to be efficiency finding out files for deltas. There are some low hanging fruit in swupd-client code to make it better. If that is not sufficient, shipping a mapping from hash->file should be fine.

**Comment by matthewrsj** [comment]
> The other problem seems to be efficiency finding out files for deltas. There are some low hanging fruit in swupd-client code to make it better.

Ok, but you would still have to read the entire from manifests and hold that information in memory. With the partial from manifests we only have the files we actually care about.

> If that is not sufficient, shipping a mapping from hash->file should be fine.

That's essentially what the partial from manifests are. They are kept in the same format as regular manifests to simplify parsing.

**Comment by cmarcelo** [comment]
> Ok, but you would still have to read the entire from manifests and hold that information in memory. With the partial from manifests we only have the files we actually care about.

Is the reading of that file(s) the bottleneck? There are a few tricks we can pull to improve things here before we have to ship more data. That said, as I mentioned I think shipping such mapping should be OK.

> That's essentially what the partial from manifests are. They are kept in the same format as regular manifests to simplify parsing.

Mixed feelings. On one hand I agree for the reason you said. On the other hand they are different since: (a) most of the fields are not relevant, (b) it will not be verifiable via the hash, so we'll be in a state that "some manifests we trust and others don't"; which make me think better just call it something else.

**Comment by matthewrsj** [comment]
> most of the fields are not relevant

well it simplifies things. 

> it will not be verifiable via the hash

The result of the delta application will be verifiable via hash.


> which make me think better just call it something else

I don't mind calling it something different but the naming will only exist in the code (and when we talk about it here) since this is just an internally-used file.

**Comment by cmarcelo** [comment]
> The result of the delta application will be verifiable via hash.

I understand that. I was referring to the manifest fragment itself.

You haven't comment on the first part of the alternative: instead of adding new entries to MoM (for the iterative manifests), assume previous version bundle Manifest will be there and ship a delta for it (falling back to download the previous, of course). Does that seem reasonable?

**Comment by matthewrsj** [comment]
ah, well because it will result in parsing and searching the entire 'from' manifest when it has a ton of entries we don't need. With the manifest fragment (nice name) it *only* has the entries we will actually care about for that pack. Much quicker to find the relevant files.

**Comment by cmarcelo** [comment]
> ah, well because it will result in parsing and searching the entire 'from' manifest when it has a ton of entries we don't need. With the manifest fragment (nice name) it only has the entries we will actually care about for that pack. Much quicker to find the relevant files.

You could just skip the entries with version greater than the "previous/from" and achieve a similar effect. Needs to check what is the slow part in the pipeline and fix it. To clarify my suggestions:

(a) "Find the right delta files": improve current code to get them from the manifest. If that's not enough ship the fragments in the delta packs.

(b) "Find new files to write to disk": ship the delta between old and new manifest. Verify it against the hash for that Manifest in MoM when applying. Improve current code to do less work we don't care about when parsing.

The trade-off in (b) is: use the delta mechanism and get a complete manifest, and no extra data is added to MoM, assumes previous manifest around; or let's add a fragment that has exactly the data we need (no further work), and add more entries in MoM to validate it, no previous manifest needed.

In the end seems to boil down to: can we compute this efficiently in the client, or add more preprocessed (redundant) data to the repo so client don't need to do work.

**Comment by jmb82** [comment]
Are we at a point where we could close this issue?

**Comment by matthewrsj** [comment]
I'd wait until the feature actually hits master before closing.

**Comment by otaviobp** [comment]
Reevaluate this proposal:
 - Compare Delta Manifest size with the I/D Manifests
 - Check any performance improvements
