### ISSUE TITLE
swupd calling cbm in a container

### ISSUE THREAD

**Issue by nesiusra** [clearlinux/swupd-client#500]
From mailing list...

From: Nesius, Robert A
Sent: Sunday, June 24, 2018 1:45 AM
To: VanCutsem, Geoffroy <geoffroy.vancutsem@intel.com>
Cc: Marcu, Tudor <tudor.marcu@intel.com>; Johnson, Matthew
<matthew.johnson@intel.com>; dev@lists.clearlinux.org
Subject: Re: [Clr-dev] Couple of questions regarding Clear Linux container
[Rob] The bundle-add behavior has not changed. It never updated while adding a
bundle.

[Geoffroy] OK, I don't know how I got that into my mind then. Thanks for the confirmation.

[Rob] I don’t think swupd should be calling out to clear boot manager in this case?

[Geoffroy] I don't know if swupd is supposed to detect when running in a container environment automatically but I remember Miguel pointed out the 'systemd-detect-virt' tool to the ACRN team. That tools does not work correctly for me however. If I run it inside a Clear Linux container, it reports "none" (I see the exact same behaviour from within a Fedora-based container by the way).

-Rob
Sent from mobile device.
> On Jun 23, 2018, at 4:27 PM, VanCutsem, Geoffroy
<geoffroy.vancutsem@intel.com> wrote:
>
>
>
>> -----Original Message-----
>> From: Marcu, Tudor
>> Sent: Friday, June 22, 2018 1:33 AM
>> To: VanCutsem, Geoffroy <geoffroy.vancutsem@intel.com>; Johnson,
>> Matthew <matthew.johnson@intel.com>; dev@lists.clearlinux.org
>> Subject: RE: Couple of questions regarding Clear Linux container
>>
>>> -----Original Message-----
>>> From: Dev [mailto:dev-bounces@lists.clearlinux.org] On Behalf Of
>>> VanCutsem, Geoffroy
>>> Sent: Thursday, June 21, 2018 4:10 PM
>>> To: Johnson, Matthew <matthew.johnson@intel.com>;
>>> dev@lists.clearlinux.org
>>> Subject: Re: [Clr-dev] Couple of questions regarding Clear Linux
>>> container
>>>
>>>
>>>
>>>> -----Original Message-----
>>>> From: Johnson, Matthew
>>>> Sent: Thursday, June 21, 2018 7:05 PM
>>>> To: VanCutsem, Geoffroy <geoffroy.vancutsem@intel.com>;
>>>> dev@lists.clearlinux.org
>>>> Subject: RE: Couple of questions regarding Clear Linux container
>>>>
>>>> Ah, I'm noticing this is run via Dockerfile, never mind the state dir bit.
>>>>
>>>> You are adding a *very* large bundle when you bundle-add os-clr-on-
clr.
>>>> William is right, the update should be first, not that the update
>>>> should fail in that case either, but you may be
>>>> downloading/installing much more than you expect you need.
>>>> os-clr-on-clr is 17 GB! Are you sure you have enough space for all that?
>>>
>>> I used to have a single line to add bundles in my Dockerfile (and no
>>> "swupd update" at all). My understanding was that the simple fact I
>>> was adding new bundles meant the whole system was going to be
>>> upgraded to the latest version. This new line was added as I was
>>> trying out different things as I was hitting this error. I'll re-run
>>> the test without the line to confirm I'm not lying :-
>>> )
>>>
>>
>> Adding bundles will not upgrade your system, only the update command
>> will do that. You can add every bundle one by one and your system
>> will remain on the version it's currently on, unless you update or
>> auto-update runs for you.
>
> Is that a new behaviour? I would have sworn that when I added a bundle in
the past, it used to upgrade my system to the latest version at the same time.
>
>>
>> I'm going to take a stab in the dark here, but do you know if you are
>> using overlay2?
>
> Yes, I'm using overlay2
>
>> Just to humor me, can you change your dockerfile from:
>>>>>   RUN swupd bundle-add os-clr-on-clr python3-basic
>>>>>   RUN swupd update
>>
>> To:
>>    RUN swupd bundle-add os-clr-on-clr python3-basic && swupd update
>>
>> (and any other swupd command all on the same 'RUN' line), and try
>> running that again?
>
> I will try that next (sorry, did not have time yet). What I had done before
you replied was to change the Dockerfile to do the update *before* adding
new bundles, i.e.:
>   RUN swupd update -b
>   RUN swupd bundle-add os-clr-on-clr python3-basic
>
> The update went fine but I still got this error at the end of the 'bundle-add'
step:
>   [ERROR] cbm (../src/lib/files.c:L165): Invalid block device: /
>   [ERROR] cbm (../src/lib/system_stub.c:L31): Invalid block device: 0:49
>   Out of memory[ERROR] cbm (../src/bootman/update.c:L255): No kernels
> discovered in ///usr/lib/kernel, bailing
>
> It proceeded though and finished building the container. I checked it after
that and ran a 'swupd verify' which found a hash mismatch for 54 files. I
fixed those using 'swupd verify -f' and it threw the same error again at the
end of the process but still said that the fix was successful:
>   [ERROR] cbm (../src/lib/files.c:L165): Invalid block device: /
>   [ERROR] cbm (../src/lib/system_stub.c:L31): Invalid block device: 0:49
>   Out of memory[ERROR] cbm (../src/bootman/update.c:L255): No kernels
discovered in ///usr/lib/kernel, bailing
>   Fix successful
>
> Which I confirmed by re-running 'swupd verify' which did not find any error
anymore. This latest container is 5.64GB in size.
>
> The full log of all these operations is attached to this mail if you want to
take a look.
>
>>
>>> What happened to the os-clr-on-clr bundle, has it recently exploded?
>>> I have an existing container (based on version 21150) that includes
>>> that bundle and is about 3.61GB in size.
>>>
>>> I have over 250GB of free space on my disk... I think that ought to
>>> suffice :-)
>>>
>>>> ________________________________________
>>>> From: Dev [dev-bounces@lists.clearlinux.org] on behalf of Johnson,
>>>> Matthew [matthew.johnson@intel.com]
>>>> Sent: Thursday, June 21, 2018 9:58 AM
>>>> To: VanCutsem, Geoffroy; dev@lists.clearlinux.org
>>>> Subject: Re: [Clr-dev] Couple of questions regarding Clear Linux
>>>> container
>>>>
>>>> Hmm, if you have plenty of disk space it could be a lot of other
>>>> reasons (looking at the source code). Can you try wiping your
>>>> statedir and trying again?
>>>>
>>>> I think at 3.15.0 you don't yet have the 'swupd clean' command, so
>>>> instead do 'rm -rf /var/lib/swupd' and try again.
>>>> ________________________________________
>>>> From: VanCutsem, Geoffroy
>>>> Sent: Thursday, June 21, 2018 9:48 AM
>>>> To: Johnson, Matthew; dev@lists.clearlinux.org
>>>> Subject: RE: Couple of questions regarding Clear Linux container
>>>>
>>>> Hi Matthew,
>>>>
>>>>> -----Original Message-----
>>>>> From: Johnson, Matthew
>>>>> Sent: Thursday, June 21, 2018 5:49 PM
>>>>> To: VanCutsem, Geoffroy <geoffroy.vancutsem@intel.com>;
>>>>> dev@lists.clearlinux.org
>>>>> Subject: RE: Couple of questions regarding Clear Linux container
>>>>>
>>>>> Hi Geoffroy,
>>>>>
>>>>> 1) yes, it is seeing 21520 as the latest in the format. On a
>>>>> successful update it will actually update you to 21520, then
>>>>> update you again to latest. Swupd clients are required to update
>>>>> to the format boundary before continuing to ensure compatibility
>>>>> with the new
>>>> format update manifests.
>>>>>
>>>>> 2) It actually looks like you are running out of disk space there
>>>>> because it is failing to stage a file. I know swupd doesn't do a
>>>>> great job of reporting out- of-disk errors and this is something
>>>>> the team is currently working on. The CBM errors themselves do not
>>>>> cause errors to be reported by swupd, so the swupd failure is due
>>>>> to swupd being unable
>>>> to stage that file.
>>>>
>>>> I have plenty of disk space on my machine. Do  you know what could
>>>> be causing this?
>>>>
>>>>>
>>>>> Publishing a more recent image would certainly help this case
>>>>> because the updates will be much smaller. The newest swupd version
>>>>> also does much more aggressive cache-cleaning so it doesn't bloat
>>>>> the
>>> system.
>>>>>
>>>>> Matthew
>>>>> ________________________________________
>>>>> From: Dev [dev-bounces@lists.clearlinux.org] on behalf of
>>>>> VanCutsem, Geoffroy [geoffroy.vancutsem@intel.com]
>>>>> Sent: Thursday, June 21, 2018 5:24 AM
>>>>> To: dev@lists.clearlinux.org
>>>>> Subject: [Clr-dev] Couple of questions regarding Clear Linux
>>>>> container
>>>>>
>>>>> Hi folks,
>>>>>
>>>>> I am building a Clear Linux-based container that includes some dev
>>>>> tools in
>>>> it.
>>>>> There is a couple of behaviours that puzzle me however:
>>>>> 1. The latest update it sees is 21520 (which is from end of March).
>>>>> Is this related to the format bump (from 24 in 21520 to 25 in
>>>>> 21530)? If true, can someone post a newer base container on Docker
>>>>> Hub so one can get the latest and greatest version of it?
>>>>> 2. When I build a container, include some additional bundles and
>>>>> update it, it fails to update the system (see more details below)
>>>>> unless I use
>>>> the "-b"
>>>>> option. I thought that swupd would automatically detect that it's
>>>>> running in a container. Is this not true (or is it only true for
>>>>> newer versions that are not available on Docker Hub)?
>>>>>
>>>>> Thanks,
>>>>> Geoffroy
>>>>>
>>>>> The Dockerfile is pretty basic and simply add a couple of bundles
>>>>> and then attempts to update the system.
>>>>>
>>>>> First lines of the Dockerfile:
>>>>>   # Build container based on Clearlinux
>>>>>   FROM clearlinux:base
>>>>>
>>>>>   RUN swupd bundle-add os-clr-on-clr python3-basic
>>>>>   RUN swupd update
>>>>>   <snip>
>>>>>
>>>>> When
>>>>>
>>>>> $ sudo docker build -t clearlinux -f Dockerfile.clearlinux .
>>>>> Sending build context to Docker daemon 177.7 kB Step 1/8 : FROM
>>>>> clearlinux:base  ---> cfe5f13b90b0 Step 2/8 : RUN swupd bundle-add
>>>>> os-clr- on-clr python3-basic  ---> Using cache  ---> 7bd1d6391ac4
>>>>> Step
>>>>> 3/8 : RUN swupd update  ---> Running in d271ffc27912
>>>>>
>>>>> swupd-client software update 3.15.0
>>>>>   Copyright (C) 2012-2018 Intel Corporation
>>>>>
>>>>> Update started.
>>>>> Attempting to download version string to memory Preparing to
>>>>> update from
>>>>> 21150 to 21520 Downloading packs...
>>>>> .
>>>>> Extracting go-basic pack for version 21420
>>>>>
>>>>> Extracting koji pack for version 21500
>>>>>
>>>>> Extracting kvm-host pack for version 21500
>>>>>
>>>>> Extracting libX11client pack for version 21500 .
>>>>> Extracting openssh-server pack for version 21330 .
>>>>> Extracting package-utils pack for version 21320
>>>>>
>>>>> Extracting perl-basic pack for version 21450
>>>>>
>>>>> Extracting perl-basic-dev pack for version 21510
>>>>>
>>>>> Extracting python2-basic pack for version 21510
>>>>>
>>>>> Extracting python3-basic pack for version 21360
>>>>>
>>>>> Extracting storage-utils pack for version 21360 .
>>>>> Extracting web-server-basic pack for version 21450
>>>>>
>>>>>
>>>>> Statistics for going from version 21150 to version 21520:
>>>>>
>>>>>    changed bundles   : 30
>>>>>    new bundles       : 0
>>>>>    deleted bundles   : 0
>>>>>
>>>>>    changed files     : 3410
>>>>>    new files         : 5329
>>>>>    deleted files     : 1658
>>>>>
>>>>> Starting download of remaining update content. This may take a
while...
>>>>>
>>>>> File /usr/bin/FileCheck was not in a pack
>>>>>
>>>>
>>
.....................................................................................................................
>>>>>
>>>>
>>
.....................................................................................................................
>>>>>
>>>>
>>
.....................................................................................................................
>>>>>
>>>>
>>
.....................................................................................................................
>>>>>
>>>>
>>
.....................................................................................................................
>>>>>
>>>>
>>
.....................................................................................................................
>>>>> ..........................Finishing download of update content...
>>>>>
>>>>> Staging file content
>>>>> File staging failed: /usr/include/clang/CrossTU Calling
>>>>> post-update helper scripts.
>>>>> none
>>>>> [ERROR] cbm (../src/lib/files.c:L165): Invalid block device: /
>>>>> [ERROR] cbm
>>>>> (../src/lib/system_stub.c:L31): Invalid block device: 0:75 Out of
>>>>> memory[ERROR] cbm (../src/bootman/update.c:L250): No kernels
>>>>> discovered in ///usr/lib/kernel, bailing Update took 279.9 seconds
>>>>> 4981 files were not in a pack
>>>>> The command '/bin/sh -c swupd update' returned a non-zero code: 18

**Comment by icarus-sparry** [comment]
My view is that swupd shouldn't attempt to detect if it is in a container, and so should call cbm in a consistent manner regardless of if it is in a container or not.

As to when it should call cbm, I see 2 choices, Either it should do so if any file with the 'b' attribute is changed, or it should always do so after any operation.

cbm should update the information on how to boot one of the current set of kernels. If it can't find any kernels then it would be reasonable for it to look to see if it is in a container and do nothing if it was, as opposed to screaming loudly if it is not a container and hence would expect there to be a kernel. This check could just look for a file, e.g. /usr/lib/kernel/NONE_NEEDED rather than jumping through a number of hoops to detect if it is a container or not.

**Comment by nesiusra** [comment]
Those are good points, @icarus-sparry.  Basically - make cbm fail gracefully so swupd-client doesn't have to care. Yeah?

**Comment by bryteise** [comment]
@icarus-sparry Hrm I'm inclined to move cbm into specific kernel bundles instead that expect to be updated with cbm. That doesn't resolve the in a container problem though if somebody adds a kernel to a container instance.

**Comment by icarus-sparry** [comment]
@bryteise Use cases that I can think of for adding a kernel to a container include using a container to create an image that will later be used to boot a system, perhaps via PXE or by writing it to a flash drive. So I don't think I would want to forbid adding kernels to containers even though it is a mistake most of the time.

It would be nice to decouple swupd and cbm, (perhaps using /etc/swupd/boot-manager if it exists rather than hard coding clr-boot-manager, which could be a symlink or a script to allow overrides). If we did this then we could also use /usr/share/defaults/swupd/boot-manager which wouldn't exist normally, but could be added by a "container package" to divert the flow away from cbm in a container.

@nesiusra Yes. I think I once heard that separation of responsibilities as being a good thing in software.

**Comment by gvancuts** [comment]
What is `cbm`? Is it an abbreviation for `clr-boot-manager`?

New data point (if that helps at all):
I put the `swupd bundle-add` and `swupd update` on the same line in my `Dockerfile`:
```
RUN swupd bundle-add -b os-clr-on-clr python3-basic && \
        swupd update -b
```
That resulted in **no** error when building the container and it is at version 23240.

Doing a `swupd verify` indicated 4 files with a hash mismatch and fixing them (`swupd verify -f`) actually triggered the error - see below:
```
root@37dbf61bb7a5 /root/acrn # swupd info
Installed version: 23240
Version URL:       https://download.clearlinux.org/update/
Content URL:       https://cdn.download.clearlinux.org/update/
root@37dbf61bb7a5 /root/acrn # swupd verify
Verifying version 23240
Verifying files
	...46%Hash mismatch for file: /usr/lib/python3.6/site-packages/pip/_internal/operations/__pycache__/__init__.cpython-36.pyc
Hash mismatch for file: /usr/lib/python3.6/site-packages/pip/_internal/utils/__pycache__/__init__.cpython-36.pyc
Hash mismatch for file: /usr/lib/python3.6/site-packages/pip/_vendor/urllib3/contrib/__pycache__/__init__.cpython-36.pyc
Hash mismatch for file: /usr/lib/python3.6/site-packages/pip/_vendor/urllib3/packages/backports/__pycache__/__init__.cpython-36.pyc
	...100%
Inspected 139400 files
  4 files did not match
Verify successful
root@37dbf61bb7a5 /root/acrn # swupd verify -f
Verifying version 23240
Verifying files
	...100%
Starting download of remaining update content. This may take a while...
	...100%
Finishing download of update content...
Adding any missing files

Fixing modified files
	...46%Hash mismatch for file: /usr/lib/python3.6/site-packages/pip/_internal/operations/__pycache__/__init__.cpython-36.pyc
	fixed
Hash mismatch for file: /usr/lib/python3.6/site-packages/pip/_internal/utils/__pycache__/__init__.cpython-36.pyc
	fixed
Hash mismatch for file: /usr/lib/python3.6/site-packages/pip/_vendor/urllib3/contrib/__pycache__/__init__.cpython-36.pyc
	fixed
Hash mismatch for file: /usr/lib/python3.6/site-packages/pip/_vendor/urllib3/packages/backports/__pycache__/__init__.cpython-36.pyc
	fixed
	...100%
Inspected 139400 files
  0 files were missing
  4 files did not match
    4 of 4 files were fixed
    0 of 4 files were not fixed
  0 files found which should be deleted
Calling post-update helper scripts.
none
[ERROR] cbm (../src/lib/files.c:L165): Invalid block device: /
[ERROR] cbm (../src/lib/system_stub.c:L31): Invalid block device: 0:49
Out of memory[ERROR] cbm (../src/bootman/update.c:L255): No kernels discovered in ///usr/lib/kernel, bailing
Fix successful
```

**Comment by icarus-sparry** [comment]
@gvancuts Yes, cbm is an abbreviation for clr-boot-manager (helpful for those of us who can't remember if it is clear-boot-manager or clr-boot-manager). 

In general the support for `.pyc` files is a bit lacking. These are cached results of compiling python code. If these files are writable, and in particular if you are running a python program as `root`, then these can get updated. This of course makes swupd notice that they have been altered. If we don't ship the `.pyc` files then the programs run slower as the files have to be compiled into their intermediate form each time.

The `error` you are seeing is coming from cbm which is being called by `swupd` as part of the post fixup cleanup. No help to you of course, but swupd did `fix` the pyc files so hopefully a second `swupd verify` would report nothing wrong, unless as part of the fixup some python programs ran and updated those same `.pyc` files again.

**Comment by gvancuts** [comment]
Thanks for the explanation @icarus-sparry .

Do you believe that all the `cbm` errors are due to it running inside a container (inc. the OOM one)?
```
[ERROR] cbm (../src/lib/files.c:L165): Invalid block device: /
[ERROR] cbm (../src/lib/system_stub.c:L31): Invalid block device: 0:49
Out of memory[ERROR] cbm (../src/bootman/update.c:L255): No kernels discovered in ///usr/lib/kernel, bailing
```

**Comment by icarus-sparry** [comment]
@gvancuts Yes, I believe it is cbm running in a container that is causing the issue. It is usual not to have kernels inside containers ([kata containers](https://katacontainers.io/) being an obvious exception, but there are other cases) but I suspect that this wasn't considered when cbm was being written.

**Comment by bryteise** [comment]
Finally coming back to this, sorry X(.

@icarus-sparry I'm not super worried about the use case. I don't want to prohibit containers from being able to do valid swupd actions since that seems overly finicky.

That said these are non-fatal error messages that would only appear when a kernel is installed on the system or when running a verify --fix as cbm would otherwise not be run so I'm not really convinced about how important of an issue this is as it is confusing rather than breaking. Moving cbm to kernel bundles avoids confusion in all cases but the kernel installed in container use case but even that I'm not particularly bothered about.

Being able to override the boot management program is a great idea.

The actual issue though isn't related to cbm: File staging failed: /usr/include/clang/CrossTU when os-clr-on-clr is installed prior to the update and that's what this bug I think should be dealing with, though @gvancuts was able to work around the problem.

**Comment by bryteise** [comment]
@otaviobp This is resolved in the latest docker images with an updated clr-boot-manager.

**Comment by otaviobp** [comment]
Issue closed on cbm.
