### ISSUE TITLE
Use address sanitizer on Travis to detect invalid memory usage and leaks introduced in new commits

### ISSUE THREAD

**Issue by otaviobp** [clearlinux/swupd-client#503]
We could use ASAN to check for memory errors when running tests in Travis by adding the following flags to CFLAGS:

    -fsanitize=address  -fno-omit-frame-pointer

And to print a full stack, I usually set this too:

    ASAN_OPTIONS=fast_unwind_on_malloc=0

**Comment by matthewrsj** [comment]
+1

**Comment by otaviobp** [comment]
This was fixed by PR #555
