### ISSUE TITLE
Signed updates

### ISSUE THREAD

**Issue by aaronovz1** [clearlinux/swupd-client#508]
Can someone explain what security features swupd has and how to use them? I did some brief looking and it seems like it is possible to do:

- Host key verification
- Signed updates

How do you enable host key verification?

For signed updates, it looks like I need to use "--enable-signature-verification" for swupd-client. What would I need to do in order to sign the updates? I am using the older swupd-server and found a pull request (https://github.com/clearlinux/swupd-server/pull/53) that says signing is now part of DevOps and there is some explanation in the mixer-tools repo. Can someone point me to that?

Thanks

**Comment by matthewrsj** [comment]
https://github.com/clearlinux/mixer-tools/blob/master/builder/builder.go#L368 for the mixer signing implementation and https://clearlinux.org/documentation/clear-linux/guides/maintenance/mixer provides the following information: 

> The CERT variable sets the path where mixer stores the Swupd_Root.pem certificate file. The chroot-builder needs the certificate file to sign the root Manifest.MoM file to provide security for content verification. The value of the CERT variable can point to a different certificate. The chroot-builder inserts the certificate specified in this value into the /os-core-update/usr/share/clear/update-ca/ path. The software update client uses this certificate to verify the Manifest.MoM file’s signature. For now, we strongly recommend that you do not modify this line, as the certificate that swupd expects needs to have a very specific configuration to sign and verify properly. Mixer automatically generates the certificate, if you do not provide the path to an existing one, and signs the Manifest.MoM file to provide security for the updated content you create.

Some more context from that document may be needed if you are unfamiliar with mixer.

**Comment by aaronovz1** [comment]
Still digging into this as I attempt to start maintaining meta-swupd. Can you clarify how the host key verification cert is set? The info you provided above is for signing/verifying Manifest.MoM. I can see in curl.c there is a capath variable:
https://github.com/clearlinux/swupd-client/blob/6c03e883f34ce710c4ad3cc8d145047313da6fa3/src/curl.c#L52
But I'm failing to see where/how that is set.
There is code that tries to use it but it seems like that code will *never* execute:
https://github.com/clearlinux/swupd-client/blob/6c03e883f34ce710c4ad3cc8d145047313da6fa3/src/curl.c#L511
https://github.com/clearlinux/swupd-client/blob/6c03e883f34ce710c4ad3cc8d145047313da6fa3/src/curl.c#L232

Maybe it was meant to be removed when --with-fallback-capaths was added?

**Comment by otaviobp** [comment]
capath is only set when using  --with-fallback-capaths and if we fail to use standard capaths. If you aren't using this flag CURLOPT_CAPATH won't be set and curl will use default CA path. This is checked on:

https://github.com/clearlinux/swupd-client/blob/48a016f001d5213a48f3ac0a5f51491ee5336f10/src/curl.c#L164

And tested on the following tests:

 - update/update-client-certificate.bats
 - bundleremove/remove-client-certificate.bats
 - bundleadd/add-client-certificate.bats
 - verify/verify-client-certificate.bats
 - checkupdate/chk-update-client-certificate.bats
 - search/search-client-certificate.bats
 - bundlelist/list-client-certificate.bats
