### ISSUE TITLE
Update of dev build not supported

### ISSUE THREAD

**Issue by aaronovz1** [clearlinux/swupd-client#513]
Can someone explain the message "Update of dev build not supported"? We are using SWUpd under Yocto environment and just bumped our OS version to 9 in our development environment. Systems on version 8 now report this message and can't update to 9. What is the significance of SWUPD_VERSION_IS_DEVEL and SWUPD_VERSION_IS_RESVD? It seems kind of odd that we can update fine for versions 1 to 8 but 8 -> 9 and 9 -> 10 are prevented by the check: https://github.com/clearlinux/swupd-client/blob/82a88d30a8770bc1ccaf4e9d5130b97ec7a6b225/src/version.c#L165

**Comment by matthewrsj** [comment]
Ah, this is a holdover from when Clear Linux anticipated using those versions for development purposes. This did not happen and those checks may be removed.

**Comment by matthewrsj** [comment]
Fixed by #514
