### ISSUE TITLE
autoupdate does not support --path option

### ISSUE THREAD

**Issue by mdhorn** [clearlinux/swupd-client#527]
## Problem
`swupd autoupdate` does not accept the `--path=<rootdir>` option like other swupd subcommands: bundle-add, bundle-remove, bundle-list, hashdump, update, verify, check-update, and search. This limits the use of the command to the currently running system.

There is a workaround of using `systemctl` directly, but it would be cleaner to only use the swupd command for consistency and in case systemctl is changed or replaced.

## Use Case
The Clear Linux OS Installer relies on `swupd` for initialization and software installation.

### Enable
`/usr/bin/systemctl --root=<rootdir> unmask --now swupd-update.service swupd-update.timer
`
### Disable
`/usr/bin/systemctl --root=<rootdir> mask --now swupd-update.service swupd-update.timer
`

**Comment by matthewrsj** [comment]
+1 to the feature, but does this mean you are providing installer users a way to install swupd with autoupdate turned off?

**Comment by mdhorn** [comment]
@matthewrsj Yes, this has been a long-standing request for the existing installer; being implemented in the new installer. It will be an advanced option, not in the "standard" installation flow choices. It also comes with a heavy warning about disabling.
This is also why I've submitted an additional issue to create a MOTD Warning when it is disabled; #529

**Comment by matthewrsj** [comment]
Classifying this as an enhancement, but I'll note that --path not being supported on this one subcommand is an inconsistency from the rest of the subcommands at the least.

**Comment by otaviobp** [comment]
Depends on #571
