### ISSUE TITLE
Feature request: swupd bundle-list could show bundle size before user install it 

### ISSUE THREAD

**Issue by alekdu** [clearlinux/swupd-client#530]
People may need this information to judge if he really wants to add this bundle. it would be too late if user find disk space is out.

**Comment by tripzero** [comment]
+1.  Just booted up my mixer image to find out 10/10gb are used.  But what is taking up the space?  There's nothing in swupd that helps it seems and I have deduce from file system folder sizes.

**Comment by castulo** [comment]
This information will be provided by the `swupd bundle-info` command proposed in #1079. However the bundle size that will be shown is only an approximation, the maximum amount of space the bundle would take if installed.
