### ISSUE TITLE
feature request: swupd could show bundle file list before user install it

### ISSUE THREAD

**Issue by alekdu** [clearlinux/swupd-client#531]
This sounds like a "dpkg -L" equivalent for Clear Linux. People love to know what's going to add into his system at file level.

**Comment by probonopd** [comment]
I second this. I would like to know what bundle-add is about to install to my system, before committing to it. Also, show how much space it will take.

**Comment by eero-t** [comment]
It should also list what additional bundles get installed, but should it show also what files get installed by those?

(With a slow console, and huge enough number of files, user could be staring at the console output for many minutes before the operations actually starts, so I would say no.)

**Comment by castulo** [comment]
The list of files included in a bundle along with the size it will take the installed (approximately) will be shown by the `swupd bundle-info` command proposed at #1079
