### ISSUE TITLE
'swupd search at' dies by OOM

### ISSUE THREAD

**Issue by vcgomes** [clearlinux/swupd-client#556]
On a KVM Guest image with 1G memory allocated to it (i.e. using the provided [start_qemu.sh](https://download.clearlinux.org/image/start_qemu.sh) script), running:
```
swupd search at
```

Results in something like:
```
Searching for 'at'

[  684.567825] Out of memory: Kill process 633 (swupd) score 919 or sacrifice child
[  684.568720] Killed process 633 (swupd) total-vm:1023276kB, anon-rss:934916kB, file-rss:0kB, shmem-rss:0kB
Killed
```

This is on Clear version 24650.

**Comment by phmccarty** [comment]
Thanks for the report.

Looks like swupd requires about 1.5GB of memory to run `swupd search at`, where it finds 380056 results spanning 192 bundles. In contrast, running `swupd search foobar` finds 6 results spanning 3 bundles and only requires 32MB of memory. A more extreme example: `swupd search e` uses over 6.8GB of memory and finds 1723624 results across 226 bundles.

This is an artifact of how swupd search is currently implemented. There are plans to modify the implementation to not require that all manifests be loaded into memory (#394), which helps a bit. But your report highlights that we should rethink how swupd tracks the search results as well.

**Comment by vcgomes** [comment]
This issue picked my interested mainly because the relation between the memory usage and the number of results (~4K for each result), the end result is the #559 PR, it's just a quick fix.

Taking a quick look, (and sorry for the intrusion) a first idea would be to mmap() the manifest files and just make the "filenames" point to parts of that mmap()'ed region. But it would take a lot more work.
