### ISSUE TITLE
Parallel downloads is broken for large files

### ISSUE THREAD

**Issue by otaviobp** [clearlinux/swupd-client#562]
When swupd is downloading large files in parallel and one package is taking to long to be extracted, downloads can get timed out and operation fails.

This bug was introduced on 3.17.13.

Subtasks:
 - Perform downloads in parallel using multiple threads
 - Create a command line option to control the number of simultaneous downloads so we can have a fallback if the parallel download fails for some other reason

**Comment by evil-brain** [comment]
Otavio and I had a quick discussion about how to do this.

Downloads are already handled by curl_mutli - so items are already downloaded in parallel.

Decompression is what we're going to be threading. This basically means we will enqueue work to a threadpool and return immediately in the curl callback. This will necessitate an extra check for errors from each thread, and retry if something fails.

By running decompression in threads, swupd will spend less time waiting, and this will prevent curl from timing out.

**Comment by otaviobp** [comment]
fixed by #767
