### ISSUE TITLE
Print the download speed and download size

### ISSUE THREAD

**Issue by mbelluzzo** [clearlinux/swupd-client#576]
I have being noticing some very slow updates lately, but without this information it makes it harder to figure out what is really going on: its my connection? its just a larger update?

Update took 2370.5 seconds
36569 files were not in a pack
Update successful. System updated from version 24440 to version 25080

Printing those values would help users to figure out network problems happening between their machines and our CDN instead of just giving the impression that our updates are insanely slow.

**Comment by matthewrsj** [comment]
For now you can pass -t to see where the time is spent

**Comment by aaronovz1** [comment]
I requested a similar improvement here: https://github.com/clearlinux/swupd-client/issues/271

**Comment by bryteise** [comment]
The amount of file not in a pack is pretty large and I expect that to heavily influence update time (and has historically been very predictive of longer updates for me).

**Comment by matthewrsj** [comment]
I believe a minversion was just released which causes swupd to validate all content on the system.  You are also updating from outside the bounds of Delta packs being created (devops only goes 10 back for creating those)

**Comment by mbelluzzo** [comment]
I think that is important to point here that I'm not questioning if the
update was supposed to be large and slow or not. Is just that we don't
provide enough output to distinguish between larger jumps from poor
connection speeds.

**Comment by matthewrsj** [comment]
See my first suggestion for now to pass the -t flag to see timing details. I'm closing this in favor of #271 for the specific feature request

**Comment by mbelluzzo** [comment]
@matthewrsj #271 doesn't talk about printing the download speed, only the side. So it can be everything on one ticket. But it needs to be clear that only download size isn't that helpful. (even that is 'live', because nobody will be doing math while watching the byte count goes up over time).

**Comment by matthewrsj** [comment]
I don't see it as swupd's responsibility to report the client's network speed as part of normal output. Maybe as a more debug style output (with -t). It makes much more sense to report download size because this is the size of the update being consumed. 

If you would like speed to be considered as well feel free to add the request to the original issue. If we were to add download speed to the output it would be done hand-in-hand with reporting size.

**Comment by otaviobp** [comment]
> I don't see it as swupd's responsibility to report the client's network speed as part of normal output. Maybe as a more debug style output (with -t). It makes much more sense to report download size because this is the size of the update being consumed.

Commands that download files usually report the current download speed, current and total download size and progress. I think that this information is important to help users to find why updates are taking longer than expected.

I like the way Archlinux package manager (pacman) reports status and I think we could have a progress bar similar to it:

    :: Synchronizing package databases...
     core                                               134.3 KiB  3.54M/s 00:00 [###########################################] 100%
     extra                                             1636.6 KiB  4.27M/s 00:00 [###########################################] 100%
     Community                                         1559.7 KiB  2.54M/s 00:01 [##############-----------------------------]  33%
I

**Comment by mbelluzzo** [comment]
The idea of not being swupd responsibility is, at least, silly. We aim and advertise about being a smart update system that is fast and efficient, to output information that proofs those points to the end user should be shouldn't be "debug mode" but standard information.
