### ISSUE TITLE
Verbose Timing for update.c Captures Incorrect/Redundant Information

### ISSUE THREAD

**Issue by jwakre** [clearlinux/swupd-client#584]
When updating with the '-t' argument, swupd outputs timing statistics for the update. The following timing blocks in update.c look incorrect or redundant:

1. "Main Update":
This seems redundant because the block of code that it captures for timing statistics is nearly identical to "Update Step 1: get versions".

2. "Load Manifests":
This only captures the time that it takes to load the current MoM. I think the time to load the server MoM should also be included in this time block.

3. "Recurse and Consolidate Manifests":
This time block captures the time to load the server MoM, recurse/consolidate current subscribed manifests, and recurse/consolidate server subscribed manifests. I think this time block should not include loading the server MoM.

**Comment by matthewrsj** [comment]
I'm fine with changes being made to titling of time blocks, but we need to make sure all operations are captured so it is as close to actual run-time as possible.
> I think this time block should not include loading the server MoM.

That's fine as long as *some* time block includes it.

**Comment by jwakre** [comment]
I plan to move loading the server MoM from "Recurse and Consolidate Manifests" to "Load Manifests", so everything should sill be captured. I care about these time blocks because they impact the Delta Manifests PR. I am not sure about the intent of "Main Update", so I am fine leaving this as is.

**Comment by castulo** [comment]
I also saw this when working on the iterative manifests, looks like the code from the update has been changing but nobody has been re-arranging the grabtime statements.

**Comment by castulo** [comment]
🚫 Blocked until the iterative/delta manifest branch merges.

**Comment by castulo** [comment]
We no longe know if/when the iterative/delta manifests code is gonna merge. So I'm fixing the update time output now, and we can rebase/fix that in the iterative/delta update code if it comes to that.
