### ISSUE TITLE
"swupd verify" and "swupd verify --fix" have different opinions

### ISSUE THREAD

**Issue by cmarcelo** [clearlinux/swupd-client#607]
While debugging https://github.com/clearlinux/distribution/issues/206, I've found this:

```
$ sudo swupd verify 
Verifying version 25470
Verifying files
	...100%
Inspected 407142 files
Verify successful

$ sudo swupd verify --fix
Verifying version 25470
Verifying files
	...100%
Starting download of remaining update content. This may take a while...
	...100%
Finishing download of update content...
Adding any missing files

Fixing modified files
	...100%
Couldn't remove directory containing untracked files: /usr/local/bin
Inspected 407142 files
  0 files were missing
  1 files found which should be deleted
    0 of 1 files were deleted
    1 of 1 files were not deleted
Calling post-update helper scripts.
none
Error: Fix did not fully succeed
```

Maybe the output of the commands need a better description, but I'd guess that if `swupd verify` is happy, then `swupd verify --fix` would have nothing to fix.

**Comment by cmarcelo** [comment]
To be clear: the issue here (bug or, maybe a feature) is the fact that a verify and a fix disagree whether the system is good.

**Comment by otaviobp** [comment]
This is a bug. Swupd fix should be a dry-run for swupd verify --fix

**Comment by phmccarty** [comment]
Related feature request: https://github.com/clearlinux/swupd-client/issues/536

**Comment by castulo** [comment]
one thing I find strange is that the results from "swupd verify --fix" shown above, are trying to remove files even when the "--picky" option was not used. As far as I know verify should only attempt to remove files if "--fix --picky" are used together.

**Comment by phmccarty** [comment]
@castulo `verify --fix` will delete files if they are marked deleted in manifests for all bundles that are installed. `verify --fix --picky` will delete extra files (i.e. files not listed in any manifest), as you mention.
