### ISSUE TITLE
"swupd verify --fix --picky -m <ver>" fails if a bundle doesn't exist in <ver>

### ISSUE THREAD

**Issue by bktan8** [clearlinux/swupd-client#608]
I was at Clear ver 25180.  This was when the zstd bundle was introduced into my system.  I tried to "swupd verify --fix --picky -m 24180" and it failed because zstd didn't exist back then.  swupd gave a warning that the bundle is invalid and "skipping it...", errored out, and stopped.

The workaround was to manually delete the offending bundle(s) in /usr/share/clear/bundles/ and retry "swupd verify --fix --picky...".  This is what I think swupd should do automatically.

**Comment by phmccarty** [comment]
Maybe an option can be used to force the downgrade in this case?

You can imagine this situation happening for a series of builds:

1. User is on build 1000
2. A new bundle is added in 1010
3. User updates to 1010 and installs the new bundle
4. A new bundle is added in 1020
5. User updates to 1020 and installs the new bundle
6. etc

Then the `swupd verify --fix --picky -m VER` trick won't ever work when trying to downgrade from 1010 to 1000, or from 1020 to 1010 or 1000; it would only work in the forward direction.

**Comment by otaviobp** [comment]
> Then the swupd verify --fix --picky -m VER trick won't ever work when trying to downgrade from 1010 to 1000, or from 1020 to 1010 or 1000; it would only work in the forward direction.

I prefer to print one message saying the the user needs to remove the bundle before proceeding instead of removing it myself.

**Comment by bktan8** [comment]
I think if someone is doing "swupd verify --fix --picky -m <ver>", I think they are knowingly choosing to wipe clean and go to <ver>.  Having the extra step of removing offending bundles is sort of pain.  But I also understand the need to be cautious and make user purposely delete offending bundles first and retry.  toss up.

**Comment by bktan8** [comment]
Can we print a warning that offending bundle(s) will be delete and ask user to press 'y' to proceed?  And if they add a "--force", then we don't ask the question?

**Comment by bktan8** [comment]
@otaviobp - My vote is for implementing "--force" instead of deleting individual bundles.  The problem with deleting individual bundles is that if they are dependent by other bundles, it a big mess to try an unravel.  Here's an example:

sudo swupd bundle-remove zstd x11-server package-builder
Removing bundle: zstd
Error: bundle requested to be removed is required by the following bundles:
format:
 # * is-required-by
 #   |-- is-required-by
 # * is-also-required-by
 # ...

  * mixer
    |-- os-clr-on-clr
Removing bundle: x11-server
Error: bundle requested to be removed is required by the following bundles:
format:
 # * is-required-by
 #   |-- is-required-by
 # * is-also-required-by
 # ...

  * desktop
    |-- desktop-autostart
Removing bundle: package-builder
Error: bundle requested to be removed is required by the following bundles:
format:
 # * is-required-by
 #   |-- is-required-by
 # * is-also-required-by
 # ...

  * os-clr-on-clr
Failed to remove 3 of 3 bundles
