### ISSUE TITLE
An invalid bundle name is still added to an image

### ISSUE THREAD

**Issue by bktan8** [clearlinux/swupd-client#609]
Even though the warning message says an invalid bundle is being skipped, the bundle name still shows up when you do "swupd bundle-list" for the created image.

Example:
clear@clr-da50329d227d4062bb2170a8b8162bd2 ~/mixer $ sudo -E mixer build image
Password:
Reading configuration
Validating configuration
Creating virtual disk
Creating partitions
Mapping loop device
Creating file systems
Setting up mount points
Starting swupd. May take several minutes
Installing 4 bundles (and dependencies)...
.
....................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
Verifying version 10
Warning: Bundle "BADBUNDLE" is invalid, skipping it...
Downloading packs...

STEPS TO REPRO:
1) Add an invalid bundle name to config json file.
2) Create an image
3) Boot up the image
4) swupd bundle-list and you can see the invalid bundle name

If swupd encounters an invalid bundle name, it should delete the invalid bundle name from /usr/share/clear/bundles.

**Comment by otaviobp** [comment]
This bug was fixed by other commit, so I'll close this ticket. @bktan8 if you are still seeing this error, feel free to reopen
