### ISSUE TITLE
Testlib.bash: Incorrect Delta Packs Generated 

### ISSUE THREAD

**Issue by jwakre** [clearlinux/swupd-client#615]
Currently, testlib.bash generates delta packs for a given bundle from its most recently changed version to the latest version. This is not correct because the current version may be older than a bundle's most recently changed version. For instance, if an update was performed from version 10 to version 30 and a bundle has been updated in versions 20 and 30, a delta pack will be generated for that bundle from version 20 to version 30. It is expected that a delta pack for that bundle should be generated for an update from version 10 to version 30.

**Comment by castulo** [comment]
so what I understand from this @jwakre is that the delta packs generated are not really incorrect, but rather some other delta packs are missing, isn't this correct?

**Comment by jwakre** [comment]
@castulo Yes, the contents of delta packs are not wrong, but there are some cases when the delta pack that is generated is not based on the current version, so it cannot be used by Swupd during the update.
