### ISSUE TITLE
Delta Manifests: Full manifest downloaded when no manifest (full or delta) required

### ISSUE THREAD

**Issue by jwakre** [clearlinux/swupd-client#616]
When a delta manifest is not necessary, mixer will not generate one. In this situation, when swupd looks for a delta manifest inside the delta pack it won't exist and a full manifest will be downloaded as a fallback which provides no useful information. Delta packs should include some information for swupd to identify FROM manifests that can be skipped when a delta manifest was intentionally omitted.

For example, if a subscribed bundle was updated to erase one file, mixer would not create a delta manifest.  Since no delta manifest exists, swupd would download the full manifest for that bundle and add all of its files to the FROM file list. The full manifest download adds no value to an update.

**Comment by otaviobp** [comment]
Updated https://github.com/clearlinux/mixer-tools/pull/411 adding a patch to generate empty Delta Manifests when no delta file is in a pack.

**Comment by jwakre** [comment]
@otaviobp The patch for empty Delta manifests was removed from #411 correct?

**Comment by otaviobp** [comment]
> @otaviobp The patch for empty Delta manifests was removed from #411 correct?

Yes, it was removed because of the discussion about having empty Manifests. I couldn't find my patch though. I though I have just added the code to the original commit
