### ISSUE TITLE
Error updating if bundles went missing from mix.

### ISSUE THREAD

**Issue by ahkok** [clearlinux/swupd-client#624]
Scenario:
- mix with bundle X
- remove X from mix
- swupd on client with bundle X installed
- swupd fails to update

```
# swupd update
Update started.
Preparing to update from 140 to 150
Warning: Bundle "xemacs" is invalid, skipping it...
Warning: Bundle "openssl" is invalid, skipping it...
Update took 0.2 seconds
# echo $?
14
```

This should probably continue, or print a really serious error message. Especially auto-updates should succeed at any cost...

**Comment by otaviobp** [comment]
I remember being told that we don't support removing bundles from mix shouldn't be allowed without a format bump. If this is really true, this is a bug in mixer.
@matthewrsj and @tmarcu, can you comment on that?

Anyway, adding a really serious message is something that we need in swupd. (or succeeding with comments saying that the bundle was removed.)

**Comment by matthewrsj** [comment]
I agree that removing bundles from your mix when not tied to a format bump is not supported in swupd/mixer **but** @ahkok is correct we should print the error and continue. We don't want to fail the update.

**Comment by otaviobp** [comment]
ok. So this is a bug.

What should be done in one update:
 - Warn the user that bundle X is being removed
 - Remove the bundle

**Comment by matthewrsj** [comment]
updating won't remove that bundle. It just won't update those specific files. Running verify --fix afterwards will remove the bundle and all files.
