### ISSUE TITLE
Documentation for swupd update options can enhance

### ISSUE THREAD

**Issue by LibertadCruz** [clearlinux/swupd-client#633]
As a new user probably the first thing it will do when deciding to learn how to use swupd is read the options in the menu and the description, to figure out how to use the swupd tool.  Then he will look for documentation.

The current documentation on swupd "https://clearlinux.org/documentation/clear-linux/guides/maintenance/swupd-guide" only holds the basic options for bundle adding, removing, checking version.  

I feel that we need to describe more on documentation some of the options of swupd update like
--format      It is not clear that it only allows me to go foward in formats not backwards until I try it and it says I cant.  
--certpath   Should there be a tutorial on how to create alternative certificates for swupd?
--statedir     On what point does a user decide to use a different state path? What kind of files and formats does the user need to create to use this different state directery?
--no-scripts    What do the post-update scripts do that will make a user be sure they did not run when using this option?

This I dont know how to use them or what to use them for.
swupd verify --help:

   -m, --manifest=M        Verify against manifest version M
   -p, --path=[PATH...]    Use [PATH...] as the path to verify (eg: a chroot or btrfs subvol
   -u, --url=[URL]         RFC-3986 encoded url for version string and content file downloads
   -P, --port=[port #]     Port number to connect to at the url for version string and content file downloads
   -c, --contenturl=[URL]  RFC-3986 encoded url for content file downloads
   -v, --versionurl=[URL]  RFC-3986 encoded url for version file downloads
   -X, --picky-tree=[PATH] Selects the sub-tree where --picky looks for extra files. Default: /usr
   -w, --picky-whitelist=[RE] Any path completely matching the POSIX extended regular expression is ignored by --picky. Matched directories get skipped. Example: /var|/etc/machine-id. Default: /usr/lib/modules|/usr/lib/kernel|/usr/local

**Comment by otaviobp** [comment]
The web documentation is a getting started guide to the command, so it should list only the basic options. According to the documentation "For a full listing of commands and options please see the man page in Clear Linux OS: man swupd" and the swupd manual is listing the options you described.

I agree not all flags are well documented and easy to understand, but at least they are documented in manual pages and under improvement. Bug #571 should make it easier to document them.
