### ISSUE TITLE
The --nosigcheck gives a confusing mesage

### ISSUE THREAD

**Issue by LibertadCruz** [clearlinux/swupd-client#634]
So, I ran
sudo swupd bundle-add --nosigcheck vim

Although the below message says the operation will proceed.  I did not expect to tell me it FAIL TO VERIFY SIGNATURE.  If I use the --nosigcheck why is it checking and failing?

Log snippet:
FAILED TO VERIFY SIGNATURE OF Manifest.MoM. Operation proceeding due to
  --nosigcheck, but system security may be compromised

**Comment by otaviobp** [comment]
I rechecked the documentation and according to the manual:

           · -n, --nosigcheck
                Do not attempt to enforce certificate or signature checking

We are checking the signature, but not enforcing it, so the message is correct. I'll close this issue then.
