### ISSUE TITLE
-D  under the bundle-add option is not being accepted

### ISSUE THREAD

**Issue by LibertadCruz** [clearlinux/swupd-client#635]
So, I ran:

sudo swupd bundle-add -D=2 vim
sudo swupd bundle-add -D=[2] vim

The ouput:

Invalid --max-parallel-downloads argument

**Comment by LibertadCruz** [comment]
hmmm, worked with 
sudo swupd bundle-add -D 2 vim

but also if I do the following it works:

 sudo swupd bundle-add -D 2.2 vim
Downloading packs...
        ...100%
Starting download of remaining update content. This may take a while...
        ...100%
Finishing download of update content...
Installing bundle(s) files...
        ...100%
Calling post-update helper scripts.
Successfully installed 1 bundle

**Comment by otaviobp** [comment]
> sudo swupd bundle-add -D 2.2 vim

If the max number of threads is 2.2 the number of threads we will use is 2 that is smaller than 2.2, which seams correct. Anyway, we use just the number prefix, so

    sudo swupd bundle-add -D 2abc vim

will also work.

**Comment by LibertadCruz** [comment]
Nice. But usually its a good practice to restrict the user into using options correctly. In this case using only integers.

**Comment by otaviobp** [comment]
Good point. We have a ticket for that #573. I'll add a comment about -D
