### ISSUE TITLE
Option --force in bundle-add doesn't do anything

### ISSUE THREAD

**Issue by castulo** [clearlinux/swupd-client#636]
bundle-add --help show the --force option but it doesn't really do anything for bundle-add, we should probably remove this option or change its description, there are probably no problems that are not critical when installing a bundle.

Usage:
   swupd bundle-add [options] [bundle1 bundle2 (...)]

Help Options:
   -h, --help              Show help options
   -u, --url=[URL]         RFC-3986 encoded url for version string and content file downloads
   -c, --contenturl=[URL]  RFC-3986 encoded url for content file downloads
   -v, --versionurl=[URL]  RFC-3986 encoded url for version string download
   -P, --port=[port #]        Port number to connect to at the url for version string and content file downloads
   -p, --path=[PATH...]    Use [PATH...] as the path to verify (eg: a chroot or btrfs subvol
   -F, --format=[staging,1,2,etc.]  the format suffix for version file downloads
   **-x, --force             Attempt to proceed even if non-critical errors found**
   -n, --nosigcheck        Do not attempt to enforce certificate or signature checking
   -I, --ignore-time       Ignore system/certificate time when validating signature
   -S, --statedir          Specify alternate swupd state directory
   -C, --certpath          Specify alternate path to swupd certificates
   -t, --time              Show verbose time output for swupd operations
   -N, --no-scripts        Do not run the post-update scripts and boot update tool
   -b, --no-boot-update    Do not update the boot files using clr-boot-manager
   -D, --max-parallel-downloads=[n] Set the maximum number of parallel downloads
   --skip-diskspace-check  Do not check free disk space before adding bundle

**Comment by castulo** [comment]
Now that I'm looking into this, looks like bundle-add, bundle-remove, update, check-update, and verify they all show --force as an option, but actually only verify uses it. I think we should remove it from everywhere where is not needed to avoid misleading people.
What do you think @otaviobp ?

**Comment by otaviobp** [comment]
Yes. Remove where it's not being used.
