### ISSUE TITLE
-t returns invalid option

### ISSUE THREAD

**Issue by reaganlo** [clearlinux/swupd-client#638]
The following swupd commands returns invalid option -- 't'
`bundle-list -t`
`check-update -t`
`hashdump`

Ideally it should return the elapsed time and CPU process time.

**Comment by otaviobp** [comment]
-t isn't supported by all swupd commands. In the list of flags for bundle-list, check-update and hashdump -t isn't listed. So this is not really a problem. And those commands aren't a target for optimization, so I don't see a reason to add a -t to them.

Closing this issue then.
