### ISSUE TITLE
bundle-list options available unclear

### ISSUE THREAD

**Issue by LibertadCruz** [clearlinux/swupd-client#645]
So, I try to use swupd bundle-list --help, thinking I would get a list of only available options for bundle-list. Instead I get optoins like -u, -c, -v, -p. Should those options be available under bundle-list? 

clrmixer@clrQA-mixer ~ $ swupd bundle-list --help
Usage:
   swupd bundle-list [options]

Help Options:
   -h, --help              Show help options
   -a, --all               List all available bundles for the current version of Clear Linux
   -u, --url=[URL]         RFC-3986 encoded url for version string and content file downloads
   -c, --contenturl=[URL]  RFC-3986 encoded url for content file downloads
   -v, --versionurl=[URL]  RFC-3986 encoded url for version string download
   -p, --path=[PATH...]    Use [PATH...] as the path to verify (eg: a chroot or btrfs subvol
   -F, --format=[staging,1,2,etc.]  the format suffix for version file downloads
   -n, --nosigcheck        Do not attempt to enforce certificate or signature checking
   -I, --ignore-time       Ignore system/certificate time when validating signature
   -S, --statedir          Specify alternate swupd state directory
   -C, --certpath          Specify alternate path to swupd certificates
   -d, --deps=[BUNDLE]     List bundles included by BUNDLE
   -D, --has-dep=[BUNDLE]  List dependency tree of all bundles which have BUNDLE as a dependency

**Comment by LibertadCruz** [comment]
Is swupd meant to pass Usability testing? Like if the CLI menu is very easy and understandable for any unfamiliar user to perform task?

**Comment by otaviobp** [comment]
swupd bundle-list --all uses the network so -u, -v and -c are expected.
swupd bundle-list lists packages installed on a system, so -p is important to list bundles from systems in different paths.

Swupd should be easy to use and we have some usabilities issues to fix. I created an issue to do an usability review in swupd to track major problems: https://github.com/clearlinux/swupd-client/issues/647
