### ISSUE TITLE
Review swupd usability

### ISSUE THREAD

**Issue by otaviobp** [clearlinux/swupd-client#647]
Users often complain about swupd UX in general. The major complaints are:
 - Output are redirected to both stderr and stdout and because of that I missed some logs (ister, for example, prints stdout before stderr and makes output very confusing)
 - Commands names are confusing (#250, #491, swupd verify to do a downgrade, swupd verify --picky/verify --fix --picky, among others)
 - Progress bars aren't clear (#622, #598, #433, #255)
 - Output message is hard to understand

**Comment by castulo** [comment]
yep, and this is important because the quality of the software is only as good as it is perceived to be by the user

**Comment by otaviobp** [comment]
Most items in this issue were fixed and the others have appropriate tickets that are being tracked. closing
