### ISSUE TITLE
swupd-client should support filenames with unusual characters...

### ISSUE THREAD

**Issue by bktan8** [clearlinux/swupd-client#671]
See https://github.com/clearlinux/mixer-tools/issues/494

Currently, mixer is blacklisting filenames with unusual characters.  But once mixer is able to handle them, I wonder how swupd-client will react to them.  This issue is a reminder to deal with this in the future.

**Comment by phmccarty** [comment]
Recently, mixer started to ban the control character `\a` in filenames, so that should be factored in to this feature.

See the commit added this PR: https://github.com/clearlinux/mixer-tools/pull/596

**Comment by otaviobp** [comment]
Fixed
