### ISSUE TITLE
Show information that a bundle is experimental in swupd operations

### ISSUE THREAD

**Issue by otaviobp** [clearlinux/swupd-client#676]
Prepend a '*' everytime we print the name of an experimental bundle.

Commands affected:
 - bundle-*
 - search

And in bundle-add, shows a warning saying that we are installing an experimental bundle.

Depends on: https://github.com/clearlinux/mixer-tools/issues/497

**Comment by castulo** [comment]
Update: 
We should have a header "status" in the bundle manifest
if _status: experimental_ then the  bundle is experimental
if there's no status or status != from experimental, it isn't experimental

**Comment by castulo** [comment]
Change of plans... having the _status: experimental_ in the header of each bundle's manifest would cause clients to have to download all the manifests only to figure out which ones are experimental. A much efficient approach is to have a new modifier in the MoM for that bundle.

Example:
`M..e 4b91c3122e7e32f1e3edb0a705a6168ca8e66f597c6f89ff32cfffd977afb5e5 10 test-bundle`

So we no longer need to have that in each bundle's manifest but only in the MoM.

**Comment by castulo** [comment]
Once the 4 PRs above get merged this issue can be closed
