### ISSUE TITLE
swupd operations will fail when the platform time is not correct

### ISSUE THREAD

**Issue by gvancuts** [clearlinux/swupd-client#678]
swupd operations will fail when the platform time is not right. While it is right to fail (certificate validation fails) in such scenario, it is hard to track what caused the failure. Having platforms that do not have the time right is a regular occurrence when working in embedded development where some boards do not have an on-board battery (and typically have the date/time set to 1970).

It would be a great help to have swupd check the platform time and issue a warning when the date looks off (e.g. a date that is in the 70's or a date that is in the past compared to the swupd client build time).

**Comment by gvancuts** [comment]
Note: I can add the error it throws if helpful (just not in front of a Clear Linux machine right now). It can easily be reproduced by temporarily forcing the platform date/time to something way in the past.

**Comment by phmccarty** [comment]
Note that swupd-client ships with a `verifytime` binary that is intended to correct certain types of time skews. Perhaps that binary isn't working correctly?

**Comment by castulo** [comment]
I just tried to recreate moving my system's time to a few years in the past and then using swupd, looks like as @phmccarty is saying swupd attempted to correct the time:
```
$ sudo swupd bundle-remove tmux
Warning: Current time is Sat Apr 18 00:00:08 1970

Attempting to fix...Set system time to Sat Apr 18 00:00:08 1970

Deleting bundle files...
Total deleted files: 1
Successfully removed 1 bundle
```

It didn't succeeded though, this is the date after the command above:
```$ date
Fri Oct 12 21:20:55 UTC 2018
```

**Comment by phmccarty** [comment]
@castulo `verifytime` uses the timestamp of /usr/share/clear/versionstamp (see [source](https://github.com/clearlinux/swupd-client/blob/ffead6e434021fe27a4aabb48dde2bbcd03c7d48/src/verifytime.c#L32)) as a reference. Is the Oct 12 2018 timestamp you posted coming from that file?

**Comment by otaviobp** [comment]
I'm using clear 26130 and my versionstamp is 1541596724 that is Wednesday, November 7, 2018 1:18:44 PM. So this looks correct.

@castulo What version of clear are you using? It may be a bug in that version.

**Comment by castulo** [comment]
Mine is 25590

**Comment by otaviobp** [comment]
So this is correct because that release is from Oct 12.

@gvancuts can you share us the clearlinux version you are using, the exact swupd commands and outputs with errors and the date set in the system before and after running swupd?

As commented we have a check that "fix" the system time to a better time when the system is too outdated. This is working fine for us, so there's something different in your system that is triggering the bug. It would help us a lot to understand the problem if we get the info I asked.

**Comment by gvancuts** [comment]
I’ll do that as soon as I’m back in front of my system (early next week). Thanks for the input so far!

**Comment by gvancuts** [comment]
Hi @otaviobp @castulo , finally back in front of a system.

I see the same as you are describing (*). The only `swupd` command that throws an error is `swupd check-update`:
```
$ sudo swupd check-update 
Error: unable to verify server SSL certificate
Error: unable to verify server SSL certificate
Curl error: (60) Peer certificate cannot be authenticated with given CA certificates
Error: Unable to determine the server version
```

*: it looks like there is a minor bug in what gets printed out as it is stating it is setting the system time to the **current time** instead of the time derived from the `versionstamp`. I guess this is a single-line fix [here](https://github.com/clearlinux/swupd-client/blob/ffead6e434021fe27a4aabb48dde2bbcd03c7d48/src/verifytime.c#L100) (`asctime(timeinfo)` is what leads to the incorrect reporting) although I wondered when reading the code why `set_time` has 2 arguments. It looks to me like a single one should do and the character string to be printed out on `stderr` could be derived from it (which would have avoided this minor bug).

**Comment by gvancuts** [comment]
Pull Request with the patch: https://github.com/clearlinux/swupd-client/pull/693

**Comment by otaviobp** [comment]
I figured out the problem them. check update is not running verifytime. I'll fix that. thank you for the report
