### ISSUE TITLE
Running update disables boot manager menu

### ISSUE THREAD

**Issue by mmccool** [clearlinux/swupd-client#683]
Running "swupd update" updates to the latest version of Clear Linux as expected, but also disables the boot manager menu (by setting the timeout to zero), which is a problem in multiboot systems where the boot manager menu is needed to select between multiple OSes.   The boot menu can be restored with the [following commands](https://clearlinux.org/documentation/clear-linux/tutorials/multi-boot)

      sudo clr-boot-manager set-timeout 5
      sudo clr-boot-manager update

but it would be even nicer if the system just restored the boot manager timeouts to their previous values.
May be related to this issue: https://github.com/clearlinux/swupd-client/issues/404

**Comment by otaviobp** [comment]
You are right about that. This is a bug.
@bryteise, in swupd we just run clr-boot-manager update Do you know if clr-boot-manager is reseting the timeout. If so, is this a bug to be moved to clr-boot-manager?

**Comment by bryteise** [comment]
I'm not aware of it being reset. @mmccool How did you initially set the timeout?

**Comment by otaviobp** [comment]
This looks like a problem in clr-boot-manager (if this is really a problem). I'm closing this for now. If any reporter find that this is really a bug in swupd, please reopen.
