### ISSUE TITLE
bad server data and corrupt deltas

### ISSUE THREAD

**Issue by aaronovz1** [clearlinux/swupd-client#706]
Hi guys,

I'm trying to debug two issues. The first issue I am getting `File content hash mismatch for ... (bad server data?)` error during verify. The file/directory in question is `/etc/polkit-1/rules.d`.

The Manifest.full lists the hash as:
`D.C.    7ce88cbc2f21ecca9c74d7034745eb922b2eba574c40239d89306dcbe2e6a1d9        1       /etc/polkit-1/rules.d`

But when dumping the hash on the system it is different. I thought maybe the issue was that some other bundle outside of os-core was changing it but didn't see anything that should be changing it.

The second issue is 3 messages reporting delta files being corrupt. I'm not even sure where to start digging on this one.

```
[INFO] : swupd-update-partition: Trying to update.
swupd-update-partition: swupd update --no-scripts -c <...> -v file:///tmp/swupd-version.zjWtPT -S /tmp/swupd-mount.D6ufGQ/swupd-state -p /tmp/swupd-mount.D6ufGQ -t
[INFO] : Update started.
[INFO] : Preparing to update from 1 to 2
[INFO] : Running script 'Pre-update'
[INFO] : Downloading packs...
[INFO] : Extracting connectivity pack for version 2
[INFO] : Extracting dss pack for version 2
[INFO] : Extracting kernelmodules pack for version 2
[INFO] : Extracting os-core pack for version 2

[INFO] : Couldn't use delta file /tmp/swupd-mount.D6ufGQ/swupd-state/delta/1-2-75d9e99b9642c65784868ae4a87106df1e71515f78fb72597cb9ab2e86a95797-e407429be9e3b93341387b69e1b45210af98317f598e33b49aa91aef2e1448d7: 'from' file corrupted on system, consider running 'swupd verify --fix'
[INFO] : Couldn't use delta file /tmp/swupd-mount.D6ufGQ/swupd-state/delta/1-2-b6e66ff1ee3129357c7f727a51fdcad96d68f510f523d37ceadf603307fdcb61-288970a473094e28ebc75f577e293a7e1677a0015aa8e15ed8793d57f507534f: 'from' file corrupted on system, consider running 'swupd verify --fix'
[INFO] : Couldn't use delta file /tmp/swupd-mount.D6ufGQ/swupd-state/delta/1-2-b1c4b3897e038ae0bd0bd3c58ce7936a0e3aef58c2a36a82e3f6acb3e82de2cc-ee4db89f5b8c5c526696069203afaf4a0cc97d2d55241b379cf603b6941c9508: 'from' file corrupted on system, consider running 'swupd verify --fix'

[INFO] : 
Statistics for going from version 1 to version 2:

[INFO] :     
    changed bundles   : 4
    new bundles       : 0
    deleted bundles   : 0

    changed files     : 25
    new files         : 1
    deleted files     : 1

[INFO] : Starting download of remaining update content. This may take a while...
[INFO] : Finishing download of update content...
[INFO] : Staging file content
[INFO] : Applying update
[INFO] : Update was applied.
[INFO] : WARNING: post-update helper scripts skipped due to --no-scripts argument
[INFO] : 3 files were not in a pack
[INFO] : Update successful. System updated from version 1 to version 2
[INFO] : swupd-update-partition: Verifying and fixing content.
[INFO] : swupd-update-partition: swupd verify --fix --picky --picky-tree /media/rfs/ro --picky-whitelist /swupd-state --no-scripts -F 4 -c <...> -v file:///tmp/swupd-version.zjWtPT -m 2 -S /tmp/swupd-mount.D6ufGQ/swupd-state -p /tmp/swupd-mount.D6ufGQ -t
[INFO] : Verifying version 2
[INFO] : Verifying files
[INFO] : Starting download of remaining update content. This may take a while...
[INFO] : Finishing download of update content...
[INFO] : Error: File content hash mismatch for /tmp/swupd-mount.D6ufGQ/swupd-state/staged/7ce88cbc2f21ecca9c74d7034745eb922b2eba574c40239d89306dcbe2e6a1d9 (bad server data?)
[INFO] : swupd-update-partition: swupd: return code 1 = unspecific failure
[INFO] : swupd-update-partition: Update failed.
[ERROR] : Failed to complete swupd-update-partition. Exited with code: 1
```

Any help would be appreciated as I'm approaching some deadlines. Cheers.

**Comment by aaronovz1** [comment]
Doing some more investigation it seems to be related to maybe uid/gid not being consistent somewhere during the build process. 

In a more isolated test environment if I run verify command myself I can see 3 mismatches.
```
Verifying version 1
Verifying files
	...0%Hash mismatch for file: /media/rfs/ro/etc/polkit-1/rules.d
	...82%Hash mismatch for file: /media/rfs/ro/usr/libexec/dbus-daemon-launch-helper
	...88%Hash mismatch for file: /media/rfs/ro/usr/share/polkit-1/rules.d
	...100%
Inspected 32179 files
  3 files did not match
Verify successful
```

If I inspect these files uid/gid I find that the ID in the full chroot doesn't match what is on the system.

On system:
```
ls -ln
drwx------    2 989      0             3488 Mar  9  2018 rules.d
```

Full chroot from `update/image/1/full/etc/polkit-1`
```
drwx------ 2 102 0 4096 Mar  9  2018 rules.d
```

@pohly sorry to drag you in as you don't maintain anymore, but do you think this could be related to #101?

**Comment by pohly** [comment]
Aaron <notifications@github.com> writes:
> @pohly sorry to drag you in as you don't maintain anymore, but do you
> think this could be related to #101?

It seems more likely that somewhere along the line a command isn't run
under pseudo. But that's just a guess.

**Comment by aaronovz1** [comment]
@pohly I am running this under mixer now using docker container so the commands are all run as root. I would have expected there to be many more hash issues otherwise, but it seems to be isolated to those 3 files/folders which have non root uid/gid (polkitd and messagebus). I am using `useradd-staticids` and supplying a static list of users and groups. The final uid/gid on the system matches what I supply, but the full chroot doesn't seem to match.

@matthewrsj Do you have any ideas of where I can look? It might be outside the scope of mixer and be an issue in the meta-swupd scripts but I'm running out of leads on this one.

**Comment by aaronovz1** [comment]
It looks like the issue is related to #101 and I needed to use `--numeric-owner` for creating and extracting the full.tar. This is different behavior to the original swupd-server and/or combination of using docker. Will close this out once I do some more tests.
