### ISSUE TITLE
Port to Golang?

### ISSUE THREAD

**Issue by junland** [clearlinux/swupd-client#742]
Is there a chance / talk that `swupd-client` might get rewritten in Go? Seems it would fit right in with `mixer` and `diva`, I personally would love to start hacking on `swupd` if it was written in Go, and it might lead to more contributions if it were written in a more readable language yet performant language.

**Comment by aaronovz1** [comment]
I feel that C fits better with the embedded nature of the application and Go is more appropriate for mixer as it's more of a backend tool.

**Comment by junland** [comment]
@aaronovz1 True. If the CL folks don't want to spend the resources on re-implementing the client they could just make a library in either C or Go. Haveing a library with some good documentation around could help other's to integrate it into other language's more easily. Think it's a good middle ground.
