### ISSUE TITLE
'swupd_lock' left behind after failure

### ISSUE THREAD

**Issue by mbelluzzo** [clearlinux/swupd-client#751]
Clear Linux installed on bare metal, Simple partition layout:
sda1 /boot
sda2 swap
sda3 / (ext4)

If during a 'swupd update' the '/' partition gets full, downloads fails and 'swupd update' fails just fine. Partition is left in full state. Admin does some cleanup and tries 'swupd update' again, but 'swupd_lock' is left behind and requires manual intervention.

```
swupd-client 3.18.5
   Copyright (C) 2012-2018 Intel Corporation

Compile-time options: +BZIP2 +SIGVERIFY -COVERAGE -BSDTAR -XATTRS -TAR_SELINUX +STATELESS
Compile-time configuration:
mount point                  /
state directory              /var/lib/swupd
bundles directory            /usr/share/clear/bundles
certificate path             /usr/share/clear/update-ca/Swupd_Root.pem
fallback certificate path    /usr/share/ca-certs/.prebuilt-store/anchors
systemd unitdir              /usr/lib/systemd/system
content URL                  https://cdn.download.clearlinux.org/update/
version URL                  https://cdn.download.clearlinux.org/update/
format ID                    26
pre-update hook              
post-update hook             /usr/bin/update-helper
```

#NoLockLeftBehind

**Comment by otaviobp** [comment]
I reproduced the "no space left" problem, but for me the lock was removed. @mbelluzzo Can you share the output of update command? Because maybe the problem is only triggered if it breaks in one specific point

**Comment by otaviobp** [comment]
What I have done:

    sudo dd if=/dev/zero of=file bs=1M count=512
    mount file /mnt/a
    sudo swupd verify --install --path /mnt/a -m 26600 --no-scripts 
    sudo swupd bundle-add vim --path /mnt/a
    df -h |grep mnt/a
    /dev/loop0      488M  478M     102   /mnt/a
    sudo dd if=/dev/zero of=/mnt/a/file bs=1M count=101
    sudo swupd update --path /mnt/a --statedir /mnt/a/var/lib/swupd
     -> error but no lock left behind
    sudo swupd update --path /mnt/a --statedir other_location
     -> error but no lock left behind

**Comment by mbelluzzo** [comment]
```
mbelluzz@clr-nuc ~ $ sudo time swupd update -t
Update started.
Preparing to update from 26170 to 26770
Curl: Error downloading to local file - /var/lib/swupd/26770/Manifest.desktop-kde-apps.tar
Failed to retrieve 26770 desktop-kde-apps manifest
Curl: Error downloading to local file - /var/lib/swupd/26770/Manifest.desktop-kde-apps.tar
Failed to retrieve 26770 desktop-kde-apps manifest
^CCommand terminated by signal 2
2.73user 0.71system 0:17.54elapsed 19%CPU (0avgtext+0avgdata 214724maxresident)k
202128inputs+127336outputs (85major+53185minor)pagefaults 0swaps
```

**Comment by otaviobp** [comment]
I was looking at the swupd lock code and swupd isn't removing the lock file on disk. Swupd locks it on startup and close the fd at the end. So if swupd is killed (abort, ctrl-c, kill), the os will release the resource and then you can execute swupd again. I couldn't reproduce the problem, but the any way I can see that we can reach this scenario is by having swupd still running in the background.

**Comment by castulo** [comment]
yeah, I'm seeing the same thing. Not being able to reproduce this, not even using Ctrl-C in the middle of an update.

**Comment by otaviobp** [comment]
Well, as @mbelluzzo couldn't reproduce that too, I'll close the ticket. If you see this problem again or find a way to reach this state, reopen this please.
