### ISSUE TITLE
Mixin: Swupd cannot update when a valid mix exists without migrating

### ISSUE THREAD

**Issue by jwakre** [clearlinux/swupd-client#753]
When a valid mix is created by mixin, calling 'swupd update' will try to migrate to the augmented upstream/mix content and ultimately fail because it cannot pass the signature check. At a glance, it seems that the --migrate option allows Swupd to skip the signature check, but is not responsible for migrating to the augmented update stream. To align with the help message, the --migrate option should be responsible for switching to the new update stream.

Steps to reproduce on Clear 26790:

1. Update to older version
* swupd verify --fix --picky -m 26780

2. Create mix with mixin
*  createrepo_c /foo
*  mixin repo add foo file:///foo
*  mixin package add vim
*  mixin build

3. Update
* swupd update

-----------------------------------------------------------------------------
Update started.                                                                                                                                                                          
NEW CLEAR AVAILABLE 26790                                                                                                                                                                
Directory walk started                                                                                                                                                                   
Directory walk done - 0 packages                                                                                                                                                         
Temporary output repo path: ./.repodata/                                                                                                                                                 
Preparing sqlite DBs                                                                                                                                                                     
Pool started (with 5 workers)                                                                                                                                                            
Pool finished                                                                                                                                                                            
Building bundles...                                                                                                                                                                      
2018/12/14 21:45:40 => BUILD BUNDLES                                                                                                                                                     
Creating bundles for version 26780010 based on Clear Linux 26790                                                                                                                         
Preparing new /usr/share/mix/update/image/26780010                                                                                                                                       
  and dnf config: /usr/share/mix/.yum-mix.conf                                                                                                                                           
Packager command-line: dnf --config=/usr/share/mix/.yum-mix.conf -y --releasever=26790                                                                                                   
Resolving packages using 4 workers                                                                                                                                                       
processing clear                                                                                                                                                                         
processing os-core                                                                                                                                                                       
... done with clear                                                                                                                                                                      
... done with os-core                                                                                                                                                                    
Resolving files using 4 workers                                                                                                                                                          
processing clear                                                                                                                                                                         
processing os-core                                                                                                                                                                       
Bundle os-core  3074 files                                                                                                                                                               
Bundle clear    7826 files                                                                                                                                                               
Cleaning DNF cache before full install                                                                                                                                                   
Installing all bundles to full chroot                                                                                                                                                    
[1/2] clear
[2/2] os-core
... building special os-core content
... Adding swupd default values to os-core bundle
2018/12/14 21:46:11
TIMINGS
2018/12/14 21:46:11   BUILD BUNDLES 30.574s
2018/12/14 21:46:11 TOTAL: 30.574s
2018/12/14 21:46:11 => CREATE MANIFESTS
Generating initial manifests...
  clear
  os-core
Reading bundle includes...
Performing manifest file subtraction...
Detecting manifest changes...
Writing manifest files...
MoM version 26780010
- clear                26780000
- os-core              26780010
- os-core-update-index 26780010
- os-core-update-index.I.26780000 26780010
- os-core.I.26780000   26780010
Signing manifest.
Compressing Manifest.MoM
Compressing bundle manifests
  os-core
  os-core-update-index.I.26780000
  os-core.I.26780000
  os-core-update-index
  full
2018/12/14 21:46:14 &{0xc00009c060}
2018/12/14 21:46:14 => CREATE FULLFILES
Using 4 workers
- Already created: 0
- Not compressed:  0
- Compressed
  - external-gzip        6
  - external-bzip2       2
  - external-xz          3
  - gzip                 1
Total fullfiles: 12
2018/12/14 21:46:14 &{0xc00009c060}
2018/12/14 21:46:14 => CREATE ZERO PACKS
Zero pack already exists for clear to version 26780000
Creating zero pack for os-core to version 26780010
  Fullfiles in pack: 2590
  Deltas in pack: 0
Creating zero pack for os-core-update-index to version 26780010
  Fullfiles in pack: 4
  Deltas in pack: 0
Saving the upstream URL: https://download.clearlinux.org
Saving the upstream version: 26790
Setting latest version to 26780010
2018/12/14 21:46:26
TIMINGS
2018/12/14 21:46:26   CREATE MANIFESTS  2.474s
2018/12/14 21:46:26   CREATE FULLFILES  72ms
2018/12/14 21:46:26   CREATE ZERO PACKS 12.799s
2018/12/14 21:46:26 TOTAL: 15.347s
* Verified upstream Manifest.MoM
Successfully built mix content
Checking manifest uniqueness...
Preparing to update from 26780 to 26780010
Certificate verification error: self signed certificate
WARNING!!! FAILED TO VERIFY SIGNATURE OF Manifest.MoM version 26780010
Retry #1 downloading server MoM manifest
Certificate verification error: self signed certificate
WARNING!!! FAILED TO VERIFY SIGNATURE OF Manifest.MoM version 26780010
Retry #2 downloading server MoM manifest
Certificate verification error: self signed certificate
WARNING!!! FAILED TO VERIFY SIGNATURE OF Manifest.MoM version 26780010
Retry #3 downloading server MoM manifest
Certificate verification error: self signed certificate
WARNING!!! FAILED TO VERIFY SIGNATURE OF Manifest.MoM version 26780010
Update took 118.1 seconds
Update failed.

**Comment by otaviobp** [comment]
As --migrate is expected to be used in the scenario you described, I'm moving this from bug to enhancement.

**Comment by otaviobp** [comment]
Mixin is being deprecated in favor of a newly added feature swupd-3rd-party. 
Closing issue as WONT-FIX
