### ISSUE TITLE
'swupd verify --fix' reports about files it cannot safely delete

### ISSUE THREAD

**Issue by phmccarty** [clearlinux/swupd-client#765]
In latest versions of Clear Linux OS, there are hundreds of files rooted at `/usr/share/mime` that are marked for deletion, so `swupd verify --fix` will try to delete them.

However, deleting that content is problematic: Those deletions were the result of a directory->symlink type change (i.e. `/usr/share/mime` used to be a directory, but it is now a symlink). SWUPD rightfully refuses to delete the content marked to be deleted, because all paths in that directory tree now contain a symlink component, the `/usr/share/mime` symlink. The verify subcommand explicitly checks for this condition to prevent swupd from following symlinks to delete content.

As seen in commit afce2631d64f5abdc06354d4fc054d7abbc86576, I added a FIXME that suggests `swupd verify --fix` should check if a file/directory/symlink can be "safely deleted", and if so, delete it. However, my current thinking is that while the "safe to delete" check is still mission critical, the `"Not safe to delete: <FILE>"` error message is not helpful for the end user; verify can just skip the file and not increment the not-deleted file count.

For reference, the swupd output in question looks like the following:

```
Verifying version 26800
Verifying files
...100%
Starting download of remaining update content. This may take a while...
...100%
Finishing download of update content...
Adding any missing files

Missing file: /usr/share/icons/Paper-Mono-Dark/icon-theme.cache

fixed
...60%
Missing file: /usr/share/icons/Paper/icon-theme.cache

fixed
...100%
Fixing modified files
...100%
File that should be deleted: /usr/share/mime/x-epoc/x-sisx-app.xml
Not safe to delete: /usr/share/mime/x-epoc/x-sisx-app.xml
File that should be deleted: /usr/share/mime/x-epoc
Not safe to delete: /usr/share/mime/x-epoc
File that should be deleted: /usr/share/mime/x-content/win32-software.xml
Not safe to delete: /usr/share/mime/x-content/win32-software.xml
File that should be deleted: /usr/share/mime/x-content/video-vcd.xml
Not safe to delete: /usr/share/mime/x-content/video-vcd.xml
File that should be deleted: /usr/share/mime/x-content/video-svcd.xml

.
.
.

File that should be deleted: /usr/share/mime/application/annodex.xml
Not safe to delete: /usr/share/mime/application/annodex.xml
File that should be deleted: /usr/share/mime/application/andrew-inset.xml
Not safe to delete: /usr/share/mime/application/andrew-inset.xml
File that should be deleted: /usr/share/mime/application
Not safe to delete: /usr/share/mime/application
File that should be deleted: /usr/share/mime/aliases
Not safe to delete: /usr/share/mime/aliases
File that should be deleted: /usr/share/mime/XMLnamespaces
Not safe to delete: /usr/share/mime/XMLnamespaces
Inspected 415705 files
2 files were missing
2 of 2 missing files were replaced
0 of 2 missing files were not replaced
817 files found which should be deleted
0 of 817 files were deleted
817 of 817 files were not deleted
Calling post-update helper scripts.
none
Error: Fix did not fully succeed
```

**Comment by thiagomacieira** [comment]
Interestingly, update does work. I tried it multiple times.

The solution to this is to schedule all deletions before any additions. Git is able to do this. But Git is also able to tell when you're moving from one version to another.

**Comment by phmccarty** [comment]
Yes, update does work, and verify --fix works just fine in this case, too. It's just that verify complains loudly about a condition that the end user should not need to care about (IMO), because verify will already add/modify content as necessary at the new location if the new location is tracked by swupd.

**Comment by thiagomacieira** [comment]
That's the point: the new location instead tracked because those files are cache and generated on each machine. Them existing in previous versions was a bug.

**Comment by lebensterben** [comment]
I have EXACT the same output. It's a new fresh install of latest Clear Linux and I haven't done any tweaks yet. So I guess this might be a bug.

**Comment by castulo** [comment]
@phmccarty and what about the exit code of "swupd verify --fix" in this situation? what should that be? if we are just skipping those files should we return 0 (successful) then?

**Comment by phmccarty** [comment]
@castulo If verify encounters no other problems, then yes, I think returning 0 is appropriate.

**Comment by lebensterben** [comment]
@phmccarty I can verify that this is fixed. Though `sudo swupd verify` still reports the two missing files, now `sudo swupd verify --fix` would correctly work.
