### ISSUE TITLE
The test library is adding bad links to bundles when the bundle contains symbolic links

### ISSUE THREAD

**Issue by castulo** [clearlinux/swupd-client#772]
When creating a test bundle that contains a symlink like this:
`create_bundle -L -n my_bundle -f /my_file -l /my_link my_test_environment`
A test bundle called _my_bundle_ is created in _my_test_environment_, this bundle has one link called _my_link_ and this link points to a file that is also added to the bundle's manifest. The problem is that during the creation of the bundle the symbolic link is created to point to an existing file but later in the process the file is renamed, causing the symlink to become dangling. This dangling link is then added to the bundle's manifest. If we run "swupd verify --fix" the installed bundle will always show a hash mismatch and the good symlink will be replaced with the dangling symlink.

This issue had not appeared so far because we are not using symlinks in a lot of our tests.

**Comment by castulo** [comment]
I found this problem while trying to create a test to recreate issue #765 , I'll need to fix this issue first before resuming working on that one

**Comment by otaviobp** [comment]
removing label bug because this isn't a bug in swupd. testing label may suffice.

**Comment by otaviobp** [comment]
#773 was closed, so I assume I can close this one. Reopen if I got it wrong
