### ISSUE TITLE
swupd update -F staging behaves inconsistently

### ISSUE THREAD

**Issue by hnanni** [clearlinux/swupd-client#781]
when pointed to go to staging, swupd fails sometimes (1.) other times it completes succesfully (3.)

1. swupd update sometimes fails to go to staging with the following error:

> root@clr-b6961c7d9476464cae25ba1a58542d2b ~ # swupd update -F staging
> swupd-client software update 3.15.2
>    Copyright (C) 2012-2018 Intel Corporation
> 
> Update started.
> Attempting to download version string to memory
> Preparing to update from 21420 to 27160
> Warning: Removing corrupt Manifest.MoM artifacts and re-downloading...
> Failed to load 27160 MoM manifest
> Retry #1 downloading server Manifests
> Warning: Removing corrupt Manifest.MoM artifacts and re-downloading...
> Failed to load 27160 MoM manifest
> Retry #2 downloading server Manifests
> Warning: Removing corrupt Manifest.MoM artifacts and re-downloading...
> Failed to load 27160 MoM manifest
> Retry #3 downloading server Manifests
> Warning: Removing corrupt Manifest.MoM artifacts and re-downloading...
> Failed to load 27160 MoM manifest
> Failure retrieving manifest from server
> Unable to load manifest after retrying (config or network problem?)
> Update took 73.5 seconds

1.1 MoM seems to be reachable:

> root@clr-b6961c7d9476464cae25ba1a58542d2b ~ # curl -s -O 
> https://cdn.download.clearlinux.org/update/27160/Manifest.MoM
> root@clr-b6961c7d9476464cae25ba1a58542d2b ~ # echo $?
> 0
> root@clr-b6961c7d9476464cae25ba1a58542d2b ~ # head Manifest.MoM 
> MANIFEST        26
> version:        27160
> previous:       27150
> minversion:     27150
> filecount:      566
> timestamp:      1547149732
> contentsize:    0

2. `swupd update` then `swupd update -F staging` completes succesfully:

 

> root@clr-b6961c7d9476464cae25ba1a58542d2b ~ # swupd update
> swupd-client software update 3.15.2
>    Copyright (C) 2012-2018 Intel Corporation
> 
> Update started.
> Attempting to download version string to memory
> Preparing to update from 21420 to 21520
> Downloading packs...

[...snip...]

> 7489 files were not in a pack
> Update successful. System updated from version 25770 to version 27150
> root@clr-b6961c7d9476464cae25ba1a58542d2b ~ # swupd update -F staging
> Update started.
> Preparing to update from 27150 to 27160
> Downloading packs...

[...snip...]

> Statistics for going from version 27150 to version 27160:
> 
>     changed bundles   : 11
>     new bundles       : 0
>     deleted bundles   : 0
> 
>     changed files     : 76
>     new files         : 28
>     deleted files     : 10
> 
> Starting download of remaining update content. This may take a while...
>         ...100%
> Finishing download of update content...
> Staging file content
> Applying update
>         ...100%
> Update was applied.

[...snip...]

> Update took 14.2 seconds
> Update successful. System updated from version 27150 to version 27160

3. swupd -F staging, sometimes is able to complete succesfully:

> root@clr-28e1b2933b89433b8d92c8f7e18ac7ae ~ # swupd update -F staging
> swupd-client software update 3.15.2
>    Copyright (C) 2012-2018 Intel Corporation
> 
> Update started.
> Attempting to download version string to memory
> Preparing to update from 21420 to 27150
> Downloading packs...
> 
> Extracting joe pack for version 27150
>         ...2%
> Extracting ethtool pack for version 27150
>         ...7%
> Update took 661.2 seconds
> Update successful. System updated from version 21420 to version 27150
> 18189 files were not in a pack

**Comment by otaviobp** [comment]
Format staging isn't supported and should be used only for testing purposes. This is problematic specially when crossing format bump barriers and in your example you crossed 2 barriers. The recommended in this case is that you use swupd update to get to the latest released version and then use format staging, as you did later.

This specific problem was caused because we updated the openssl in the system, so older swupd may have problems on validating the signature of new manifests. As we don't support long updates like that using format staging I'll close this bug.
