### ISSUE TITLE
Check for binary before executing

### ISSUE THREAD

**Issue by mdhorn** [clearlinux/swupd-client#795]
Swupd attempts to run the clr-boot-manager as a post step, but does not check if the executable is present before running:
```
Calling post-update helper scripts.
sh: <...path...>/rootfs//usr/bin/clr-boot-manager: No such file or directory
```
https://github.com/clearlinux/swupd-client/blob/master/src/scripts.c#L54

Please consider adding a check for the presence of the binary before attempting to execute.
Maybe print a debug or information message about skipping the execute if not present.

**Comment by otaviobp** [comment]
Nice idea +1.
