### ISSUE TITLE
swupd is slower than the packaging tools in other distributions

### ISSUE THREAD

**Issue by eero-t** [clearlinux/swupd-client#806]
Always when I used swupd, it starts by downloading >50MB of data from network, which makes in excruciatingly slow to use (compared to the package management tools in other distributions).  Successive swupd invocations are fast, but I rarely do those.

For example, with Debian APT tool, updating the package information to latest upstream state is done with a *separate* "update" command, so that one doesn't need to suffer download waits if one is e.g. just doing package/bundle content searches.

On top of that, the "apt update" command e.g. in Ubuntu 18.04 is clearly faster than swupd download (for starters, it loads much smaller amount of data).

#41 and #647 issues may be related.

**Comment by otaviobp** [comment]
A PR was opened to use manifests-deltas and reduce significantly the download size on updates. https://github.com/clearlinux/swupd-client/pull/815

Thank you for the feedback

**Comment by otaviobp** [comment]
Closed on swupd. As soon as mixer start producing delta-manifests this will be concluded.
