### ISSUE TITLE
Consider using libnica

### ISSUE THREAD

**Issue by phmccarty** [clearlinux/swupd-client#81]
The libnica project from https://github.com/ikeydoherty/libnica provides a nice, minimal C library that swupd-client could leverage.

As an example, in #74, it was suggested that we could use the `nc_mkdir_p` instead of the equivalent of `system("mkdir -p")`.

**Comment by phmccarty** [comment]
I'm not actively working on this issue, so I'll unassign it.

**Comment by matthewrsj** [comment]
We have no real plans to do this. Closing.
