### ISSUE TITLE
verifytime: Search for versionstamp ignores --path

### ISSUE THREAD

**Issue by pdxjohnny** [clearlinux/swupd-client#812]
User specified path is not being prepended.

https://github.com/clearlinux/swupd-client/blob/880191fd1b0ebabb2e1029a4a126d1aa3ac0c952/src/verifytime.c#L37-L41

https://github.com/clearlinux/swupd-client/blob/880191fd1b0ebabb2e1029a4a126d1aa3ac0c952/docs/swupd.1.rst#L81-L84

**Comment by otaviobp** [comment]
Thanks. This looks wrong. I'll set that as a bug to be fixed.
