### ISSUE TITLE
Improve State Directory Cleaning Policy

### ISSUE THREAD

**Issue by jwakre** [clearlinux/swupd-client#818]
When performing an update, useful manifests can be cleaned from the state directory. For instance, when running the update-manifest-delta.bats test from #815, an update from v10 to v20 is performed. When I look at the state directory, only the manifests from v10 are cached. As a result, I would need to download the manifests for version 20 again to do an update from v20 to v30.

It would be nice to keep all manifests used by the current MoM cached in the state directory. This would greatly reduce the number of downloaded bundle manifests for updates. The "from" manifests would exist in the state directory and the "to" manifests would be created by applying manifest deltas.

**Comment by otaviobp** [comment]
> It would be nice to keep all manifests used by the current MoM cached in the state directory. This would greatly reduce the number of downloaded bundle manifests for updates. The "from" manifests would exist in the state directory and the "to" manifests would be created by applying manifest deltas.

We have a simple grep for manifests in MoM, so this shouldn't happen. Maybe there's a bug on the way we're doing that. I tested this feature on last 5 releases on os-clr-on-clr and it seams to be working. I'll check what's wrong with that test

**Comment by otaviobp** [comment]
@jwakre oh, I'm manually removing all manifests to make sure the test will break if the delta manifest is not working. Is this manifests you were talking about?
https://github.com/otaviobp/swupd-client/blob/1e32ab1ac00816ea7d720566284498f702db49a4/test/functional/update/update-manifest-delta.bats#L21

**Comment by jwakre** [comment]
> @jwakre oh, I'm manually removing all manifests to make sure the test will break if the delta manifest is not working. Is this manifests you were talking about?
> https://github.com/otaviobp/swupd-client/blob/1e32ab1ac00816ea7d720566284498f702db49a4/test/functional/update/update-manifest-delta.bats#L21

Note: This isn't a problem with the manifest delta PR. I just used the test as an example to demonstrate the current state directory cleaning policy.

No, I am talking about how manifests are cached in the state directory (testfs/state). If you append the '-k' argument to Swupd, it won't clean the state directory and the v20 manifests will be cached.

I think update performance could be improved by changing how the state directory is cleaned (clean.c, function: clean_staged_manifests)

**Comment by jwakre** [comment]
This is actually not an issue.

When using the test library to create a new version without the '-r' argument, the update will not change the current version. As a result, my test update thought the system was at version 10, so manifests in version 20 were cleaned from the state directory.
