### ISSUE TITLE
swupd-update: manifest does not work on latest if used through an integer literal

### ISSUE THREAD

**Issue by lsandoval** [clearlinux/swupd-client#821]
**Describe the bug**
Semantically, these should give the same status code

swupd update -m latest
swupd update -m X

where X=`curl -s https://download.clearlinux.org/latest`

**To Reproduce**

1. swupd update -m latest 
2. check the return status (must be zero) and check the version your OS has been updated (<version>)
3. swupdu update -m <version>
4. check the return status: it is non-zero

**Expected behavior**
Step 4. return status must be zero
 
**Screenshots**

**Environment (please complete the following information):**
 - Clear Linux OS version: [`cat /usr/lib/os-release`]
 - Bundles: [e.g. `sudo swupd bundle-list`]

**Additional context**

**Comment by otaviobp** [comment]
Fixed by #814 and it will be available on next swupd release.
