### ISSUE TITLE
Support adding commands from other binaries into swudp

### ISSUE THREAD

**Issue by otaviobp** [clearlinux/swupd-client#826]
Currently all swupd commands are implemented in swupd-client source code and built in a single binary. With this change we should be able to execute other binaries to perform some swupd tasks
 - Create a simple binary execution main function
 - Create security measures to prevent executing unsafe binaries (check hash)
 - Create tests to validade that

**Comment by otaviobp** [comment]
> Create security measures to prevent executing unsafe binaries (check hash)

I think we can skip this item. If we hardcode the path we are sure that the binary is in the system and we have checked the hash to install that.

**Comment by castulo** [comment]
> > Create security measures to prevent executing unsafe binaries (check hash)
> 
> I think we can skip this item. If we hardcode the path we are sure that the binary is in the system and we have checked the hash to install that.

yes, make sense, I'll omit checking the hash, there is no point
