### ISSUE TITLE
Split search out completely

### ISSUE THREAD

**Issue by bryteise** [clearlinux/swupd-client#848]
The current swupd search default mechanism in use in Clear Linux is a completely different utility than the built-in version of swupd-client. Given that swupd-client is likely to continue to make use of components like this in the future as well it may be better to have swupd search do a bundle add on first use if the search ability isn't installed. This will enable creating a smaller update centric bundle if users do not need search (getting smaller is very important for using swupd inside docker as that tends to make use of a preset list of bundles without ever needing the search feature).

**Comment by otaviobp** [comment]
Are you ok on just printing the message or do you think we should try to install it? Right now if you run swupd search without os-core-search installed it will print:

    Error: Binary /usr/bin/swupd-search doesn't exist in your system
    Swupd search depends on a binary available on os-core-search bundle
    Run 'swupd bundle-add os-core-search' to install it
