### ISSUE TITLE
swupd info does not respect -p / --path option

### ISSUE THREAD

**Issue by thiagomacieira** [clearlinux/swupd-client#851]
**Describe the bug**
When you run `swupd info -p <dirname>`, it prints the information about the host, not the target system.

**To Reproduce**
1. Install a version of Clear in a subdirectory (mount a live image, VM image, use `mkosi`, etc.)
2. Make sure it is different from the host system
3. Run `swupd info -p <dirname>`

**Expected behavior**
Swupd should print the information about the contained system.

**Environment (please complete the following information):**
 - Clear Linux OS Version: 28330 (contained system: 28310)

```
$ swupd info -p clear
Installed version: 28330
Version URL:       https://cdn.download.clearlinux.org/update/
Content URL:       https://cdn.download.clearlinux.org/update/
$ swupd info --help
Installed version: 28330
Version URL:       https://cdn.download.clearlinux.org/update/
Content URL:       https://cdn.download.clearlinux.org/update/
$ cat clear/usr/lib/os-release 
NAME="Clear Linux OS"
VERSION=1
ID=clear-linux-os
ID_LIKE=clear-linux-os
VERSION_ID=28310
PRETTY_NAME="Clear Linux OS"
ANSI_COLOR="1;35"
HOME_URL="https://clearlinux.org"
SUPPORT_URL="https://clearlinux.org"
BUG_REPORT_URL="mailto:dev@lists.clearlinux.org"
PRIVACY_POLICY_URL="http://www.intel.com/privacy"
```

**Comment by otaviobp** [comment]
Thanks for this report. And this is a simple fix. We wasn't calling the function to parse global parameters in info. Thanks
