### ISSUE TITLE
nitpick: "swupd verify --help" : one line way too long

### ISSUE THREAD

**Issue by jurobystricky** [clearlinux/swupd-client#860]
version: swupd-client 3.19.0

running "swupd verify --help " displays this line:
<pre>
...
-w, --picky-whitelist=[RE] Any path completely matching the POSIX extended regular expression is ignored by --picky. Matched directories get skipped. Example: /var|/etc/machine-id. Default: /usr/lib/modules|/usr/lib/kernel|/usr/local|/usr/src
</pre>

This single line should be broken into several shorter ones.

**Comment by otaviobp** [comment]
Thanks. I added some line breaks to be easier to read. The ideal would be to have a better way to align descriptions, but for not it's at least a lot better to read.
