### ISSUE TITLE
bundle-add fails to install bundle content that should overwrite custom content

### ISSUE THREAD

**Issue by phmccarty** [clearlinux/swupd-client#863]
**Describe the bug**

If I install custom content on Clear Linux OS to locations that swupd controls (e.g. `/usr/bin`), and I then `swupd bundle-add` a bundle that should overwrite that custom content, `swupd bundle-add` fails to overwrite that content with its own content.

**To Reproduce**

1. Run `swupd bundle-remove keepassxc`
2. Run `touch /usr/bin/keepassxc`
3. Run `swupd bundle-add keepassxc`
4. Observe that `/usr/bin/keepassxc` is still the empty file created in step 2.

**Expected behavior**

Expected is for `swupd bundle-add keepassxc` to install all content for the bundle, also overwriting any custom content that may exist at the install destinations of the content.

**Environment (please complete the following information):**
 - swupd info
```
Installed version: 28410
Version URL:       https://cdn.download.clearlinux.org/update/
Content URL:       https://cdn.download.clearlinux.org/update/
```

**Comment by castulo** [comment]
@phmccarty I submitted  a PR to fix this issue. I'd like your feedback if you have some time.
