### ISSUE TITLE
swupd search results suggested-bundle size should be reported as "MB" instead of "Mb"

### ISSUE THREAD

**Issue by bktan8** [clearlinux/swupd-client#874]
**Describe the bug**
When swupd search shows the bundle size, it shows the units in "Mb" (little "b"), which is megabits.  It should use "MB" (big "B") instead.

**To Reproduce**
For Example:

```bktan1@clr-i9990k ~ $ sudo swupd search -b setquota
Password: 
Bundle with the best search result:
     ruby-basic                     	- Run ruby language programs  (37Mb) (installed)

This bundle can be installed with:

  swupd bundle-add  ruby-basic

Alternative bundle options are
     desktop                        	- Run the GNOME GUI desktop environment.  (257Mb) (installed)
     dev-utils                      	- Assist application development  (266Mb) (installed)
     texlive                        	- major TeX-related typesetting programs, macro packages, and fonts.  (538Mb) (installed)
```

**Expected behavior**
Report the size in "MB" instead of "Mb".

**Environment (please complete the following information):**
 - Clear Linux OS Version: 28510
 - Platform: all

**Comment by otaviobp** [comment]
Thank you for the reported. Fixed and should be available on next swupd-search release.

**Comment by bktan8** [comment]
@otaviobp - Thanks for the quick response!
