### ISSUE TITLE
offline bundle-list

### ISSUE THREAD

**Issue by tripzero** [clearlinux/swupd-client#895]
I understand why bundle-list -a would require an internet connection, but bundle-list with no args first tries to connect... and reconnect... waiting about 60 seconds total before spitting out the results for bundles installed on system.

It'd also be nice to have the file sizes of each bundle.

**Comment by otaviobp** [comment]
This was just partially fixed. It works only when running as regular user. Reopening

**Comment by castulo** [comment]
I'm closing this issue since it is fixed now. The only time swupd hangs is when the system uses a proxy and the proxy is not responding. In such cases swupd waits for 30 seconds then it times out.
