### ISSUE TITLE
Post update triggers are not blocking

### ISSUE THREAD

**Issue by gtkramer** [clearlinux/swupd-client#909]
**Describe the bug**
After running `swupd verify --install` on a chroot that has touched bundle files in it to perform an install of Clear Linux, post update triggers are run in a non-blocking mode.  This prevents automation from creating the official Docker image for Clear Linux, or validation from running that checks whether the clrtrust post update trigger has run without resorting to adding a `sleep 1m` after the chroot is created.

**To Reproduce**
Use the following script:
```
#!/bin/bash
set -xe
TMP_ROOT="$(mktemp -d)"
mkdir -p "${TMP_ROOT}/usr/share/clear/bundles"
touch "${TMP_ROOT}/usr/share/clear/bundles/"{os-core,os-core-update}
swupd verify --install -p "${TMP_ROOT}" -b -m "$(< /usr/share/clear/version)"
# Missing a sleep 1m here, so the following command will sometimes fail
[ -d "${TMP_ROOT}/var/cache/ca-certs" ]
rm -rf "${TMP_ROOT}"
```

**Expected behavior**
After a `swupd verify --install`, only when all of the post update triggers have finished running does the swupd command exit.  While this could be exposed as a new command line option, it would probably be better to have this blocking behavior for post update triggers enabled by default to ensure all users/consumers of swupd get this behavior, namely DevOps, the clr-installer, and QA.

**Environment (please complete the following information):**
 - Clear Linux OS Version: 29100 (N/A)
 - Platform: Baremetal, VM, anywhere swupd is used

**Comment by otaviobp** [comment]
Thanks for the report.

The ideal solution for this would be to add a new cmdline flag to force all post update scripts to be run without the --no-block flag.

**Comment by gtkramer** [comment]
@otaviobp, that makes sense.  If the non-blocking behavior is wanted, then it should be specified only when needed.
