### ISSUE TITLE
Rename "swupd verify --install" to "swupd os-install"

### ISSUE THREAD

**Issue by castulo** [clearlinux/swupd-client#911]
The purpose of `swupd verify --install` is so it can be used to install a new Clear OS in a target system. However since currently it is part of the `swupd verify` command it makes it confusing  as of to what its purpose is.

We should move the `swupd verify --install` option to be its own command `swupd os-install` so its purpose is more straightforward. The new command will still use the verify code to perform the task.

Note: the name `swupd os-install` was chosen over `swupd install` to avoid misleading users to believe they can use `swupd install` to install bundles. 

Tasks:
- [x] Add `swupd os-install` to main menu.
- [x] Add new os-install.c file with the following functions:
    - The command main function
    - Function(s) to parse the command
    - Validation of command options
- [x] Deprecate the `--install` option from verify.c
- [x] Add to the auto-complete script
- [x] Update functional tests
- [x] Update Travis with the new tests
- [x] Update documentation

**Important: This change will require an update in the clr-installer side which uses `swupd verify --installl` to install the OS.**

**Comment by otaviobp** [comment]
Related to #250
Check if there's something in that issue that can help with this command
