### ISSUE TITLE
swupd verify --install ignores OS defaults

### ISSUE THREAD

**Issue by mdhorn** [clearlinux/swupd-client#924]
**Describe the bug**
Using swupd to install a new OS from mix fails.

**To Reproduce**
- Build a mix
- Create an image from that mix
- Boot the new image
- Use swupd from booted image to install OS with `swupd verify --install`
- swupd will fail to verify the signature and will be using that last version from clearlinux.org instead of the mix

**Expected behavior**
swupd will use the content and version URL from the /usr/share/defaults/swupd

**Environment (please complete the following information):**
```
root@clr-live ~ # swupd info
Installed version: 10
Version URL:       http:/myhost.com/mixer/
Content URL:       http://myhost.com/mixer/

root@clr-live ~ # swupd mirror
Installed version: 10
Version URL:       http://myhost.com/mixer/
Content URL:       http://myhost.com/mixer/

root@clr-live ~ # swupd verify --path=/mnt --statedir=/mnt/var/lib/swupd --install -m latest --force --no-boot-update -B os-core-update,openssh-server,telemetrics,tzdata,kernel-native
/mnt//usr/share/clear/versionstamp does not exist!
Verifying version 29480
Certificate verification error: self signed certificate
Certificate verification error: self signed certificate


root@clr-live ~ # swupd -v
swupd-client 3.19.0
   Copyright (C) 2012-2018 Intel Corporation

Compile-time options: +BZIP2 +SIGVERIFY -COVERAGE -BSDTAR -XATTRS -TAR_SELINUX +STATELESS
Compile-time configuration:
mount point                  /
state directory              /var/lib/swupd
bundles directory            /usr/share/clear/bundles
certificate path             /usr/share/clear/update-ca/Swupd_Root.pem
fallback certificate path    /usr/share/ca-certs/.prebuilt-store/anchors
systemd unitdir              /usr/lib/systemd/system
content URL                  https://cdn.download.clearlinux.org/update/
version URL                  https://cdn.download.clearlinux.org/update/
format ID                    27
pre-update hook
post-update hook             /usr/bin/update-helper
```

Note that even though the defaults are set correctly for the mix, and one can do a `swupd bundle-add` or `swupd verify --fix` and the correct URL is used, when doing a `swupd verify --install`, swupd falls back to its compile time defaults.

**Comment by mdhorn** [comment]
@otaviobp Can this be targetted for the 4.0.0 release?

**Comment by otaviobp** [comment]
All swupd commands use settings of the chroot where --path is pointed to. So if there's no mirror setting in the desired path the default that swupd was built to is the one going to be used. This is the expected behavior and it's consistent on the swupd commands you mentioned (verify and bundle-add).

**Comment by otaviobp** [comment]
We are going to add a fallback to the system config if the one in path is missing. And targeting to next release
