### ISSUE TITLE
Add tree view for bundle-list dependency 

### ISSUE THREAD

**Issue by puneetse** [clearlinux/swupd-client#929]
The -d and -D commands are helpful but I would like a tree view for bundle-list showing dependencies, similar to the view of `mixer bundle list --tree`.

**Comment by otaviobp** [comment]
Nice suggestion. thanks

**Comment by jumpinggoofballs** [comment]
Any news on this? Trimming the system of all the random bundles that get added when you install something to try out is a right hassle.

**Comment by castulo** [comment]
> Any news on this? Trimming the system of all the random bundles that get added when you install something to try out is a right hassle.

I submitted a PR to address your suggestion.
