### ISSUE TITLE
Some modified files show in swupd verify but not swupd verify --picky

### ISSUE THREAD

**Issue by puneetse** [clearlinux/swupd-client#932]
**Describe the bug**
/usr/lib/modules is part of the default picky-whitelist so they don't get targeted with a `swupd verify --picky` but they do get targeted with a `swupd verify`.

Additionally, `swupd verify --picky --fix` fixes those files even though they didn't show in `swupd verify --picky` 

**To Reproduce**
Have custom kernel modules in use. Run `swupd verify` vs `swupd verify --picky`.

**Expected behavior**
I'd expect `swupd verify` to always be a subset of `swupd verify --picky`

**Environment (please complete the following information):**
 - Clear Linux OS Version: 29620

**Comment by otaviobp** [comment]
There were a previous discussion about the best behavior of verify --picky. Reporting your expectations was  a good feedback for us and it is what I would expect too.
Setting this as a bug
