### ISSUE TITLE
fail to remove bundle after upgrading to custom mix

### ISSUE THREAD

**Issue by avalluri** [clearlinux/swupd-client#937]
**Describe the bug**
I created my custom bundle as described in [this](https://clearlinux.org/documentation/clear-linux/guides/maintenance/mixin#examples) document. Once after upgrading to my ustom mix using `swupd update --migrate`, I couldn't remove any existing bundle, fails with below error:

```
# swupd check-update 
Current OS version: 29660000
There are no updates available

# swupd bundle-remove file
Error: Cannot load file sub-manifest (ret = 8)
Failed to remove 1 of 1 bundles
```

**To Reproduce**
Create a custom bundle mix using `mixin` tool with below series of commands:
```
# swupd bundle-add mixer
# mixin package add file --bundle pmem-csi 
# mixin package add xfsprogs --bundle pmem-csi
# mixin package add e2fsprogs --bundle pmem-csi
# mixin package add LVM2-bin --bundle pmem-csi
# mixin build
# swupd update --migrate
```

Then try to delete a bundle:
```
# swupd bundle-remove file
Error: Cannot load file sub-manifest (ret = 8)
Failed to remove 1 of 1 bundles
```

**Expected behavior**
The bundle remove should succeed. 

**Environment (please complete the following information):**
 - Clear Linux OS Version: 
Installed version: 29660000
Version URL:       https://cdn.download.clearlinux.org/update/
Content URL:       https://cdn.download.clearlinux.org/update/
 - Platform(s): QEMU virtual maching, docker container

**Comment by otaviobp** [comment]
Mixin is being deprecated in favor of a newly added feature swupd-3rd-party. 
Closing issue as WONT-FIX
