### ISSUE TITLE
verify_fix_path not called for manifests

### ISSUE THREAD

**Issue by tpepper** [clearlinux/swupd-client#94]
This function is meant to be a generic helper to insure integrity and survive-ability.  It is not applied to manifests that don't hash check and actually should be.

**Comment by fenrus75** [comment]
As a general design rule it is a MUST that each object for which the hash or signature check fails, gets deleted from the OS filesystem before the client application exits. It is NEVER ok to leave known-bad content on the disk, both from general security principles angle as well as from a recoverability angle (one bad download should never be able to brick the machine)

**Comment by tpepper** [comment]
to elaborate on this, there are three cases of verification/failure/recovery:

# MoM signature fails to verify: recover is reinstall system or run with --force (NOTE: a PR for the --force feature is soon to be coming from @bradTpeters)
# bundle Manifest hash does not match expected from the MoM: auto recover by unlinking file and redownloading it
# file hash does not match expected from the bundle Manifest: auto recover by unlinking file and redownloading it

The first item there is already in the works.  The third item there is already implemented.  This issue is about the middle item.

**Comment by fenrus75** [comment]
I think we also should at least try to redownload the MoM once or twice before giving up.

**Comment by tpepper** [comment]
Yes.../me just edited to clarify.  My intent was to call out that we have a basic pattern of "attempt auto recover by unlinking file and redownloading it".  Beyond that, there are additional options, depending on the case.  The above comment should capture that better now.

**Comment by matthewrsj** [comment]
This issue was addressed in https://github.com/clearlinux/swupd-client/commit/ba4f80034d9bef9ba7c6bd832268d9f661cc1727
