### ISSUE TITLE
Swupd mirror with --versionurl and --contenturl can be confusing

### ISSUE THREAD

**Issue by otaviobp** [clearlinux/swupd-client#941]
**Describe the bug**
If I run

    sudo swupd mirror --versionurl=https://myserver/ --contenturl=https://myserver

Swupd prints:

    Installed version: xxxxxx
    Version URL:       https://myserver
    Content URL:       https://myserver

And this may look like we are setting the mirror. But to set a mirror we need to use the flags --set.

**Possible solutions**

1. Set the mirror if --versionurl or --contenturl is used.

or

2. Warn the user that --set is required to set the mirror.

We need to evaluate which one is better

**Comment by dorileo** [comment]
I vote up for checking if ```--set``` or ```--unset``` is not present.
