### ISSUE TITLE
`swupd` has ambiguous option

### ISSUE THREAD

**Issue by lebensterben** [clearlinux/swupd-client#946]
Execute `swupd search-file -h` and you will see the following to options:

```
   -b, --no-boot-update    Do not install boot files to the boot partition (containers)
   -b, --binary            Search paths where binaries are located for a match
```

`-b` is duplicated.

**Comment by castulo** [comment]
I see this kind of conflict between global options and local options occur many times in swupd:

With "update":
```
-d, --retry-delay (global)
-d, --download   (local)
```

With "bundle-list":
```
-d, --retry-delay           (global)
-d, --deps=[BUNDLE]  (local)
```

With "search":
```
-b, --no-boot-update  (global)
-b, --binary                   (local)
```

With "mirror":
```
-u, --url=[URL] (global)
-u, --unset        (local)
```

All flags are evaluated against local flags first, and if they match one, then they are not evaluated against global flags. Based on the global flags these local flags are overriding I don't see any real problem, nonetheless it is an inconsistency that can lead to confusions and it would be best to fix.

The one dilemma comes with how to fix this without renaming flags and possibly breaking users. 🤔
