### ISSUE TITLE
remove manifest timestamp

### ISSUE THREAD

**Issue by tpepper** [clearlinux/swupd-client#95]
We've never used this timestamp for anything.  Manifests are meant to be immutable once created.  So the timestamps should only flow forward and no issues.

In the unfortunate situation of a DevOps group needing to recreate old Manifests, they will have a new timestamp, and a changed hash relative what an old MoM (ie: assume MoM's got recreated, but some clients had downloaded and cached an old MoM, then downloaded a new bundle manifest on bundle add), which leads to an error/warn in the client at runtime.

The error/warn can be addressed via Issue #94, but that code path would also have never hit if the manifest did not have the timestamp in it.

Let's simply remove the timestamp.  This can be done without a format bump.

**Comment by matthewrsj** [comment]
This should actually be implemented in server. Closed in favor of https://github.com/clearlinux/swupd-server/issues/79
