### ISSUE TITLE
Inform users that http is insecure and require a force flag to continue

### ISSUE THREAD

**Issue by otaviobp** [clearlinux/swupd-client#953]
If users try to use a server using http inform users that this is insecure and don't proceed unless flag --force-insecure-http is used. There's one tricky problem on adding this flag. We need a way to inform that on autoupdate. So we need to have a way to do it using a config file too.

**Expected behavior** 

 - [x] User uses -u (or equivalent) with http: print a warning message and require --force-insecure-http to proceed
 - [x] User tries to run any command and the default server (mirror or server in /usr/share/default) is a http server: print a warning message and require --force-insecure-http to proceed
 - [x] User runs "swupd mirror" command to set a new mirror pointing to an http server. Warn the user and require --force-insecure-http to proceed. If flag is used create a configuration file to always use that flag when a swupd command is run.
 - [x] Users run any command pointing to an http server and using the --force-insecure-http flag: Warns that this is insecure and proceed.
 - [ ] Users have a mirror or default server pointing to a http server and no configuration file forcing that flag: We need to notify him that autoupdate is disabled on system logins with instructions on what to do about that.

Depends on #952

**Comment by castulo** [comment]
I think `--allow-insecure-http` sounds more accurate than `--force-insecure-http `
