### ISSUE TITLE
swupd search help is not accurate (nor consistent across different sources)

### ISSUE THREAD

**Issue by gvancuts** [clearlinux/swupd-client#961]
**Describe the bug**
There are different ways to get help about the options supported by `swupd search`, but the information returned is not consistent.

**To Reproduce**
Run the following commands:
1. `sudo swupd search -h` and you get:
```
Searches for the best bundle to install a binary or library.

Usage:
  swupd-search [search_term...]

Flags:
  -h, --help      help for swupd-search
  -a, --all       show all
  -q, --quiet     quiet mode
  -v, -vv, --verbose   verbose mode
```
2. `man swupd`, the `search` section shows:
```
       search {string}
          Search for matching paths in manifest data. The specified {string} is matched in any part of the path listed in manifests, and all matches are printed, including the name of the bundle in which the match was found.

          If manifest data is not present in the state folder, it is downloaded from the content url.

          Because this search consults all manifests, it normally requires to download all manifests for bundles that are not installed, and may result in the download of several mega bytes of manifest data.

          • -l, --library
                Restrict search to designated dynamic shared library paths.

          • -b, --binary
                Restrict search to designated program binary paths.

          • -i, --init
                Perform collection and download of all required manifest resources needed to perform the search, then exit.
```

**Expected behavior**
The `swupd search` help sections should be updated to be the same and reflect the actual implementation.

**Environment (please complete the following information):**
 - Clear Linux OS Version: Installed version: 29940
 - Platform: N/A

**Comment by castulo** [comment]
`swupd search` was renamed `swupd search-file` and a new `swupd search` function was introduced. Looks like the man pages were never updated, the info you show is actually for search-file and the man pages are missing the search info.

**Comment by castulo** [comment]
Thanks for reporting this

**Comment by otaviobp** [comment]
I updated the manual and it will be available on next clear release
