### ISSUE TITLE
Add option to delay updates on metered connections

### ISSUE THREAD

**Issue by slrtbtfs** [clearlinux/swupd-client#962]
**Problem Description:**
I'm using clear linux with a laptop, which does not always have a LAN or WIFI connection (e.g. when travelling). In this case it falls back to a metered and costly Mobile Broadband connection. If swupd is updating while on such a connection it might quickly use up my data volume.

**Enhancement Idea:**
Add an option in the swupd configuration to not update while on a metered connection.

Whether an connection is metered can be found out using NetworkManager.

**Comment by miguelinux** [comment]
Have you seen
https://github.com/clearlinux/distribution/issues/893

Does it work for you?

**Comment by slrtbtfs** [comment]
Nope, hadn't seen that. That one seems quite useful. Thanks.

I guess using that approach together with something like https://unix.stackexchange.com/questions/210604/how-to-write-a-systemd-service-unit-file-so-it-waits-until-a-specific-interface I'll manage to implement the desired functionality myself.

Is there any place where such Clear Linux* "tricks" are collected for users that might face the same problem in the future (sth. like the arch wiki)? If there is, I might add it there.

**Comment by miguelinux** [comment]
> Is there any place where such Clear Linux* "tricks" are collected for users that might face the same problem in the future (sth. like the arch wiki)? If there is, I might add it there.
> 

You can post it in the CL Forums

https://community.clearlinux.org/c/news/guides

Under Tutorias and Guides
