### ISSUE TITLE
resume support with bundle-add

### ISSUE THREAD

**Issue by nazar2sfive** [clearlinux/swupd-client#984]
i tried the same command and it started downloading from the start.

is there no resume support?

![image](https://user-images.githubusercontent.com/12841320/60872087-c86bbd00-a253-11e9-8764-638b461a7980.png)

**Comment by otaviobp** [comment]
Thanks for the report.
Swupd download resume is automatic. First swupd won't try to download the same pack twice, so if we have completed pack downloads the list from second execution should be smaller than first execution and the total download size too.
If there's a partial file download we also try to resume from where we stopped, if there's no corruption and if the server supports it.
Can you share the full log of the 2 executions of swupd to check if the download resume is broken for you? If you want to check each file swupd is downloading and if any partial file was used you can run swupd with the flag --debug.

**Comment by otaviobp** [comment]
Closing ticket as we aren't able to reproduce the reported problem. Please, reopen if you still think it's a bug.
Thanks
